// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDataFormatNifTypes.pas
// Generated by `cargo xtask port-defs emit-df`. Do not edit.

#![allow(
    clippy::all,
    unused_mut,
    unused_variables,
    unused_parens,
    unused_imports,
    unused_assignments,
    non_snake_case,
    dead_code
)]

use super::*;

/// Upstream `wbByteFloat` (line 226).
pub fn wb_byte_float(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_integer(a_name, DataType::U8, "0.0", a_events);
    result.events.on_get_text = Some(byte_float_get_text);
    result.events.on_set_text = Some(byte_float_set_text);
    result
}

/// Upstream `wbByteFloat` (line 233).
pub fn wb_byte_float_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_byte_float(a_name, &[]);
    result
}

/// Upstream `wbHexByte` (line 250).
pub fn wb_hex_byte(a_name: &str) -> Def {
    let mut result: Def;
    result = df_integer(
        a_name,
        DataType::U8,
        "",
        &[Event::GetText(get_text_hex_byte), Event::SetText(set_text_hex_byte)],
    );
    result
}

/// Upstream `wbHexFloat` (line 274).
pub fn wb_hex_float(a_name: &str) -> Def {
    let mut result: Def;
    result = df_float(
        a_name,
        DataType::Float32,
        "",
        &[Event::GetText(get_text_hex_float), Event::SetText(set_text_hex_float)],
    );
    result
}

/// Upstream `wbShortString` (line 282).
pub fn wb_short_string(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_chars(a_name, -1 as i32, "", 0u8, true, a_events);
    result
}

/// Upstream `wbShortString` (line 287).
pub fn wb_short_string_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_short_string(a_name, &[]);
    result
}

/// Upstream `wbSizedString` (line 292).
pub fn wb_sized_string(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_chars(a_name, -4 as i32, a_default_value, 0u8, false, a_events);
    result
}

/// Upstream `wbSizedString` (line 297).
pub fn wb_sized_string_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_sized_string(a_name, "", a_events);
    result
}

/// Upstream `wbSizedString` (line 302).
pub fn wb_sized_string_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_sized_string(a_name, "", &[]);
    result
}

/// Upstream `wbByteArray` (line 307).
pub fn wb_byte_array(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_bytes(a_name, -4 as i32, a_events);
    result
}

/// Upstream `wbByteArray` (line 312).
pub fn wb_byte_array_name(a_name: &str) -> Def {
    let mut result: Def;
    result = df_bytes(a_name, -4 as i32, &[]);
    result
}

/// Upstream `wbMatchGroup` (line 317).
pub fn wb_match_group(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_array(
        a_name,
        df_integer("Vertex Indices", DataType::U16, "", &[]),
        -2 as i32,
        "",
        a_events,
    );
    result
}

/// Upstream `wbMatchGroup` (line 322).
pub fn wb_match_group_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_match_group(a_name, &[]);
    result
}

/// Upstream `wbVector3` (line 327).
pub fn wb_vector3(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("X", DataType::Float32, "", &[]),
            df_float("Y", DataType::Float32, "", &[]),
            df_float("Z", DataType::Float32, "", &[]),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbVector3` (line 336).
pub fn wb_vector3_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_vector3(a_name, "", a_events);
    result
}

/// Upstream `wbVector3` (line 341).
pub fn wb_vector3_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_vector3_name_events(a_name, &[]);
    result
}

/// Upstream `wbVector4` (line 346).
pub fn wb_vector4(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("X", DataType::Float32, "", &[]),
            df_float("Y", DataType::Float32, "", &[]),
            df_float("Z", DataType::Float32, "", &[]),
            df_float("W", DataType::Float32, "", &[]),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbVector4` (line 356).
pub fn wb_vector4_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_vector4(a_name, "", a_events);
    result
}

/// Upstream `wbVector4` (line 361).
pub fn wb_vector4_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_vector4_name_events(a_name, &[]);
    result
}

/// Upstream `wbHalfVector3` (line 366).
pub fn wb_half_vector3(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("X", DataType::Float16, "", &[]),
            df_float("Y", DataType::Float16, "", &[]),
            df_float("Z", DataType::Float16, "", &[]),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbHalfVector3` (line 375).
pub fn wb_half_vector3_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_half_vector3(a_name, "", a_events);
    result
}

/// Upstream `wbHalfVector3` (line 380).
pub fn wb_half_vector3_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_half_vector3_name_events(a_name, &[]);
    result
}

/// Upstream `wbByteVector3` (line 385).
pub fn wb_byte_vector3(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            wb_byte_float_name("X"),
            wb_byte_float_name("Y"),
            wb_byte_float_name("Z"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbByteVector3` (line 394).
pub fn wb_byte_vector3_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_byte_vector3(a_name, "", a_events);
    result
}

/// Upstream `wbByteVector3` (line 399).
pub fn wb_byte_vector3_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_byte_vector3_name_events(a_name, &[]);
    result
}

/// Upstream `wbColor3` (line 404).
pub fn wb_color3(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![wb_hex_float("R"), wb_hex_float("G"), wb_hex_float("B")],
        a_default_value,
        a_events,
    );
    result.events.on_get_text = Some(get_text_hex_color);
    result.events.on_set_text = Some(set_text_hex_color);
    result
}

/// Upstream `wbColor3` (line 416).
pub fn wb_color3_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_color3(a_name, "#FFFFFF", a_events);
    result
}

/// Upstream `wbColor3` (line 421).
pub fn wb_color3_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_color3_name_events(a_name, &[]);
    result
}

/// Upstream `wbColor4` (line 426).
pub fn wb_color4(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            wb_hex_float("R"),
            wb_hex_float("G"),
            wb_hex_float("B"),
            wb_hex_float("A"),
        ],
        a_default_value,
        a_events,
    );
    result.events.on_get_text = Some(get_text_hex_color);
    result.events.on_set_text = Some(set_text_hex_color);
    result
}

/// Upstream `wbColor4` (line 439).
pub fn wb_color4_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_color4(a_name, "#FFFFFFFF", a_events);
    result
}

/// Upstream `wbColor4` (line 444).
pub fn wb_color4_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_color4_name_events(a_name, &[]);
    result
}

/// Upstream `wbByteColor4` (line 449).
pub fn wb_byte_color4(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![wb_hex_byte("R"), wb_hex_byte("G"), wb_hex_byte("B"), wb_hex_byte("A")],
        a_default_value,
        a_events,
    );
    result.set_delimiter("");
    result.events.on_get_text = Some(get_text_hex_color);
    result.events.on_set_text = Some(set_text_hex_color);
    result
}

/// Upstream `wbByteColor4` (line 462).
pub fn wb_byte_color4_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_byte_color4(a_name, "#FFFFFFFF", a_events);
    result
}

/// Upstream `wbByteColor4` (line 467).
pub fn wb_byte_color4_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_byte_color4_name_events(a_name, &[]);
    result
}

/// Upstream `wbQuaternion` (line 541).
pub fn wb_quaternion(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("W", DataType::Float32, "1.0", &[]),
            df_float("X", DataType::Float32, "", &[]),
            df_float("Y", DataType::Float32, "", &[]),
            df_float("Z", DataType::Float32, "", &[]),
        ],
        "",
        a_events,
    );
    result.events.on_get_text = Some(quaternion_get_text);
    result.events.on_set_text = Some(quaternion_set_text);
    result
}

/// Upstream `wbQuaternion` (line 553).
pub fn wb_quaternion_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_quaternion(a_name, &[]);
    result
}

/// Upstream `wbhkQuaternion` (line 558).
pub fn wbhk_quaternion(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("X", DataType::Float32, "", &[]),
            df_float("Y", DataType::Float32, "", &[]),
            df_float("Z", DataType::Float32, "", &[]),
            df_float("W", DataType::Float32, "1.0", &[]),
        ],
        "",
        a_events,
    );
    result.events.on_get_text = Some(quaternion_get_text);
    result.events.on_set_text = Some(quaternion_set_text);
    result
}

/// Upstream `wbhkQuaternion` (line 570).
pub fn wbhk_quaternion_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wbhk_quaternion(a_name, &[]);
    result
}

/// Upstream `wbMatrix22` (line 575).
pub fn wb_matrix22(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_float("m11", DataType::Float32, "1.0", &[]),
            df_float("m21", DataType::Float32, "", &[]),
            df_float("m12", DataType::Float32, "", &[]),
            df_float("m22", DataType::Float32, "1.0", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbMatrix22` (line 585).
pub fn wb_matrix22_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_matrix22(a_name, &[]);
    result
}

/// Upstream `wbMatrix33` (line 590).
pub fn wb_matrix33(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_float("m11", DataType::Float32, "1.0", &[]),
            df_float("m21", DataType::Float32, "", &[]),
            df_float("m31", DataType::Float32, "", &[]),
            df_float("m12", DataType::Float32, "", &[]),
            df_float("m22", DataType::Float32, "1.0", &[]),
            df_float("m32", DataType::Float32, "", &[]),
            df_float("m13", DataType::Float32, "", &[]),
            df_float("m23", DataType::Float32, "", &[]),
            df_float("m33", DataType::Float32, "1.0", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbMatrix33` (line 605).
pub fn wb_matrix33_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_matrix33(a_name, &[]);
    result
}

/// Upstream `wbRotMatrix33` (line 665).
pub fn wb_rot_matrix33(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("m11", DataType::Float32, "1.0", &[]),
            df_float("m21", DataType::Float32, "", &[]),
            df_float("m31", DataType::Float32, "", &[]),
            df_float("m12", DataType::Float32, "", &[]),
            df_float("m22", DataType::Float32, "1.0", &[]),
            df_float("m32", DataType::Float32, "", &[]),
            df_float("m13", DataType::Float32, "", &[]),
            df_float("m23", DataType::Float32, "", &[]),
            df_float("m33", DataType::Float32, "1.0", &[]),
        ],
        "",
        a_events,
    );
    result.events.on_get_text = Some(rot_matrix33_get_text);
    result.events.on_set_text = Some(rot_matrix33_set_text);
    result
}

/// Upstream `wbRotMatrix33` (line 682).
pub fn wb_rot_matrix33_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_rot_matrix33(a_name, &[]);
    result
}

/// Upstream `wbMatrix44` (line 687).
pub fn wb_matrix44(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_float("m11", DataType::Float32, "1.0", &[]),
            df_float("m21", DataType::Float32, "", &[]),
            df_float("m31", DataType::Float32, "", &[]),
            df_float("m41", DataType::Float32, "", &[]),
            df_float("m12", DataType::Float32, "", &[]),
            df_float("m22", DataType::Float32, "1.0", &[]),
            df_float("m32", DataType::Float32, "", &[]),
            df_float("m42", DataType::Float32, "", &[]),
            df_float("m13", DataType::Float32, "", &[]),
            df_float("m23", DataType::Float32, "", &[]),
            df_float("m33", DataType::Float32, "1.0", &[]),
            df_float("m43", DataType::Float32, "", &[]),
            df_float("m14", DataType::Float32, "", &[]),
            df_float("m24", DataType::Float32, "", &[]),
            df_float("m34", DataType::Float32, "", &[]),
            df_float("m44", DataType::Float32, "1.0", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbMatrix44` (line 709).
pub fn wb_matrix44_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_matrix44(a_name, &[]);
    result
}

/// Upstream `wbhkMatrix3` (line 714).
pub fn wbhk_matrix3(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_float("m11", DataType::Float32, "1.0", &[]),
            df_float("m12", DataType::Float32, "", &[]),
            df_float("m13", DataType::Float32, "", &[]),
            df_float("Unused m14", DataType::Float32, "", &[]),
            df_float("m21", DataType::Float32, "", &[]),
            df_float("m22", DataType::Float32, "1.0", &[]),
            df_float("m23", DataType::Float32, "", &[]),
            df_float("Unused m24", DataType::Float32, "", &[]),
            df_float("m31", DataType::Float32, "", &[]),
            df_float("m32", DataType::Float32, "", &[]),
            df_float("m33", DataType::Float32, "1.0", &[]),
            df_float("Unused m34", DataType::Float32, "", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbhkMatrix3` (line 732).
pub fn wbhk_matrix3_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wbhk_matrix3(a_name, &[]);
    result
}

/// Upstream `wbTBC` (line 737).
pub fn wb_tbc(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_float("T", DataType::Float32, "", &[]),
            df_float("B", DataType::Float32, "", &[]),
            df_float("C", DataType::Float32, "", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbNiPlane` (line 746).
pub fn wb_ni_plane(a_name: &str) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            wb_vector3_name("Normal"),
            df_float("Constant", DataType::Float32, "", &[]),
        ],
        &[],
    );
    result
}

/// Upstream `wbNiBound` (line 754).
pub fn wb_ni_bound(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            wb_vector3_name("Center"),
            df_float("Radius", DataType::Float32, "", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbNiBound` (line 762).
pub fn wb_ni_bound_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_ni_bound(a_name, &[]);
    result
}

/// Upstream `wbNiQuatTransform` (line 767).
pub fn wb_ni_quat_transform(a_name: &str) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            wb_vector3_name("Translation"),
            wb_quaternion_name("Rotation"),
            df_float("Scale", DataType::Float32, "1.0", &[]),
        ],
        &[],
    );
    result
}

/// Upstream `wbNiTransform` (line 776).
pub fn wb_ni_transform(a_name: &str) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            wb_rot_matrix33_name("Rotation"),
            wb_vector3_name("Translation"),
            df_float("Scale", DataType::Float32, "1.0", &[]),
        ],
        &[],
    );
    result
}

/// Upstream `wbMTransform` (line 785).
pub fn wb_m_transform(a_name: &str) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            wb_vector3_name("Translation"),
            wb_rot_matrix33("Rotation", &[]),
            df_float("Scale", DataType::Float32, "1.0", &[]),
        ],
        &[],
    );
    result
}

/// Upstream `wbTexCoord` (line 795).
pub fn wb_tex_coord(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("U", DataType::Float32, "", &[]),
            df_float("V", DataType::Float32, "", &[]),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbTexCoord` (line 803).
pub fn wb_tex_coord_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_tex_coord(a_name, "", a_events);
    result
}

/// Upstream `wbTexCoord` (line 808).
pub fn wb_tex_coord_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_tex_coord_name_events(a_name, &[]);
    result
}

/// Upstream `wbHalfTexCoord` (line 813).
pub fn wb_half_tex_coord(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_float("U", DataType::Float16, "", &[]),
            df_float("V", DataType::Float16, "", &[]),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbHalfTexCoord` (line 821).
pub fn wb_half_tex_coord_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_half_tex_coord(a_name, "", a_events);
    result
}

/// Upstream `wbHalfTexCoord` (line 826).
pub fn wb_half_tex_coord_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_half_tex_coord_name_events(a_name, &[]);
    result
}

/// Upstream `wbTriangle` (line 831).
pub fn wb_triangle(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_merge(
        a_name,
        vec![
            df_integer("V1", DataType::U16, "", &[]),
            df_integer("V2", DataType::U16, "", &[]),
            df_integer("V3", DataType::U16, "", &[]),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbTriangle` (line 840).
pub fn wb_triangle_name_events(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = wb_triangle(a_name, "", a_events);
    result
}

/// Upstream `wbTriangle` (line 845).
pub fn wb_triangle_name(a_name: &str) -> Def {
    let mut result: Def;
    result = wb_triangle_name_events(a_name, &[]);
    result
}

/// Upstream `wbAlphaFormat` (line 850).
pub fn wb_alpha_format(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "ALPHA_NONE"),
            (1, "ALPHA_BINARY"),
            (2, "ALPHA_SMOOTH"),
            (3, "ALPHA_DEFAULT"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBSPartFlag` (line 860).
pub fn wb_bs_part_flag(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[(0, "PF_EDITOR_VISIBLE"), (8, "PF_START_NET_BONESET")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBSDismemberBodyPartType` (line 868).
pub fn wb_bs_dismember_body_part_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U16,
        &[
            (0, "BP_TORSO"),
            (1, "BP_HEAD"),
            (2, "BP_HEAD2"),
            (3, "BP_LEFTARM"),
            (4, "BP_LEFTARM2"),
            (5, "BP_RIGHTARM"),
            (6, "BP_RIGHTARM2"),
            (7, "BP_LEFTLEG"),
            (8, "BP_LEFTLEG2"),
            (9, "BP_LEFTLEG3"),
            (10, "BP_RIGHTLEG"),
            (11, "BP_RIGHTLEG2"),
            (12, "BP_RIGHTLEG3"),
            (13, "BP_BRAIN"),
            (30, "SBP_30_HEAD"),
            (31, "SBP_31_HAIR"),
            (32, "SBP_32_BODY"),
            (33, "SBP_33_HANDS"),
            (34, "SBP_34_FOREARMS"),
            (35, "SBP_35_AMULET"),
            (36, "SBP_36_RING"),
            (37, "SBP_37_FEET"),
            (38, "SBP_38_CALVES"),
            (39, "SBP_39_SHIELD"),
            (40, "SBP_40_TAIL"),
            (41, "SBP_41_LONGHAIR"),
            (42, "SBP_42_CIRCLET"),
            (43, "SBP_43_EARS"),
            (44, "SBP_44_DRAGON_BLOODHEAD_OR_MOD_MOUTH"),
            (45, "SBP_45_DRAGON_BLOODWINGL_OR_MOD_NECK"),
            (46, "SBP_46_DRAGON_BLOODWINGR_OR_MOD_CHEST_PRIMARY"),
            (47, "SBP_47_DRAGON_BLOODTAIL_OR_MOD_BACK"),
            (48, "SBP_48_MOD_MISC1"),
            (49, "SBP_49_MOD_PELVIS_PRIMARY"),
            (50, "SBP_50_DECAPITATEDHEAD"),
            (51, "SBP_51_DECAPITATE"),
            (52, "SBP_52_MOD_PELVIS_SECONDARY"),
            (53, "SBP_53_MOD_LEG_RIGHT"),
            (54, "SBP_54_MOD_LEG_LEFT"),
            (55, "SBP_55_MOD_FACE_JEWELRY"),
            (56, "SBP_56_MOD_CHEST_SECONDARY"),
            (57, "SBP_57_MOD_SHOULDER"),
            (58, "SBP_58_MOD_ARM_LEFT"),
            (59, "SBP_59_MOD_ARM_RIGHT"),
            (60, "SBP_60_MOD_MISC2"),
            (61, "SBP_61_FX01"),
            (101, "BP_SECTIONCAP_HEAD"),
            (102, "BP_SECTIONCAP_HEAD2"),
            (103, "BP_SECTIONCAP_LEFTARM"),
            (104, "BP_SECTIONCAP_LEFTARM2"),
            (105, "BP_SECTIONCAP_RIGHTARM"),
            (106, "BP_SECTIONCAP_RIGHTARM2"),
            (107, "BP_SECTIONCAP_LEFTLEG"),
            (108, "BP_SECTIONCAP_LEFTLEG2"),
            (109, "BP_SECTIONCAP_LEFTLEG3"),
            (110, "BP_SECTIONCAP_RIGHTLEG"),
            (111, "BP_SECTIONCAP_RIGHTLEG2"),
            (112, "BP_SECTIONCAP_RIGHTLEG3"),
            (113, "BP_SECTIONCAP_BRAIN"),
            (130, "SBP_130_HEAD"),
            (131, "SBP_131_HAIR"),
            (141, "SBP_141_LONGHAIR"),
            (142, "SBP_142_CIRCLET"),
            (143, "SBP_143_EARS"),
            (150, "SBP_150_DECAPITATEDHEAD"),
            (201, "BP_TORSOCAP_HEAD"),
            (202, "BP_TORSOCAP_HEAD2"),
            (203, "BP_TORSOCAP_LEFTARM"),
            (204, "BP_TORSOCAP_LEFTARM2"),
            (205, "BP_TORSOCAP_RIGHTARM"),
            (206, "BP_TORSOCAP_RIGHTARM2"),
            (207, "BP_TORSOCAP_LEFTLEG"),
            (208, "BP_TORSOCAP_LEFTLEG2"),
            (209, "BP_TORSOCAP_LEFTLEG3"),
            (210, "BP_TORSOCAP_RIGHTLEG"),
            (211, "BP_TORSOCAP_RIGHTLEG2"),
            (212, "BP_TORSOCAP_RIGHTLEG3"),
            (213, "BP_TORSOCAP_BRAIN"),
            (230, "SBP_230_HEAD"),
            (1000, "BP_TORSOSECTION_HEAD"),
            (2000, "BP_TORSOSECTION_HEAD2"),
            (3000, "BP_TORSOSECTION_LEFTARM"),
            (4000, "BP_TORSOSECTION_LEFTARM2"),
            (5000, "BP_TORSOSECTION_RIGHTARM"),
            (6000, "BP_TORSOSECTION_RIGHTARM2"),
            (7000, "BP_TORSOSECTION_LEFTLEG"),
            (8000, "BP_TORSOSECTION_LEFTLEG2"),
            (9000, "BP_TORSOSECTION_LEFTLEG3"),
            (10000, "BP_TORSOSECTION_RIGHTLEG"),
            (11000, "BP_TORSOSECTION_RIGHTLEG2"),
            (12000, "BP_TORSOSECTION_RIGHTLEG3"),
            (13000, "BP_TORSOSECTION_BRAIN"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBodyPartList` (line 966).
pub fn wb_body_part_list(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            wb_bs_part_flag("Part Flags", "257", &[]),
            wb_bs_dismember_body_part_type("Body Part", "", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbBSGeometrySegmentData` (line 974).
pub fn wb_bs_geometry_segment_data(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_integer("Flags", DataType::U8, "", &[]),
            df_integer("Index", DataType::U32, "", &[]),
            df_integer("Num Tris in Segment", DataType::U32, "", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbBSShaderType` (line 983).
pub fn wb_bs_shader_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "SHADER_TALL_GRASS"),
            (1, "SHADER_DEFAULT"),
            (10, "SHADER_SKY"),
            (14, "SHADER_SKIN"),
            (17, "SHADER_WATER"),
            (29, "SHADER_LIGHTING30"),
            (32, "SHADER_TILE"),
            (33, "SHADER_NOLIGHTING"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBSShaderFlags` (line 997).
pub fn wb_bs_shader_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U32,
        &[
            (0, "Specular"),
            (1, "Skinned"),
            (2, "LowDetail"),
            (3, "Vertex_Alpha"),
            (4, "Motion_Blur"),
            (5, "Single_Pass"),
            (6, "Empty"),
            (7, "Environment_Mapping"),
            (8, "Alpha_Texture"),
            (9, "Z_Prepass"),
            (10, "FaceGen"),
            (11, "Parallax_Shader_Index_15"),
            (12, "Model_Space_Normals"),
            (13, "Non_Projective_Shadows"),
            (14, "Landscape"),
            (15, "Refraction"),
            (16, "Fire_Refraction"),
            (17, "Eye_Environment_Mapping"),
            (18, "Hair"),
            (19, "Dynamic_Alpha"),
            (20, "Localmap_Hide_Secret"),
            (21, "Window_Environment_Mapping"),
            (22, "Tree_Billboard"),
            (23, "Shadow_Frustum"),
            (24, "Multiple_Textures"),
            (25, "Remappable_Textures"),
            (26, "Decal_Single_Pass"),
            (27, "Dynamic_Decal_Single_Pass"),
            (28, "Parallax_Occlusion"),
            (29, "External_Emittance"),
            (30, "Shadow_Map"),
            (31, "ZBuffer_Test"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBSShaderFlags2` (line 1035).
pub fn wb_bs_shader_flags2(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U32,
        &[
            (0, "ZBuffer_Write"),
            (1, "LOD_Landscape"),
            (2, "LOD_Building"),
            (3, "No_Fade"),
            (4, "Refraction_Tint"),
            (5, "Vertex_Colors"),
            (6, "1st_person"),
            (7, "1st_Light_is_Point_Light"),
            (8, "2nd_Light"),
            (9, "3rd_Light"),
            (10, "Vertex_Lighting"),
            (11, "Uniform_Scale"),
            (12, "Fit_Slope"),
            (13, "Billboard_and_Envmap_Light_Fade"),
            (14, "No_LOD_Land_Blend"),
            (15, "Envmap_Light_Fade"),
            (16, "Wireframe"),
            (17, "VATS_Selection"),
            (18, "Show_in_Local_Map"),
            (19, "Premult_Alpha"),
            (20, "Skip_Normal_Maps"),
            (21, "Alpha_Decal"),
            (22, "No_Transparency_Multisampling"),
            (23, "Stinger_Prop"),
            (24, "Unknown3"),
            (25, "Unknown4"),
            (26, "Unknown5"),
            (27, "Unknown6"),
            (28, "Unknown7"),
            (29, "Unknown8"),
            (30, "Unknown9"),
            (31, "Unknown10"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBSLightingShaderPropertyShaderType` (line 1073).
pub fn wb_bs_lighting_shader_property_shader_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "Default"),
            (1, "Environment Map"),
            (2, "Glow Shader"),
            (3, "Parallax"),
            (4, "Facegen"),
            (5, "Skin Tint"),
            (6, "Hair Tint"),
            (7, "Parallax Occ"),
            (8, "Multitexture Landscape"),
            (9, "LOD Landscape"),
            (10, "Snow"),
            (11, "MultiLayer Parallax"),
            (12, "Tree Anim"),
            (13, "LOD Objects"),
            (14, "Sparkle Snow"),
            (15, "LOD Objects HD"),
            (16, "Eye Envmap"),
            (17, "Cloud"),
            (18, "LOD Landscape Noise"),
            (19, "Multitexture Landscape LOD Blend"),
            (20, "FO4 Dismemberment"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbEffectShaderControlledVariable` (line 1100).
pub fn wb_effect_shader_controlled_variable(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "EmissiveMultiple"),
            (1, "Falloff Start Angle"),
            (2, "Falloff Stop Angle"),
            (3, "Falloff Start Opacity"),
            (4, "Falloff Stop Opacity"),
            (5, "Alpha Transparency"),
            (6, "U Offset"),
            (7, "U Scale"),
            (8, "V Offset"),
            (9, "V Scale"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbEffectShaderControlledColor` (line 1116).
pub fn wb_effect_shader_controlled_color(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "Emissive Color")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbLightingShaderControlledVariable` (line 1123).
pub fn wb_lighting_shader_controlled_variable(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "Refraction Strength"),
            (8, "Environment Map Scale"),
            (9, "Glossiness"),
            (10, "Specular Strength"),
            (11, "Emissive Multiple"),
            (12, "Alpha"),
            (20, "U Offset"),
            (21, "U Scale"),
            (22, "V Offset"),
            (23, "V Scale"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbLightingShaderControlledColor` (line 1139).
pub fn wb_lighting_shader_controlled_color(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "Specular Color"), (1, "Emissive Color")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbSkyrimWaterShaderFlags` (line 1147).
pub fn wb_skyrim_water_shader_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U8,
        &[
            (0, "SWSF1_UNKNOWN0"),
            (1, "SWSF1_Bypass_Refraction_Map"),
            (2, "SWSF1_Water_Toggle"),
            (3, "SWSF1_UNKNOWN3"),
            (4, "SWSF1_UNKNOWN4"),
            (5, "SWSF1_UNKNOWN5"),
            (6, "SWSF1_Highlight_Layer_Toggle"),
            (7, "SWSF1_Enabled"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbSkyObjectType` (line 1161).
pub fn wb_sky_object_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "BSSM_SKY_TEXTURE"),
            (1, "BSSM_SKY_SUNGLARE"),
            (2, "BSSM_SKY"),
            (3, "BSSM_SKY_CLOUDS"),
            (5, "BSSM_SKY_STARS"),
            (7, "BSSM_SKY_MOON_STARS_MASK"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBroadPhaseType` (line 1173).
pub fn wb_broad_phase_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "BROAD_PHASE_INVALID"),
            (1, "BROAD_PHASE_ENTITY"),
            (2, "BROAD_PHASE_PHANTOM"),
            (3, "BROAD_PHASE_BORDER"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbhkResponseType` (line 1183).
pub fn wbhk_response_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "RESPONSE_INVALID"),
            (1, "RESPONSE_SIMPLE_CONTACT"),
            (2, "RESPONSE_REPORTING"),
            (3, "RESPONSE_NONE"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbhkConstraintType` (line 1193).
pub fn wbhk_constraint_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "Ball And Socket"),
            (1, "Hinge"),
            (2, "Limited Hinge"),
            (6, "Prismatic"),
            (7, "Ragdoll"),
            (8, "Stiff Spring"),
            (13, "Malleable"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbApplyMode` (line 1206).
pub fn wb_apply_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "APPLY_REPLACE"),
            (1, "APPLY_DECAL"),
            (2, "APPLY_MODULATE"),
            (3, "APPLY_HILIGHT"),
            (4, "APPLY_HILIGHT2"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbTexType` (line 1217).
pub fn wb_tex_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "BASE_MAP"),
            (1, "DARK_MAP"),
            (2, "DETAIL_MAP"),
            (3, "GLOSS_MAP"),
            (4, "GLOW_MAP"),
            (5, "BUMP_MAP"),
            (6, "NORMAL_MAP"),
            (7, "PARALLAX_MAP"),
            (8, "DECAL_0_MAP"),
            (9, "DECAL_1_MAP"),
            (10, "DECAL_2_MAP"),
            (11, "DECAL_3_MAP"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbKeyType` (line 1235).
pub fn wb_key_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (1, "LINEAR_KEY"),
            (2, "QUADRATIC_KEY"),
            (3, "TBC_KEY"),
            (4, "XYZ_ROTATION_KEY"),
            (5, "CONST_KEY"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbLightMode` (line 1246).
pub fn wb_light_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "LIGHT_MODE_EMISSIVE"), (1, "LIGHT_MODE_EMI_AMB_DIF")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbOblivionHavokMaterial` (line 1254).
pub fn wb_oblivion_havok_material(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "OB_HAV_MAT_STONE"),
            (1, "OB_HAV_MAT_CLOTH"),
            (2, "OB_HAV_MAT_DIRT"),
            (3, "OB_HAV_MAT_GLASS"),
            (4, "OB_HAV_MAT_GRASS"),
            (5, "OB_HAV_MAT_METAL"),
            (6, "OB_HAV_MAT_ORGANIC"),
            (7, "OB_HAV_MAT_SKIN"),
            (8, "OB_HAV_MAT_WATER"),
            (9, "OB_HAV_MAT_WOOD"),
            (10, "OB_HAV_MAT_HEAVY_STONE"),
            (11, "OB_HAV_MAT_HEAVY_METAL"),
            (12, "OB_HAV_MAT_HEAVY_WOOD"),
            (13, "OB_HAV_MAT_CHAIN"),
            (14, "OB_HAV_MAT_SNOW"),
            (15, "OB_HAV_MAT_STONE_STAIRS"),
            (16, "OB_HAV_MAT_CLOTH_STAIRS"),
            (17, "OB_HAV_MAT_DIRT_STAIRS"),
            (18, "OB_HAV_MAT_GLASS_STAIRS"),
            (19, "OB_HAV_MAT_GRASS_STAIRS"),
            (20, "OB_HAV_MAT_METAL_STAIRS"),
            (21, "OB_HAV_MAT_ORGANIC_STAIRS"),
            (22, "OB_HAV_MAT_SKIN_STAIRS"),
            (23, "OB_HAV_MAT_WATER_STAIRS"),
            (24, "OB_HAV_MAT_WOOD_STAIRS"),
            (25, "OB_HAV_MAT_HEAVY_STONE_STAIRS"),
            (26, "OB_HAV_MAT_HEAVY_METAL_STAIRS"),
            (27, "OB_HAV_MAT_HEAVY_WOOD_STAIRS"),
            (28, "OB_HAV_MAT_CHAIN_STAIRS"),
            (29, "OB_HAV_MAT_SNOW_STAIRS"),
            (30, "OB_HAV_MAT_ELEVATOR"),
            (31, "OB_HAV_MAT_RUBBER"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbFallout3HavokMaterial` (line 1292).
pub fn wb_fallout3_havok_material(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "FO_HAV_MAT_STONE"),
            (1, "FO_HAV_MAT_CLOTH"),
            (2, "FO_HAV_MAT_DIRT"),
            (3, "FO_HAV_MAT_GLASS"),
            (4, "FO_HAV_MAT_GRASS"),
            (5, "FO_HAV_MAT_METAL"),
            (6, "FO_HAV_MAT_ORGANIC"),
            (7, "FO_HAV_MAT_SKIN"),
            (8, "FO_HAV_MAT_WATER"),
            (9, "FO_HAV_MAT_WOOD"),
            (10, "FO_HAV_MAT_HEAVY_STONE"),
            (11, "FO_HAV_MAT_HEAVY_METAL"),
            (12, "FO_HAV_MAT_HEAVY_WOOD"),
            (13, "FO_HAV_MAT_CHAIN"),
            (14, "FO_HAV_MAT_BOTTLECAP"),
            (15, "FO_HAV_MAT_ELEVATOR"),
            (16, "FO_HAV_MAT_HOLLOW_METAL"),
            (17, "FO_HAV_MAT_SHEET_METAL"),
            (18, "FO_HAV_MAT_SAND"),
            (19, "FO_HAV_MAT_BROKEN_CONCRETE"),
            (20, "FO_HAV_MAT_VEHICLE_BODY"),
            (21, "FO_HAV_MAT_VEHICLE_PART_SOLID"),
            (22, "FO_HAV_MAT_VEHICLE_PART_HOLLOW"),
            (23, "FO_HAV_MAT_BARREL"),
            (24, "FO_HAV_MAT_BOTTLE"),
            (25, "FO_HAV_MAT_SODA_CAN"),
            (26, "FO_HAV_MAT_PISTOL"),
            (27, "FO_HAV_MAT_RIFLE"),
            (28, "FO_HAV_MAT_SHOPPING_CART"),
            (29, "FO_HAV_MAT_LUNCHBOX"),
            (30, "FO_HAV_MAT_BABY_RATTLE"),
            (31, "FO_HAV_MAT_RUBBER_BALL"),
            (32, "FO_HAV_MAT_STONE_PLATFORM"),
            (33, "FO_HAV_MAT_CLOTH_PLATFORM"),
            (34, "FO_HAV_MAT_DIRT_PLATFORM"),
            (35, "FO_HAV_MAT_GLASS_PLATFORM"),
            (36, "FO_HAV_MAT_GRASS_PLATFORM"),
            (37, "FO_HAV_MAT_METAL_PLATFORM"),
            (38, "FO_HAV_MAT_ORGANIC_PLATFORM"),
            (39, "FO_HAV_MAT_SKIN_PLATFORM"),
            (40, "FO_HAV_MAT_WATER_PLATFORM"),
            (41, "FO_HAV_MAT_WOOD_PLATFORM"),
            (42, "FO_HAV_MAT_HEAVY_STONE_PLATFORM"),
            (43, "FO_HAV_MAT_HEAVY_METAL_PLATFORM"),
            (44, "FO_HAV_MAT_HEAVY_WOOD_PLATFORM"),
            (45, "FO_HAV_MAT_CHAIN_PLATFORM"),
            (46, "FO_HAV_MAT_BOTTLECAP_PLATFORM"),
            (47, "FO_HAV_MAT_ELEVATOR_PLATFORM"),
            (48, "FO_HAV_MAT_HOLLOW_METAL_PLATFORM"),
            (49, "FO_HAV_MAT_SHEET_METAL_PLATFORM"),
            (50, "FO_HAV_MAT_SAND_PLATFORM"),
            (51, "FO_HAV_MAT_BROKEN_CONCRETE_PLATFORM"),
            (52, "FO_HAV_MAT_VEHICLE_BODY_PLATFORM"),
            (53, "FO_HAV_MAT_VEHICLE_PART_SOLID_PLATFORM"),
            (54, "FO_HAV_MAT_VEHICLE_PART_HOLLOW_PLATFORM"),
            (55, "FO_HAV_MAT_BARREL_PLATFORM"),
            (56, "FO_HAV_MAT_BOTTLE_PLATFORM"),
            (57, "FO_HAV_MAT_SODA_CAN_PLATFORM"),
            (58, "FO_HAV_MAT_PISTOL_PLATFORM"),
            (59, "FO_HAV_MAT_RIFLE_PLATFORM"),
            (60, "FO_HAV_MAT_SHOPPING_CART_PLATFORM"),
            (61, "FO_HAV_MAT_LUNCHBOX_PLATFORM"),
            (62, "FO_HAV_MAT_BABY_RATTLE_PLATFORM"),
            (63, "FO_HAV_MAT_RUBBER_BALL_PLATFORM"),
            (64, "FO_HAV_MAT_STONE_STAIRS"),
            (65, "FO_HAV_MAT_CLOTH_STAIRS"),
            (66, "FO_HAV_MAT_DIRT_STAIRS"),
            (67, "FO_HAV_MAT_GLASS_STAIRS"),
            (68, "FO_HAV_MAT_GRASS_STAIRS"),
            (69, "FO_HAV_MAT_METAL_STAIRS"),
            (70, "FO_HAV_MAT_ORGANIC_STAIRS"),
            (71, "FO_HAV_MAT_SKIN_STAIRS"),
            (72, "FO_HAV_MAT_WATER_STAIRS"),
            (73, "FO_HAV_MAT_WOOD_STAIRS"),
            (74, "FO_HAV_MAT_HEAVY_STONE_STAIRS"),
            (75, "FO_HAV_MAT_HEAVY_METAL_STAIRS"),
            (76, "FO_HAV_MAT_HEAVY_WOOD_STAIRS"),
            (77, "FO_HAV_MAT_CHAIN_STAIRS"),
            (78, "FO_HAV_MAT_BOTTLECAP_STAIRS"),
            (79, "FO_HAV_MAT_ELEVATOR_STAIRS"),
            (80, "FO_HAV_MAT_HOLLOW_METAL_STAIRS"),
            (81, "FO_HAV_MAT_SHEET_METAL_STAIRS"),
            (82, "FO_HAV_MAT_SAND_STAIRS"),
            (83, "FO_HAV_MAT_BROKEN_CONCRETE_STAIRS"),
            (84, "FO_HAV_MAT_VEHICLE_BODY_STAIRS"),
            (85, "FO_HAV_MAT_VEHICLE_PART_SOLID_STAIRS"),
            (86, "FO_HAV_MAT_VEHICLE_PART_HOLLOW_STAIRS"),
            (87, "FO_HAV_MAT_BARREL_STAIRS"),
            (88, "FO_HAV_MAT_BOTTLE_STAIRS"),
            (89, "FO_HAV_MAT_SODA_CAN_STAIRS"),
            (90, "FO_HAV_MAT_PISTOL_STAIRS"),
            (91, "FO_HAV_MAT_RIFLE_STAIRS"),
            (92, "FO_HAV_MAT_SHOPPING_CART_STAIRS"),
            (93, "FO_HAV_MAT_LUNCHBOX_STAIRS"),
            (94, "FO_HAV_MAT_BABY_RATTLE_STAIRS"),
            (95, "FO_HAV_MAT_RUBBER_BALL_STAIRS"),
            (96, "FO_HAV_MAT_STONE_STAIRS_PLATFORM"),
            (97, "FO_HAV_MAT_CLOTH_STAIRS_PLATFORM"),
            (98, "FO_HAV_MAT_DIRT_STAIRS_PLATFORM"),
            (99, "FO_HAV_MAT_GLASS_STAIRS_PLATFORM"),
            (100, "FO_HAV_MAT_GRASS_STAIRS_PLATFORM"),
            (101, "FO_HAV_MAT_METAL_STAIRS_PLATFORM"),
            (102, "FO_HAV_MAT_ORGANIC_STAIRS_PLATFORM"),
            (103, "FO_HAV_MAT_SKIN_STAIRS_PLATFORM"),
            (104, "FO_HAV_MAT_WATER_STAIRS_PLATFORM"),
            (105, "FO_HAV_MAT_WOOD_STAIRS_PLATFORM"),
            (106, "FO_HAV_MAT_HEAVY_STONE_STAIRS_PLATFORM"),
            (107, "FO_HAV_MAT_HEAVY_METAL_STAIRS_PLATFORM"),
            (108, "FO_HAV_MAT_HEAVY_WOOD_STAIRS_PLATFORM"),
            (109, "FO_HAV_MAT_CHAIN_STAIRS_PLATFORM"),
            (110, "FO_HAV_MAT_BOTTLECAP_STAIRS_PLATFORM"),
            (111, "FO_HAV_MAT_ELEVATOR_STAIRS_PLATFORM"),
            (112, "FO_HAV_MAT_HOLLOW_METAL_STAIRS_PLATFORM"),
            (113, "FO_HAV_MAT_SHEET_METAL_STAIRS_PLATFORM"),
            (114, "FO_HAV_MAT_SAND_STAIRS_PLATFORM"),
            (115, "FO_HAV_MAT_BROKEN_CONCRETE_STAIRS_PLATFORM"),
            (116, "FO_HAV_MAT_VEHICLE_BODY_STAIRS_PLATFORM"),
            (117, "FO_HAV_MAT_VEHICLE_PART_SOLID_STAIRS_PLATFORM"),
            (118, "FO_HAV_MAT_VEHICLE_PART_HOLLOW_STAIRS_PLATFORM"),
            (119, "FO_HAV_MAT_BARREL_STAIRS_PLATFORM"),
            (120, "FO_HAV_MAT_BOTTLE_STAIRS_PLATFORM"),
            (121, "FO_HAV_MAT_SODA_CAN_STAIRS_PLATFORM"),
            (122, "FO_HAV_MAT_PISTOL_STAIRS_PLATFORM"),
            (123, "FO_HAV_MAT_RIFLE_STAIRS_PLATFORM"),
            (124, "FO_HAV_MAT_SHOPPING_CART_STAIRS_PLATFORM"),
            (125, "FO_HAV_MAT_LUNCHBOX_STAIRS_PLATFORM"),
            (126, "FO_HAV_MAT_BABY_RATTLE_STAIRS_PLATFORM"),
            (127, "FO_HAV_MAT_RUBBER_BALL_STAIRS_PLATFORM"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbSkyrimHavokMaterial` (line 1426).
pub fn wb_skyrim_havok_material(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "SKY_HAV_MAT_NONE"),
            (131151687, "SKY_HAV_MAT_STONE_BROKEN"),
            (165778930, "SKY_HAV_MAT_WEAPON_BLADE_1HAND_BLOCK"),
            (220124585, "SKY_HAV_MAT_MEAT"),
            (322207473, "SKY_HAV_MAT_CARRIAGE_WHEEL"),
            (346811165, "SKY_HAV_MAT_METAL_LIGHT"),
            (365420259, "SKY_HAV_MAT_WOOD_LIGHT"),
            (398949039, "SKY_HAV_MAT_SNOW"),
            (428587608, "SKY_HAV_MAT_GRAVEL"),
            (438912228, "SKY_HAV_MAT_METAL_CHAIN"),
            (493553910, "SKY_HAV_MAT_BOTTLE"),
            (500811281, "SKY_HAV_MAT_WOOD"),
            (534864873, "SKY_HAV_MAT_ASH"),
            (551270354, "SKY_HAV_MAT_STAIRS_METAL"),
            (591247106, "SKY_HAV_MAT_SKIN"),
            (593401068, "SKY_HAV_MAT_WEAPON_BLUNT_1HAND_BLOCK"),
            (668408902, "SKY_HAV_MAT_INSECT"),
            (732141076, "SKY_HAV_MAT_BARREL"),
            (781661019, "SKY_HAV_MAT_CERAMIC"),
            (790784366, "SKY_HAV_MAT_BASKET"),
            (873356572, "SKY_HAV_MAT_ICE"),
            (880200008, "SKY_HAV_MAT_STAIRS_GLASS"),
            (899511101, "SKY_HAV_MAT_STAIRS_STONE"),
            (1024582599, "SKY_HAV_MAT_WATER"),
            (1060167844, "SKY_HAV_MAT_WEAPON_BLADE_1HAND"),
            (1264672850, "SKY_HAV_MAT_BOOK"),
            (1286705471, "SKY_HAV_MAT_CARPET"),
            (1288358971, "SKY_HAV_MAT_METAL_SOLID"),
            (1305674443, "SKY_HAV_MAT_WEAPON_AXE"),
            (1312943906, "SKY_HAV_MAT_WEAPON_BLADE_2HAND_BLOCK"),
            (1322093133, "SKY_HAV_MAT_ORGANIC_LARGE"),
            (1461712277, "SKY_HAV_MAT_STAIRS_WOOD"),
            (1486385281, "SKY_HAV_MAT_MUD"),
            (1550912982, "SKY_HAV_MAT_BOULDER_SMALL"),
            (1560365355, "SKY_HAV_MAT_STAIRS_SNOW"),
            (1570821952, "SKY_HAV_MAT_STONE_HEAVY"),
            (1607128641, "SKY_HAV_MAT_WEAPON_BOWS_AND_STAVES"),
            (1730220269, "SKY_HAV_MAT_ALDUIN"),
            (1763418903, "SKY_HAV_MAT_WEAPON_BOWS_AND_STAVES_BLOCK"),
            (1803571212, "SKY_HAV_MAT_WOOD_AS_STAIRS"),
            (1848600814, "SKY_HAV_MAT_GRASS"),
            (1885326971, "SKY_HAV_MAT_BOULDER_LARGE"),
            (1886078335, "SKY_HAV_MAT_STONE_AS_STAIRS"),
            (2022742644, "SKY_HAV_MAT_WEAPON_BLADE_2HAND"),
            (2025794648, "SKY_HAV_MAT_BOTTLE_SMALL"),
            (2058949504, "SKY_HAV_MAT_BONE_ACTOR"),
            (2168343821, "SKY_HAV_MAT_SAND"),
            (2229413539, "SKY_HAV_MAT_METAL_HEAVY"),
            (2431524493, "SKY_HAV_MAT_ICE_FORM"),
            (2518321175, "SKY_HAV_MAT_DRAGON"),
            (2617944780, "SKY_HAV_MAT_WEAPON_BLADE_1HAND_SMALL"),
            (2632367422, "SKY_HAV_MAT_SKIN_SMALL"),
            (2742858142, "SKY_HAV_MAT_POTS_AND_PANS"),
            (2821299363, "SKY_HAV_MAT_SKIN_SKELETON"),
            (2872791301, "SKY_HAV_MAT_WEAPON_BLUNT_1HAND"),
            (2892392795, "SKY_HAV_MAT_STAIRS_STONE_BROKEN"),
            (2965929619, "SKY_HAV_MAT_SKIN_LARGE"),
            (2974920155, "SKY_HAV_MAT_ORGANIC"),
            (3049421844, "SKY_HAV_MAT_BONE"),
            (3070783559, "SKY_HAV_MAT_WOOD_HEAVY"),
            (3074114406, "SKY_HAV_MAT_CHAIN"),
            (3106094762, "SKY_HAV_MAT_DIRT"),
            (3312543676, "SKY_HAV_MAT_GHOST"),
            (3387452107, "SKY_HAV_MAT_SKIN_METAL_LARGE"),
            (3400476823, "SKY_HAV_MAT_WEAPON_AXE_BLOCK"),
            (3424720541, "SKY_HAV_MAT_ARMOR_LIGHT"),
            (3448167928, "SKY_HAV_MAT_SHIELD_LIGHT"),
            (3589100606, "SKY_HAV_MAT_COIN"),
            (3662306947, "SKY_HAV_MAT_WEAPON_BLUNT_2HAND_BLOCK"),
            (3702389584, "SKY_HAV_MAT_SHIELD_HEAVY"),
            (3708432437, "SKY_HAV_MAT_ARMOR_HEAVY"),
            (3725505938, "SKY_HAV_MAT_ARROW"),
            (3739830338, "SKY_HAV_MAT_GLASS"),
            (3741512247, "SKY_HAV_MAT_STONE"),
            (3764646153, "SKY_HAV_MAT_WATER_PUDDLE"),
            (3839073443, "SKY_HAV_MAT_CLOTH"),
            (3855001958, "SKY_HAV_MAT_SKIN_METAL_SMALL"),
            (3895166727, "SKY_HAV_MAT_WARD"),
            (3934839107, "SKY_HAV_MAT_WEB"),
            (3969592277, "SKY_HAV_MAT_MATERIAL_BLUNT_2HAND"),
            (4283869410, "SKY_HAV_MAT_BOULDER_MEDIUM"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbOblivionLayer` (line 1513).
pub fn wb_oblivion_layer(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "OL_UNIDENTIFIED"),
            (1, "OL_STATIC"),
            (2, "OL_ANIM_STATIC"),
            (3, "OL_TRANSPARENT"),
            (4, "OL_CLUTTER"),
            (5, "OL_WEAPON"),
            (6, "OL_PROJECTILE"),
            (7, "OL_SPELL"),
            (8, "OL_BIPED"),
            (9, "OL_TREES"),
            (10, "OL_PROPS"),
            (11, "OL_WATER"),
            (12, "OL_TRIGGER"),
            (13, "OL_TERRAIN"),
            (14, "OL_TRAP"),
            (15, "OL_NONCOLLIDABLE"),
            (16, "OL_CLOUD_TRAP"),
            (17, "OL_GROUND"),
            (18, "OL_PORTAL"),
            (19, "OL_STAIRS"),
            (20, "OL_CHAR_CONTROLLER"),
            (21, "OL_AVOID_BOX"),
            (22, "OL_UNKNOWN1"),
            (23, "OL_UNKNOWN2"),
            (24, "OL_CAMERA_PICK"),
            (25, "OL_ITEM_PICK"),
            (26, "OL_LINE_OF_SIGHT"),
            (27, "OL_PATH_PICK"),
            (28, "OL_CUSTOM_PICK_1"),
            (29, "OL_CUSTOM_PICK_2"),
            (30, "OL_SPELL_EXPLOSION"),
            (31, "OL_DROPPING_PICK"),
            (32, "OL_OTHER"),
            (33, "OL_HEAD"),
            (34, "OL_BODY"),
            (35, "OL_SPINE1"),
            (36, "OL_SPINE2"),
            (37, "OL_L_UPPER_ARM"),
            (38, "OL_L_FOREARM"),
            (39, "OL_L_HAND"),
            (40, "OL_L_THIGH"),
            (41, "OL_L_CALF"),
            (42, "OL_L_FOOT"),
            (43, "OL_R_UPPER_ARM"),
            (44, "OL_R_FOREARM"),
            (45, "OL_R_HAND"),
            (46, "OL_R_THIGH"),
            (47, "OL_R_CALF"),
            (48, "OL_R_FOOT"),
            (49, "OL_TAIL"),
            (50, "OL_SIDE_WEAPON"),
            (51, "OL_SHIELD"),
            (52, "OL_QUIVER"),
            (53, "OL_BACK_WEAPON"),
            (54, "OL_BACK_WEAPON2"),
            (55, "OL_PONYTAIL"),
            (56, "OL_WING"),
            (57, "OL_NULL"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbFallout3Layer` (line 1577).
pub fn wb_fallout3_layer(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "FOL_UNIDENTIFIED"),
            (1, "FOL_STATIC"),
            (2, "FOL_ANIM_STATIC"),
            (3, "FOL_TRANSPARENT"),
            (4, "FOL_CLUTTER"),
            (5, "FOL_WEAPON"),
            (6, "FOL_PROJECTILE"),
            (7, "FOL_SPELL"),
            (8, "FOL_BIPED"),
            (9, "FOL_TREES"),
            (10, "FOL_PROPS"),
            (11, "FOL_WATER"),
            (12, "FOL_TRIGGER"),
            (13, "FOL_TERRAIN"),
            (14, "FOL_TRAP"),
            (15, "FOL_NONCOLLIDABLE"),
            (16, "FOL_CLOUD_TRAP"),
            (17, "FOL_GROUND"),
            (18, "FOL_PORTAL"),
            (19, "FOL_DEBRIS_SMALL"),
            (20, "FOL_DEBRIS_LARGE"),
            (21, "FOL_ACOUSTIC_SPACE"),
            (22, "FOL_ACTORZONE"),
            (23, "FOL_PROJECTILEZONE"),
            (24, "FOL_GASTRAP"),
            (25, "FOL_SHELLCASING"),
            (26, "FOL_TRANSPARENT_SMALL"),
            (27, "FOL_INVISIBLE_WALL"),
            (28, "FOL_TRANSPARENT_SMALL_ANIM"),
            (29, "FOL_DEADBIP"),
            (30, "FOL_CHARCONTROLLER"),
            (31, "FOL_AVOIDBOX"),
            (32, "FOL_COLLISIONBOX"),
            (33, "FOL_CAMERASPHERE"),
            (34, "FOL_DOORDETECTION"),
            (35, "FOL_CAMERAPICK"),
            (36, "FOL_ITEMPICK"),
            (37, "FOL_LINEOFSIGHT"),
            (38, "FOL_PATHPICK"),
            (39, "FOL_CUSTOMPICK1"),
            (40, "FOL_CUSTOMPICK2"),
            (41, "FOL_SPELLEXPLOSION"),
            (42, "FOL_DROPPINGPICK"),
            (43, "FOL_NULL"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbSkyrimLayer` (line 1627).
pub fn wb_skyrim_layer(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "SKYL_UNIDENTIFIED"),
            (1, "SKYL_STATIC"),
            (2, "SKYL_ANIMSTATIC"),
            (3, "SKYL_TRANSPARENT"),
            (4, "SKYL_CLUTTER"),
            (5, "SKYL_WEAPON"),
            (6, "SKYL_PROJECTILE"),
            (7, "SKYL_SPELL"),
            (8, "SKYL_BIPED"),
            (9, "SKYL_TREES"),
            (10, "SKYL_PROPS"),
            (11, "SKYL_WATER"),
            (12, "SKYL_TRIGGER"),
            (13, "SKYL_TERRAIN"),
            (14, "SKYL_TRAP"),
            (15, "SKYL_NONCOLLIDABLE"),
            (16, "SKYL_CLOUD_TRAP"),
            (17, "SKYL_GROUND"),
            (18, "SKYL_PORTAL"),
            (19, "SKYL_DEBRIS_SMALL"),
            (20, "SKYL_DEBRIS_LARGE"),
            (21, "SKYL_ACOUSTIC_SPACE"),
            (22, "SKYL_ACTORZONE"),
            (23, "SKYL_PROJECTILEZONE"),
            (24, "SKYL_GASTRAP"),
            (25, "SKYL_SHELLCASING"),
            (26, "SKYL_TRANSPARENT_SMALL"),
            (27, "SKYL_INVISIBLE_WALL"),
            (28, "SKYL_TRANSPARENT_SMALL_ANIM"),
            (29, "SKYL_WARD"),
            (30, "SKYL_CHARCONTROLLER"),
            (31, "SKYL_STAIRHELPER"),
            (32, "SKYL_DEADBIP"),
            (33, "SKYL_BIPED_NO_CC"),
            (34, "SKYL_AVOIDBOX"),
            (35, "SKYL_COLLISIONBOX"),
            (36, "SKYL_CAMERASHPERE"),
            (37, "SKYL_DOORDETECTION"),
            (38, "SKYL_CONEPROJECTILE"),
            (39, "SKYL_CAMERA"),
            (40, "SKYL_ITEMPICKER"),
            (41, "SKYL_LOS"),
            (42, "SKYL_PATHPICK"),
            (43, "SKYL_CUSTOMPICK1"),
            (44, "SKYL_CUSTOMPICK2"),
            (45, "SKYL_SPELLEXPLOSION"),
            (46, "SKYL_DROPPINGPICK"),
            (47, "SKYL_DEADACTORZONE"),
            (48, "SKYL_TRIGGER_FALLINGTRAP"),
            (49, "SKYL_NAVCUT"),
            (50, "SKYL_CRITTER"),
            (51, "SKYL_SPELLTRIGGER"),
            (52, "SKYL_LIVING_AND_DEAD_ACTORS"),
            (53, "SKYL_DETECTION"),
            (54, "SKYL_TRAP_TRIGGER"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbhkWorldObjCinfoProperty` (line 1688).
pub fn wbhk_world_obj_cinfo_property(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_integer("Data", DataType::U32, "", &[]),
            df_integer("Size", DataType::U32, "", &[]),
            df_integer("Capacity and Flags", DataType::U32, "2147483648", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbbhkCOFlags` (line 1697).
pub fn wbbhk_co_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[
            (0, "ACTIVE"),
            (2, "NOTIFY"),
            (3, "SET_LOCAL"),
            (4, "DBG_DISPLAY"),
            (5, "USE_VEL"),
            (6, "RESET"),
            (7, "SYNC_ON_UPDATE"),
            (8, "BLEND_POS"),
            (9, "ALWAYS_BLEND"),
            (10, "ANIM_TARGETED"),
            (11, "DISMEMBERED_LIMB"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbbhkCMSDTransform` (line 1714).
pub fn wbbhk_cmsd_transform(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![wb_vector4_name("Translation"), wbhk_quaternion_name("Rotation")],
        a_events,
    );
    result
}

/// Upstream `wbbhkCMSDBigTris` (line 1722).
pub fn wbbhk_cmsd_big_tris(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_integer("Triangle 1", DataType::U16, "", &[]),
            df_integer("Triangle 2", DataType::U16, "", &[]),
            df_integer("Triangle 3", DataType::U16, "", &[]),
            df_integer("Material", DataType::U32, "", &[]),
            df_integer("Welding Info", DataType::U16, "", &[]),
        ],
        a_events,
    );
    result
}

/// Upstream `wbbhkCMSDChunk` (line 1733).
pub fn wbbhk_cmsd_chunk(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            wb_vector4_name("Offset"),
            df_integer("Material Index", DataType::U32, "", &[]),
            df_integer("Reference", DataType::U16, "", &[]),
            df_integer("Transform Index", DataType::U16, "", &[]),
            df_array(
                "Vertices",
                df_integer("Vertices", DataType::U16, "", &[]),
                -4 as i32,
                "",
                &[],
            ),
            df_array(
                "Indices",
                df_integer("Indices", DataType::U16, "", &[]),
                -4 as i32,
                "",
                &[],
            ),
            df_array(
                "Strip Lengths",
                df_integer("Strip Length", DataType::U16, "", &[]),
                -4 as i32,
                "",
                &[],
            ),
            df_array(
                "Welding Info",
                df_integer("Welding Info", DataType::U16, "", &[]),
                -4 as i32,
                "",
                &[],
            ),
        ],
        a_events,
    );
    result
}

/// Upstream `wbMoppDataBuildType` (line 1747).
pub fn wb_mopp_data_build_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "BUILT_WITH_CHUNK_SUBDIVISION"),
            (1, "BUILT_WITHOUT_CHUNK_SUBDIVISION"),
            (2, "BUILD_NOT_SET"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbMipMapFormat` (line 1756).
pub fn wb_mip_map_format(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "MIP_FMT_NO"), (1, "MIP_FMT_YES"), (2, "MIP_FMT_DEFAULT")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbPixelFormat` (line 1765).
pub fn wb_pixel_format(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "PX_FMT_RGB"),
            (1, "PX_FMT_RGBA"),
            (2, "PX_FMT_PAL"),
            (3, "PX_FMT_PALA"),
            (4, "PX_FMT_DXT1"),
            (5, "PX_FMT_DXT5"),
            (6, "PX_FMT_DXT5_ALT"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbPixelLayout` (line 1778).
pub fn wb_pixel_layout(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "PIX_LAY_PALETTISED"),
            (1, "PIX_LAY_HIGH_COLOR_16"),
            (2, "PIX_LAY_TRUE_COLOR_32"),
            (3, "PIX_LAY_COMPRESSED"),
            (4, "PIX_LAY_BUMPMAP"),
            (5, "PIX_LAY_PALETTISED_4"),
            (6, "PIX_LAY_DEFAULT"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbTexClampMode` (line 1791).
pub fn wb_tex_clamp_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "CLAMP_S_CLAMP_T"),
            (1, "CLAMP_S_WRAP_T"),
            (2, "WRAP_S_CLAMP_T"),
            (3, "WRAP_S_WRAP_T"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbTexFilterMode` (line 1801).
pub fn wb_tex_filter_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "FILTER_NEAREST"),
            (1, "FILTER_BILERP"),
            (2, "FILTER_TRILERP"),
            (3, "FILTER_NEAREST_MIPNEAREST"),
            (4, "FILTER_NEAREST_MIPLERP"),
            (5, "FILTER_BILERP_MIPNEAREST"),
            (6, "FILTER_ANISOTROPIC"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbVertMode` (line 1814).
pub fn wb_vert_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "VERT_MODE_SRC_IGNORE"),
            (1, "VERT_MODE_SRC_EMISSIVE"),
            (2, "VERT_MODE_SRC_AMB_DIF"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbCycleType` (line 1823).
pub fn wb_cycle_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "CYCLE_LOOP"), (1, "CYCLE_REVERSE"), (2, "CYCLE_CLAMP")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBillboardMode` (line 1832).
pub fn wb_billboard_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U16,
        &[
            (0, "ALWAYS_FACE_CAMERA"),
            (1, "ROTATE_ABOUT_UP"),
            (2, "RIGID_FACE_CAMERA"),
            (3, "ALWAYS_FACE_CENTER"),
            (4, "RIGID_FACE_CENTER"),
            (5, "BSROTATE_ABOUT_UP"),
            (9, "ROTATE_ABOUT_UP2"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbFieldType` (line 1845).
pub fn wb_field_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "FIELD_WIND"), (1, "FIELD_POINT")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbZCompareMode` (line 1853).
pub fn wb_z_compare_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "ZCOMP_ALWAYS"),
            (1, "ZCOMP_LESS"),
            (2, "ZCOMP_EQUAL"),
            (3, "ZCOMP_LESS_EQUAL"),
            (4, "ZCOMP_GREATER"),
            (5, "ZCOMP_NOT_EQUAL"),
            (6, "ZCOMP_GREATER_EQUAL"),
            (7, "ZCOMP_NEVER"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbStencilCompareMode` (line 1867).
pub fn wb_stencil_compare_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "TEST_NEVER"),
            (1, "TEST_LESS"),
            (2, "TEST_EQUAL"),
            (3, "TEST_LESS_EQUAL"),
            (4, "TEST_GREATER"),
            (5, "TEST_NOT_EQUAL"),
            (6, "TEST_GREATER_EQUAL"),
            (7, "TEST_ALWAYS"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbStencilAction` (line 1881).
pub fn wb_stencil_action(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "ACTION_KEEP"),
            (1, "ACTION_ZERO"),
            (2, "ACTION_REPLACE"),
            (3, "ACTION_INCREMENT"),
            (4, "ACTION_DECREMENT"),
            (5, "ACTION_INVERT"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbStencilDrawMode` (line 1893).
pub fn wb_stencil_draw_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "DRAW_CCW_OR_BOTH"),
            (1, "DRAW_CCW"),
            (2, "DRAW_CW"),
            (3, "DRAW_BOTH"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbhkMotionType` (line 1903).
pub fn wbhk_motion_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "MO_SYS_INVALID"),
            (1, "MO_SYS_DYNAMIC"),
            (2, "MO_SYS_SPHERE_INERTIA"),
            (3, "MO_SYS_SPHERE_STABILIZED"),
            (4, "MO_SYS_BOX_INERTIA"),
            (5, "MO_SYS_BOX_STABILIZED"),
            (6, "MO_SYS_KEYFRAMED"),
            (7, "MO_SYS_FIXED"),
            (8, "MO_SYS_THIN_BOX"),
            (9, "MO_SYS_CHARACTER"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbhkDeactivatorType` (line 1926).
pub fn wbhk_deactivator_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "DEACTIVATOR_INVALID"),
            (1, "DEACTIVATOR_NEVER"),
            (2, "DEACTIVATOR_SPATIAL"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbhkSolverDeactivation` (line 1941).
pub fn wbhk_solver_deactivation(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "SOLVER_DEACTIVATION_INVALID"),
            (1, "SOLVER_DEACTIVATION_OFF"),
            (2, "SOLVER_DEACTIVATION_LOW"),
            (3, "SOLVER_DEACTIVATION_MEDIUM"),
            (4, "SOLVER_DEACTIVATION_HIGH"),
            (5, "SOLVER_DEACTIVATION_MAX"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbhkQualityType` (line 1953).
pub fn wbhk_quality_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "MO_QUAL_INVALID"),
            (1, "MO_QUAL_FIXED"),
            (2, "MO_QUAL_KEYFRAMED"),
            (3, "MO_QUAL_DEBRIS"),
            (4, "MO_QUAL_MOVING"),
            (5, "MO_QUAL_CRITICAL"),
            (6, "MO_QUAL_BULLET"),
            (7, "MO_QUAL_USER"),
            (8, "MO_QUAL_CHARACTER"),
            (9, "MO_QUAL_KEYFRAMED_REPORT"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbForceType` (line 1969).
pub fn wb_force_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "FORCE_PLANAR"), (1, "FORCE_SPHERICAL"), (2, "FORCE_UNKNOWN")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbTransformMember` (line 1978).
pub fn wb_transform_member(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "TT_TRANSLATE_U"),
            (1, "TT_TRANSLATE_V"),
            (2, "TT_ROTATE"),
            (3, "TT_SCALE_U"),
            (4, "TT_SCALE_V"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbDecayType` (line 1989).
pub fn wb_decay_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "DECAY_NONE"), (1, "DECAY_LINEAR"), (2, "DECAY_EXPONENTIAL")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbSymmetryType` (line 1998).
pub fn wb_symmetry_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "SPHERICAL_SYMMETRY"),
            (1, "CYLINDRICAL_SYMMETRY"),
            (2, "PLANAR_SYMMETRY"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbVelocityType` (line 2007).
pub fn wb_velocity_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "VELOCITY_USE_NORMALS"),
            (1, "VELOCITY_USE_RANDOM"),
            (2, "VELOCITY_USE_DIRECTION"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbEmitFrom` (line 2016).
pub fn wb_emit_from(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "EMIT_FROM_VERTICES"),
            (1, "EMIT_FROM_FACE_CENTER"),
            (2, "EMIT_FROM_EDGE_CENTER"),
            (3, "EMIT_FROM_FACE_SURFACE"),
            (4, "EMIT_FROM_EDGE_SURFACE"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbTextureType` (line 2027).
pub fn wb_texture_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "TEX_PROJECTED_LIGHT"),
            (1, "TEX_PROJECTED_SHADOW"),
            (2, "TEX_ENVIRONMENT_MAP"),
            (3, "TEX_FOG_MAP"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbCoordGenType` (line 2037).
pub fn wb_coord_gen_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "CG_WORLD_PARALLEL"),
            (1, "CG_WORLD_PERSPECTIVE"),
            (2, "CG_SPHERE_MAP"),
            (3, "CG_SPECULAR_CUBE_MAP"),
            (4, "CG_DIFFUSE_CUBE_MAP"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbMaterialColor` (line 2048).
pub fn wb_material_color(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U16,
        &[
            (0, "TC_AMBIENT"),
            (1, "TC_DIFFUSE"),
            (2, "TC_SPECULAR"),
            (3, "TC_SELF_ILLUM"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbLightColor` (line 2058).
pub fn wb_light_color(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U16,
        &[(0, "LC_DIFFUSE"), (1, "LC_AMBIENT")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbConsistencyType` (line 2066).
pub fn wb_consistency_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U16,
        &[(0, "CT_MUTABLE"), (16384, "CT_STATIC"), (32768, "CT_VOLATILE")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbPropagationMode` (line 2075).
pub fn wb_propagation_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "PROPAGATE_ON_SUCCESS"),
            (1, "PROPAGATE_ON_FAILURE"),
            (2, "PROPAGATE_ALWAYS"),
            (3, "PROPAGATE_NEVER"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbCollisionMode` (line 2085).
pub fn wb_collision_mode(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "CM_USE_OBB"),
            (1, "CM_USE_TRI"),
            (2, "CM_USE_ABV"),
            (3, "CM_NOTEST"),
            (4, "CM_USE_NIBOUND"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbPathFlags` (line 2096).
pub fn wb_path_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[
            (0, "NIPI_CVDataNeedsUpdate"),
            (1, "NIPI_CurveTypeOpen"),
            (2, "NIPI_AllowFlip"),
            (3, "NIPI_Bank"),
            (4, "NIPI_ConstantVelocity"),
            (5, "NIPI_Follow"),
            (6, "NIPI_Flip"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbInterpBlendFlags` (line 2109).
pub fn wb_interp_blend_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[(1, "MANAGER_CONTROLLED")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbVectorFlags` (line 2116).
pub fn wb_vector_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[
            (0, "UV_1"),
            (1, "UV_2"),
            (2, "UV_4"),
            (3, "UV_8"),
            (4, "UV_16"),
            (5, "UV_32"),
            (6, "Unk64"),
            (7, "Unk128"),
            (8, "Unk256"),
            (9, "Unk512"),
            (10, "Unk1024"),
            (11, "Unk2048"),
            (12, "Has_Tangents"),
            (13, "Unk8192"),
            (14, "Unk16384"),
            (15, "Unk32768"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBSVectorFlags` (line 2138).
pub fn wb_bs_vector_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[
            (0, "Has_UV"),
            (1, "Unk2"),
            (2, "Unk4"),
            (3, "Unk8"),
            (4, "Unk16"),
            (5, "Unk32"),
            (6, "Unk64"),
            (7, "Unk128"),
            (8, "Unk256"),
            (9, "Unk512"),
            (10, "Unk1024"),
            (11, "Unk2048"),
            (12, "Has_Tangents"),
            (13, "Unk8192"),
            (14, "Unk16384"),
            (15, "Unk32768"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbSkyrimShaderPropertyFlags1` (line 2160).
pub fn wb_skyrim_shader_property_flags1(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U32,
        &[
            (0, "Specular"),
            (1, "Skinned"),
            (2, "Temp_Refraction"),
            (3, "Vertex_Alpha"),
            (4, "Grayscale_To_PaletteColor"),
            (5, "Grayscale_To_PaletteAlpha"),
            (6, "Use_Falloff"),
            (7, "Environment_Mapping"),
            (8, "Recieve_Shadows"),
            (9, "Cast_Shadows"),
            (10, "Facegen"),
            (11, "Parallax"),
            (12, "Model_Space_Normals"),
            (13, "Non_Projective_Shadows"),
            (14, "Landscape"),
            (15, "Refraction"),
            (16, "Fire_Refraction"),
            (17, "Eye_Environment_Mapping"),
            (18, "Hair_Tint"),
            (19, "Screendoor_Alpha_Fade"),
            (20, "Localmap_Hide_Secret"),
            (21, "Skin_Tint"),
            (22, "Own_Emit"),
            (23, "Projected_UV"),
            (24, "Multiple_Textures"),
            (25, "Remappable_Textures"),
            (26, "Decal"),
            (27, "Dynamic_Decal"),
            (28, "Parallax_Occlusion"),
            (29, "External_Emittance"),
            (30, "Soft_Effect"),
            (31, "ZBuffer_Test"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbSkyrimShaderPropertyFlags2` (line 2198).
pub fn wb_skyrim_shader_property_flags2(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U32,
        &[
            (0, "ZBuffer_Write"),
            (1, "LOD_Landscape"),
            (2, "LOD_Objects"),
            (3, "No_Fade"),
            (4, "Double_Sided"),
            (5, "Vertex_Colors"),
            (6, "Glow_Map"),
            (7, "Assume_Shadowmask"),
            (8, "Character_Lighting"),
            (9, "Multi_Index_Snow"),
            (10, "Vertex_Lighting"),
            (11, "Uniform_Scale"),
            (12, "Fit_Slope"),
            (13, "Billboard"),
            (14, "No_LOD_Land_Blend"),
            (15, "EnvMap_Light_Fade"),
            (16, "Wireframe"),
            (17, "Weapon_Blood"),
            (18, "Hide_On_Local_Map"),
            (19, "Premult_Alpha"),
            (20, "Cloud_LOD"),
            (21, "Anisotropic_Lighting"),
            (22, "No_Transparency_Multisampling"),
            (23, "Unused01"),
            (24, "Multi_Layer_Parallax"),
            (25, "Soft_Lighting"),
            (26, "Rim_Lighting"),
            (27, "Back_Lighting"),
            (28, "Unused02"),
            (29, "Tree_Anim"),
            (30, "Effect_Lighting"),
            (31, "HD_LOD_Objects"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbFallout4ShaderPropertyFlags1` (line 2236).
pub fn wb_fallout4_shader_property_flags1(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U32,
        &[
            (0, "Specular"),
            (1, "Skinned"),
            (2, "Temp_Refraction"),
            (3, "Vertex_Alpha"),
            (4, "GrayscaleToPalette_Color"),
            (5, "GrayscaleToPalette_Alpha"),
            (6, "Use_Falloff"),
            (7, "Environment_Mapping"),
            (8, "RGB_Falloff"),
            (9, "Cast_Shadows"),
            (10, "Face"),
            (11, "UI_Mask_Rects"),
            (12, "Model_Space_Normals"),
            (13, "Non_Projective_Shadows"),
            (14, "Landscape"),
            (15, "Refraction"),
            (16, "Fire_Refraction"),
            (17, "Eye_Environment_Mapping"),
            (18, "Hair"),
            (19, "Screendoor_Alpha_Fade"),
            (20, "Localmap_Hide_Secret"),
            (21, "Skin_Tint"),
            (22, "Own_Emit"),
            (23, "Projected_UV"),
            (24, "Multiple_Textures"),
            (25, "Tessellate"),
            (26, "Decal"),
            (27, "Dynamic_Decal"),
            (28, "Character_Lighting"),
            (29, "External_Emittance"),
            (30, "Soft_Effect"),
            (31, "ZBuffer_Test"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbFallout4ShaderPropertyFlags2` (line 2274).
pub fn wb_fallout4_shader_property_flags2(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U32,
        &[
            (0, "ZBuffer_Write"),
            (1, "LOD_Landscape"),
            (2, "LOD_Objects"),
            (3, "No_Fade"),
            (4, "Double_Sided"),
            (5, "Vertex_Colors"),
            (6, "Glow_Map"),
            (7, "Transform_Changed"),
            (8, "Dismemberment_Meatcuff"),
            (9, "Tint"),
            (10, "Grass_Vertex_Lighting"),
            (11, "Grass_Uniform_Scale"),
            (12, "Grass_Fit_Slope"),
            (13, "Grass_Billboard"),
            (14, "No_LOD_Land_Blend"),
            (15, "Dismemberment"),
            (16, "Wireframe"),
            (17, "Weapon_Blood"),
            (18, "Hide_On_Local_Map"),
            (19, "Premult_Alpha"),
            (20, "VATS_Target"),
            (21, "Anisotropic_Lighting"),
            (22, "Skew_Specular_Alpha"),
            (23, "Menu_Screen"),
            (24, "Multi_Layer_Parallax"),
            (25, "Alpha_Test"),
            (26, "Gradient_Remap"),
            (27, "VATS_Target_Draw_All"),
            (28, "Pipboy_Screen"),
            (29, "Tree_Anim"),
            (30, "Effect_Lighting"),
            (31, "Refraction_Writes_Depth"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbNewShaderFlags` (line 2312).
pub fn wb_new_shader_flags(a_name: &str, a_data_type: DataType) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        a_data_type,
        &[
            (314919375, "FACE"),
            (348504749, "VERTEXCOLORS"),
            (442246519, "GRAYSCALE_TO_PALETTE_COLOR"),
            (731263983, "PBR"),
            (759557230, "TWO_SIDED"),
            (902349195, "REFRACTION_FALLOFF"),
            (1264105798, "HAIRTINT"),
            (1483897208, "SKIN_TINT"),
            (1563274220, "CAST_SHADOWS"),
            (1576614759, "DYNAMIC_DECAL"),
            (1740048692, "ZBUFFER_TEST"),
            (1957349758, "REFRACTION"),
            (2078326675, "WEAPON_BLOOD"),
            (2150459555, "EXTERNAL_EMITTANCE"),
            (2262553490, "EMIT_ENABLED"),
            (2333069810, "VERTEX_ALPHA"),
            (2399422528, "GLOWMAP"),
            (2548465567, "MODELSPACENORMALS"),
            (2893749418, "ENVMAP"),
            (2896726515, "LOD_OBJECTS"),
            (2901038324, "GRAYSCALE_TO_PALETTE_ALPHA"),
            (2994043788, "NOFADE"),
            (3030867718, "INVERTED_FADE_PATTERN"),
            (3166356979, "ZBUFFER_WRITE"),
            (3196772338, "TRANSFORM_CHANGED"),
            (3448946507, "RGB_FALLOFF"),
            (3473438218, "EFFECT_LIGHTING"),
            (3503164976, "SOFT_EFFECT"),
            (3707406987, "NO_EXPOSURE"),
            (3744563888, "SKINNED"),
            (3849131744, "DECAL"),
            (3980660124, "FALLOFF"),
        ],
        "",
        &[],
    );
    result
}

/// Upstream `wbVertexFlags` (line 2350).
pub fn wb_vertex_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[
            (0, "VF_Unknown_0"),
            (1, "VF_Unknown_1"),
            (2, "VF_Unknown_2"),
            (3, "VF_Unknown_3"),
            (4, "VF_VERTEX"),
            (5, "VF_UV"),
            (6, "VF_UV_2"),
            (7, "VF_NORMAL"),
            (8, "VF_TANGENT"),
            (9, "VF_COLORS"),
            (10, "VF_SKINNED"),
            (11, "VF_LANDDATA"),
            (12, "VF_EYEDATA"),
            (13, "VF_INSTANCE"),
            (14, "VF_FULLPREC"),
            (15, "VF_Unknown_15"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbBSCPCullingType` (line 2372).
pub fn wb_bscp_culling_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "BSCP_CULL_NORMAL"),
            (1, "BSCP_CULL_ALLPASS"),
            (2, "BSCP_CULL_ALLFAIL"),
            (3, "BSCP_CULL_IGNOREMULTIBOUNDS"),
            (4, "BSCP_CULL_FORCEMULTIBOUNDSNOUPDATE"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbNiSwitchFlags` (line 2383).
pub fn wb_ni_switch_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[(0, "UpdateOnlyActiveChild"), (1, "UpdateControllers")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbMotorType` (line 2391).
pub fn wb_motor_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U8,
        &[
            (0, "MOTOR_NONE"),
            (1, "MOTOR_POSITION"),
            (2, "MOTOR_VELOCITY"),
            (3, "MOTOR_SPRING"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbChannelType` (line 2401).
pub fn wb_channel_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[
            (0, "CHNL_RED"),
            (1, "CHNL_GREEN"),
            (2, "CHNL_BLUE"),
            (3, "CHNL_ALPHA"),
            (4, "CHNL_COMPRESSED"),
            (16, "CHNL_INDEX"),
            (19, "CHNL_EMPTY"),
        ],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbChannelConvention` (line 2414).
pub fn wb_channel_convention(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U32,
        &[(0, "CC_FIXED"), (3, "CC_INDEX"), (4, "CC_COMPRESSED"), (5, "CC_EMPTY")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbFurnitureEntryPoints` (line 2424).
pub fn wb_furniture_entry_points(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[(0, "Front"), (1, "Behind"), (2, "Right"), (3, "Left"), (4, "Up")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbAnimationType` (line 2435).
pub fn wb_animation_type(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_enum(
        a_name,
        DataType::U16,
        &[(1, "Sit"), (2, "Sleep"), (4, "Lean")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbLookAtFlags` (line 2444).
pub fn wb_look_at_flags(a_name: &str, a_default_value: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_flags(
        a_name,
        DataType::U16,
        &[(0, "LOOK_FLIP"), (1, "LOOK_Y_AXIS"), (2, "LOOK_Z_AXIS")],
        a_default_value,
        a_events,
    );
    result
}

/// Upstream `wbAdditionalDataInfo` (line 2453).
pub fn wb_additional_data_info(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_integer("Data Type", DataType::S32, "", &[]),
            df_integer("Num Channel Bytes Per Element", DataType::S32, "", &[]),
            df_integer("Num Channel Bytes", DataType::S32, "", &[]),
            df_integer("Num Total Bytes Per Element", DataType::S32, "", &[]),
            df_integer("Block Index", DataType::S32, "", &[]),
            df_integer("Channel Offset", DataType::S32, "", &[]),
            df_integer("Unknown Byte 1", DataType::U8, "2", &[]),
        ],
        &[],
    );
    result
}

/// Upstream `wbAdditionalDataBlock` (line 2469).
pub fn wb_additional_data_block(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_bool("Has Data", DataType::U8, "", &[]),
            df_struct(
                "Data",
                vec![
                    df_integer("Block Size", DataType::S32, "", &[]),
                    df_array(
                        "Block Offsets",
                        df_integer("Block Offsets", DataType::S32, "", &[]),
                        -4 as i32,
                        "",
                        &[],
                    ),
                    df_integer("Num Data", DataType::S32, "", &[]),
                    df_array(
                        "Data Sizes",
                        df_integer("Data Sizes", DataType::S32, "", &[]),
                        0 as i32,
                        "Num Data",
                        &[],
                    ),
                    df_array(
                        "Data",
                        df_bytes(
                            "Data",
                            0 as i32,
                            &[Event::GetCount(additional_data_block_get_count_data)],
                        ),
                        0 as i32,
                        "Num Data",
                        &[],
                    ),
                ],
                &[Event::GetEnabled(additional_data_block_en_data)],
            ),
        ],
        a_events,
    );
    result
}

/// Upstream `wbBSPackedAdditionalDataBlock` (line 2485).
pub fn wb_bs_packed_additional_data_block(a_name: &str, a_events: &[Event]) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_bool("Has Data", DataType::U8, "", &[]),
            df_struct(
                "Data",
                vec![
                    df_integer("Num Total Bytes", DataType::U32, "", &[]),
                    df_array(
                        "Block Offsets",
                        df_integer("Block Offsets", DataType::S32, "", &[]),
                        -4 as i32,
                        "",
                        &[],
                    ),
                    df_array(
                        "Atom Sizes",
                        df_integer("Atom Sizes", DataType::S32, "", &[]),
                        -4 as i32,
                        "",
                        &[],
                    ),
                    df_array(
                        "Data",
                        df_integer("Data", DataType::U8, "", &[]),
                        0 as i32,
                        "Num Total Bytes",
                        &[],
                    ),
                    df_integer("Unknown Int", DataType::S32, "", &[]),
                    df_integer("Num Total Bytes Per Element", DataType::U32, "", &[]),
                ],
                &[Event::GetEnabled(bs_packed_additional_data_block_en_data)],
            ),
        ],
        a_events,
    );
    result
}

/// Upstream `wbBoundingVolume` (line 2511).
pub fn wb_bounding_volume(a_name: &str) -> Def {
    let mut result: Def;
    result = df_struct(
        a_name,
        vec![
            df_enum(
                "Collision Type",
                DataType::S32,
                &[
                    (-1, "BASE_BV"),
                    (0, "SPHERE_BV"),
                    (1, "BOX_BV"),
                    (2, "CAPSULE_BV"),
                    (4, "UNION_BV"),
                    (5, "HALFSPACE_BV"),
                ],
                "BOX_BV",
                &[],
            ),
            df_struct(
                "Sphere",
                vec![
                    wb_vector3_name("Center"),
                    df_float("Radius", DataType::Float32, "", &[]),
                ],
                &[Event::GetEnabled(bounding_volume_en_type0)],
            ),
            df_struct(
                "Box",
                vec![
                    wb_vector3_name("Center"),
                    df_array("Axis", wb_vector3_name("Axis"), 3 as i32, "", &[]),
                    wb_vector3_name("Extent"),
                ],
                &[Event::GetEnabled(bounding_volume_en_type1)],
            ),
            df_struct(
                "Capsule",
                vec![
                    wb_vector3_name("Center"),
                    wb_vector3_name("Origin"),
                    df_float("Extent", DataType::Float32, "", &[]),
                    df_float("Radius", DataType::Float32, "", &[]),
                ],
                &[Event::GetEnabled(bounding_volume_en_type2)],
            ),
            df_integer(
                "Union BV",
                DataType::U32,
                "",
                &[Event::GetEnabled(bounding_volume_en_type4)],
            ),
            df_struct(
                "Half Space",
                vec![wb_ni_plane("Plane"), wb_vector3_name("Center")],
                &[Event::GetEnabled(bounding_volume_en_type5)],
            ),
        ],
        &[],
    );
    result
}

/// Upstream `AdditionalDataBlock_EnData` (line 2466).
pub fn additional_data_block_en_data(t: &mut Tree, e: El) -> R<bool> {
    let mut result = false;
    result = (t.native_values(e, &"..\\Has Data")? != 0i64);
    Ok(result)
}

/// Upstream `AdditionalDataBlock_GetCountData` (line 2467).
pub fn additional_data_block_get_count_data(t: &mut Tree, e: El, a_count: &mut i32) -> R<()> {
    *a_count = ((t.native_values(e, &"..\\..\\Block Size")?).to_i64()?) as i32;
    Ok(())
}

/// Upstream `BSPackedAdditionalDataBlock_EnData` (line 2483).
pub fn bs_packed_additional_data_block_en_data(t: &mut Tree, e: El) -> R<bool> {
    let mut result = false;
    result = (t.native_values(e, &"..\\Has Data")? != 0i64);
    Ok(result)
}

/// Upstream `BoundingVolume_EnType0` (line 2500).
pub fn bounding_volume_en_type0(t: &mut Tree, e: El) -> R<bool> {
    let mut result = false;
    result = (t.native_values(e, &"..\\Collision Type")? == 0i64);
    Ok(result)
}

/// Upstream `BoundingVolume_EnType1` (line 2501).
pub fn bounding_volume_en_type1(t: &mut Tree, e: El) -> R<bool> {
    let mut result = false;
    result = (t.native_values(e, &"..\\Collision Type")? == 1i64);
    Ok(result)
}

/// Upstream `BoundingVolume_EnType2` (line 2502).
pub fn bounding_volume_en_type2(t: &mut Tree, e: El) -> R<bool> {
    let mut result = false;
    result = (t.native_values(e, &"..\\Collision Type")? == 2i64);
    Ok(result)
}

/// Upstream `BoundingVolume_EnType4` (line 2503).
pub fn bounding_volume_en_type4(t: &mut Tree, e: El) -> R<bool> {
    let mut result = false;
    result = false;
    if (t.native_values(e, &"..\\Collision Type")? == 4i64) {
        return Err(t.exception(e, &"BoundingVolume UnionBV type is not supported"));
    }
    Ok(result)
}

/// Upstream `BoundingVolume_EnType5` (line 2509).
pub fn bounding_volume_en_type5(t: &mut Tree, e: El) -> R<bool> {
    let mut result = false;
    result = (t.native_values(e, &"..\\Collision Type")? == 5i64);
    Ok(result)
}
