// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDataFormatNif.pas
// Generated by `cargo xtask port-defs emit-df`. Do not edit.

//! The callbacks that are not ported yet. Each fails when called.

#![allow(unused_variables, unused_imports, dead_code)]

use super::*;
