// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsCommon.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `wbLGDIFiltersToStr`, line 212 of `wbDefinitionsCommon.pas`.
pub fn wb_lgdi_filters_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbLGDIFiltersToStr from wbDefinitionsCommon.pas line 212")
}

/// Upstream `wbLGDIRankSlotArrayShouldInclude`, line 170 of `wbDefinitionsCommon.pas`.
pub fn wb_lgdi_rank_slot_array_should_include(_a_base_ptr: DataPtr, _a_array: ElementArg) -> bool {
    todo!("port wbLGDIRankSlotArrayShouldInclude from wbDefinitionsCommon.pas line 170")
}

/// Upstream `anonymous routine in wb_lgdi_slot_def`, line 7802 of `wbDefinitionsCommon.pas`.
pub fn wb_lgdi_slot_def_anonymous_7802(_a_base_ptr: DataPtr, _a_element: ElementArg) -> bool {
    todo!("port anonymous routine in wb_lgdi_slot_def from wbDefinitionsCommon.pas line 7802")
}

/// Upstream `anonymous routine in wb_model_info`, line 8545 of `wbDefinitionsCommon.pas`.
pub fn wb_model_info_anonymous_8545(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port anonymous routine in wb_model_info from wbDefinitionsCommon.pas line 8545")
}

/// Upstream `anonymous routine in wb_model_info`, line 8585 of `wbDefinitionsCommon.pas`.
pub fn wb_model_info_anonymous_8585(
    _a_value: &mut String,
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
    _a_type: CallbackType,
) {
    todo!("port anonymous routine in wb_model_info from wbDefinitionsCommon.pas line 8585")
}

/// Upstream `wbRPLDAfterLoad`, line 47 of `wbDefinitionsCommon.pas`.
pub fn wb_rpld_after_load(_a_element: &ElementRef) {
    todo!("port wbRPLDAfterLoad from wbDefinitionsCommon.pas line 47")
}

/// Upstream `wbStrToLGDIFilter`, line 188 of `wbDefinitionsCommon.pas`.
pub fn wb_str_to_lgdi_filter(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbStrToLGDIFilter from wbDefinitionsCommon.pas line 188")
}
