// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsCommon.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use std::sync::Arc;

use xedit_core::interface::*;

/// Upstream `wbACBSLevelMultAfterLoad`, line 39 of `wbDefinitionsCommon.pas`.
pub fn wb_acbs_level_mult_after_load(_a_element: &ElementRef) {
    todo!("port wbACBSLevelMultAfterLoad from wbDefinitionsCommon.pas line 39")
}

/// Upstream `wbACBSLevelMultAfterSet`, line 54 of `wbDefinitionsCommon.pas`.
pub fn wb_acbs_level_mult_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbACBSLevelMultAfterSet from wbDefinitionsCommon.pas line 54")
}

/// Upstream `wbAVIFSkillAfterLoad`, line 40 of `wbDefinitionsCommon.pas`.
pub fn wb_avif_skill_after_load(_a_element: &ElementRef) {
    todo!("port wbAVIFSkillAfterLoad from wbDefinitionsCommon.pas line 40")
}

/// Upstream `wbBOOKDataFlagsAfterSet`, line 55 of `wbDefinitionsCommon.pas`.
pub fn wb_book_data_flags_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbBOOKDataFlagsAfterSet from wbDefinitionsCommon.pas line 55")
}

/// Upstream `wbConditionRunOnAfterSet`, line 57 of `wbDefinitionsCommon.pas`.
pub fn wb_condition_run_on_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbConditionRunOnAfterSet from wbDefinitionsCommon.pas line 57")
}

/// Upstream `wbConditionSummaryLinksTo`, line 149 of `wbDefinitionsCommon.pas`.
pub fn wb_condition_summary_links_to(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbConditionSummaryLinksTo from wbDefinitionsCommon.pas line 149")
}

/// Upstream `wbConditionTypeAfterSet`, line 56 of `wbDefinitionsCommon.pas`.
pub fn wb_condition_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbConditionTypeAfterSet from wbDefinitionsCommon.pas line 56")
}

/// Upstream `wbCrowdPropertyToStr`, line 238 of `wbDefinitionsCommon.pas`.
pub fn wb_crowd_property_to_str(
    _a_value: &mut String,
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
    _a_type: CallbackType,
) {
    todo!("port wbCrowdPropertyToStr from wbDefinitionsCommon.pas line 238")
}

/// Upstream `wbDialogueTextAfterLoad`, line 41 of `wbDefinitionsCommon.pas`.
pub fn wb_dialogue_text_after_load(_a_element: &ElementRef) {
    todo!("port wbDialogueTextAfterLoad from wbDefinitionsCommon.pas line 41")
}

/// Upstream `wbDialogueTextAfterSet`, line 58 of `wbDefinitionsCommon.pas`.
pub fn wb_dialogue_text_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbDialogueTextAfterSet from wbDefinitionsCommon.pas line 58")
}

/// Upstream `wbDOBJObjectsAfterLoad`, line 42 of `wbDefinitionsCommon.pas`.
pub fn wb_dobj_objects_after_load(_a_element: &ElementRef) {
    todo!("port wbDOBJObjectsAfterLoad from wbDefinitionsCommon.pas line 42")
}

/// Upstream `wbFlagNavmeshIgnoreErosionDontSHow`, line 87 of `wbDefinitionsCommon.pas`.
pub fn wb_flag_navmesh_ignore_erosion_dont_s_how(_a_element: ElementArg) -> bool {
    todo!("port wbFlagNavmeshIgnoreErosionDontSHow from wbDefinitionsCommon.pas line 87")
}

/// Upstream `wbFlagNavmeshOnlyCutDontSHow`, line 86 of `wbDefinitionsCommon.pas`.
pub fn wb_flag_navmesh_only_cut_dont_s_how(_a_element: ElementArg) -> bool {
    todo!("port wbFlagNavmeshOnlyCutDontSHow from wbDefinitionsCommon.pas line 86")
}

/// Upstream `wbIdleMarkerPNAMAfterSet`, line 59 of `wbDefinitionsCommon.pas`.
pub fn wb_idle_marker_pnam_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbIdleMarkerPNAMAfterSet from wbDefinitionsCommon.pas line 59")
}

/// Upstream `wbIdleMarkerQNAMAfterSet`, line 60 of `wbDefinitionsCommon.pas`.
pub fn wb_idle_marker_qnam_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbIdleMarkerQNAMAfterSet from wbDefinitionsCommon.pas line 60")
}

/// Upstream `wbINFOAliasToStr`, line 211 of `wbDefinitionsCommon.pas`.
pub fn wb_info_alias_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbINFOAliasToStr from wbDefinitionsCommon.pas line 211")
}

/// Upstream `wbIntPrefixedStrToInt`, line 184 of `wbDefinitionsCommon.pas`.
pub fn wb_int_prefixed_str_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbIntPrefixedStrToInt from wbDefinitionsCommon.pas line 184")
}

/// Upstream `wbLGDIFiltersToStr`, line 212 of `wbDefinitionsCommon.pas`.
pub fn wb_lgdi_filters_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbLGDIFiltersToStr from wbDefinitionsCommon.pas line 212")
}

/// Upstream `wbLGDIRankSlotArrayShouldInclude`, line 170 of `wbDefinitionsCommon.pas`.
pub fn wb_lgdi_rank_slot_array_should_include(_a_base_ptr: DataPtr, _a_array: ElementArg) -> bool {
    todo!("port wbLGDIRankSlotArrayShouldInclude from wbDefinitionsCommon.pas line 170")
}

/// Upstream `anonymous routine in wb_lgdi_slot_def`, line 7802 of `wbDefinitionsCommon.pas`.
pub fn wb_lgdi_slot_def_anonymous_7802(_a_base_ptr: DataPtr, _a_element: ElementArg) -> bool {
    todo!("port anonymous routine in wb_lgdi_slot_def from wbDefinitionsCommon.pas line 7802")
}

/// Upstream `wbMESGAfterLoad`, line 43 of `wbDefinitionsCommon.pas`.
pub fn wb_mesg_after_load(_a_element: &ElementRef) {
    todo!("port wbMESGAfterLoad from wbDefinitionsCommon.pas line 43")
}

/// Upstream `wbMESGDNAMAfterSet`, line 61 of `wbDefinitionsCommon.pas`.
pub fn wb_mesgdnam_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMESGDNAMAfterSet from wbDefinitionsCommon.pas line 61")
}

/// Upstream `wbNPCFaceDialLinksTo`, line 154 of `wbDefinitionsCommon.pas`.
pub fn wb_npc_face_dial_links_to(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbNPCFaceDialLinksTo from wbDefinitionsCommon.pas line 154")
}

/// Upstream `wbNPCFaceDialToStr`, line 213 of `wbDefinitionsCommon.pas`.
pub fn wb_npc_face_dial_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbNPCFaceDialToStr from wbDefinitionsCommon.pas line 213")
}

/// Upstream `wbNPCFaceMorphLinksTo`, line 155 of `wbDefinitionsCommon.pas`.
pub fn wb_npc_face_morph_links_to(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbNPCFaceMorphLinksTo from wbDefinitionsCommon.pas line 155")
}

/// Upstream `wbNPCFaceMorphToStr`, line 214 of `wbDefinitionsCommon.pas`.
pub fn wb_npc_face_morph_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbNPCFaceMorphToStr from wbDefinitionsCommon.pas line 214")
}

/// Upstream `wbPACKDateAfterLoad`, line 44 of `wbDefinitionsCommon.pas`.
pub fn wb_pack_date_after_load(_a_element: &ElementRef) {
    todo!("port wbPACKDateAfterLoad from wbDefinitionsCommon.pas line 44")
}

/// Upstream `wbPACKDateAfterSet`, line 62 of `wbDefinitionsCommon.pas`.
pub fn wb_pack_date_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPACKDateAfterSet from wbDefinitionsCommon.pas line 62")
}

/// Upstream `wbPERKPRKETypeAfterSet`, line 63 of `wbDefinitionsCommon.pas`.
pub fn wb_perkprke_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPERKPRKETypeAfterSet from wbDefinitionsCommon.pas line 63")
}

/// Upstream `wbPERKPRUCAfterSet`, line 64 of `wbDefinitionsCommon.pas`.
pub fn wb_perkpruc_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPERKPRUCAfterSet from wbDefinitionsCommon.pas line 64")
}

/// Upstream `wbPNDTAfterLoad`, line 45 of `wbDefinitionsCommon.pas`.
pub fn wb_pndt_after_load(_a_element: &ElementRef) {
    todo!("port wbPNDTAfterLoad from wbDefinitionsCommon.pas line 45")
}

/// Upstream `wbRecipeCategoryDataAfterLoad`, line 46 of `wbDefinitionsCommon.pas`.
pub fn wb_recipe_category_data_after_load(_a_element: &ElementRef) {
    todo!("port wbRecipeCategoryDataAfterLoad from wbDefinitionsCommon.pas line 46")
}

/// Upstream `wbRPLDAfterLoad`, line 47 of `wbDefinitionsCommon.pas`.
pub fn wb_rpld_after_load(_a_element: &ElementRef) {
    todo!("port wbRPLDAfterLoad from wbDefinitionsCommon.pas line 47")
}

/// Upstream `wbSceneActionTypeAfterSet`, line 65 of `wbDefinitionsCommon.pas`.
pub fn wb_scene_action_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbSceneActionTypeAfterSet from wbDefinitionsCommon.pas line 65")
}

/// Upstream `wbScriptFragmentsQuestScriptNameAfterSet`, line 66 of `wbDefinitionsCommon.pas`.
pub fn wb_script_fragments_quest_script_name_after_set(
    _a_element: &ElementRef,
    _a_old_value: &Variant,
    _a_new_value: &Variant,
) {
    todo!("port wbScriptFragmentsQuestScriptNameAfterSet from wbDefinitionsCommon.pas line 66")
}

/// Upstream `wbScriptPropertyTypeAfterSet`, line 67 of `wbDefinitionsCommon.pas`.
pub fn wb_script_property_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbScriptPropertyTypeAfterSet from wbDefinitionsCommon.pas line 67")
}

/// Upstream `wbScrollCastAfterLoad`, line 48 of `wbDefinitionsCommon.pas`.
pub fn wb_scroll_cast_after_load(_a_element: &ElementRef) {
    todo!("port wbScrollCastAfterLoad from wbDefinitionsCommon.pas line 48")
}

/// Upstream `wbScrollTypeAfterLoad`, line 49 of `wbDefinitionsCommon.pas`.
pub fn wb_scroll_type_after_load(_a_element: &ElementRef) {
    todo!("port wbScrollTypeAfterLoad from wbDefinitionsCommon.pas line 49")
}

/// Upstream `wbSOUNAfterLoad`, line 50 of `wbDefinitionsCommon.pas`.
pub fn wb_soun_after_load(_a_element: &ElementRef) {
    todo!("port wbSOUNAfterLoad from wbDefinitionsCommon.pas line 50")
}

/// Upstream `wbStrToLGDIFilter`, line 188 of `wbDefinitionsCommon.pas`.
pub fn wb_str_to_lgdi_filter(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbStrToLGDIFilter from wbDefinitionsCommon.pas line 188")
}

/// Upstream `wbUpdateSameParentUnions`, line 68 of `wbDefinitionsCommon.pas`.
pub fn wb_update_same_parent_unions(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbUpdateSameParentUnions from wbDefinitionsCommon.pas line 68")
}

/// Upstream `wbWorldAfterLoad`, line 51 of `wbDefinitionsCommon.pas`.
pub fn wb_world_after_load(_a_element: &ElementRef) {
    todo!("port wbWorldAfterLoad from wbDefinitionsCommon.pas line 51")
}

/// Upstream `wbWorldAfterSet`, line 69 of `wbDefinitionsCommon.pas`.
pub fn wb_world_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbWorldAfterSet from wbDefinitionsCommon.pas line 69")
}

/// Upstream `wbWwiseKeywordMappingSoundDecider`, line 282 of `wbDefinitionsCommon.pas`.
pub fn wb_wwise_keyword_mapping_sound_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbWwiseKeywordMappingSoundDecider from wbDefinitionsCommon.pas line 282")
}

/// Upstream `wbWwiseKeywordMappingTemplateAfterSet`, line 70 of `wbDefinitionsCommon.pas`.
pub fn wb_wwise_keyword_mapping_template_after_set(
    _a_element: &ElementRef,
    _a_old_value: &Variant,
    _a_new_value: &Variant,
) {
    todo!("port wbWwiseKeywordMappingTemplateAfterSet from wbDefinitionsCommon.pas line 70")
}
