// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsFNV.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `wbCELLAfterLoad`, line 2595 of `wbDefinitionsFNV.pas`.
pub fn wb_cell_after_load(_a_element: &ElementRef) {
    todo!("port wbCELLAfterLoad from wbDefinitionsFNV.pas line 2595")
}

/// Upstream `wbConditionAfterLoad`, line 1048 of `wbDefinitionsFNV.pas`.
pub fn wb_condition_after_load(_a_element: &ElementRef) {
    todo!("port wbConditionAfterLoad from wbDefinitionsFNV.pas line 1048")
}

/// Upstream `wbEFITAfterLoad`, line 2822 of `wbDefinitionsFNV.pas`.
pub fn wb_efit_after_load(_a_element: &ElementRef) {
    todo!("port wbEFITAfterLoad from wbDefinitionsFNV.pas line 2822")
}

/// Upstream `wbEFSHAfterLoad`, line 2763 of `wbDefinitionsFNV.pas`.
pub fn wb_efsh_after_load(_a_element: &ElementRef) {
    todo!("port wbEFSHAfterLoad from wbDefinitionsFNV.pas line 2763")
}

/// Upstream `wbEmbeddedScriptAfterLoad`, line 2626 of `wbDefinitionsFNV.pas`.
pub fn wb_embedded_script_after_load(_a_element: &ElementRef) {
    todo!("port wbEmbeddedScriptAfterLoad from wbDefinitionsFNV.pas line 2626")
}

/// Upstream `wbFACTAfterLoad`, line 2795 of `wbDefinitionsFNV.pas`.
pub fn wb_fact_after_load(_a_element: &ElementRef) {
    todo!("port wbFACTAfterLoad from wbDefinitionsFNV.pas line 2795")
}

/// Upstream `wbFLSTEDIDAfterSet`, line 1261 of `wbDefinitionsFNV.pas`.
pub fn wb_flstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbFLSTEDIDAfterSet from wbDefinitionsFNV.pas line 1261")
}

/// Upstream `wbGMSTEDIDAfterSet`, line 1241 of `wbDefinitionsFNV.pas`.
pub fn wb_gmstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGMSTEDIDAfterSet from wbDefinitionsFNV.pas line 1241")
}

/// Upstream `wbHeadPartsAfterSet`, line 1228 of `wbDefinitionsFNV.pas`.
pub fn wb_head_parts_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbHeadPartsAfterSet from wbDefinitionsFNV.pas line 1228")
}

/// Upstream `wbINFOAfterLoad`, line 2574 of `wbDefinitionsFNV.pas`.
pub fn wb_info_after_load(_a_element: &ElementRef) {
    todo!("port wbINFOAfterLoad from wbDefinitionsFNV.pas line 2574")
}

/// Upstream `wbMGEFAfterLoad`, line 2428 of `wbDefinitionsFNV.pas`.
pub fn wb_mgef_after_load(_a_element: &ElementRef) {
    todo!("port wbMGEFAfterLoad from wbDefinitionsFNV.pas line 2428")
}

/// Upstream `wbMGEFArchtypeAfterSet`, line 1407 of `wbDefinitionsFNV.pas`.
pub fn wb_mgef_archtype_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFArchtypeAfterSet from wbDefinitionsFNV.pas line 1407")
}

/// Upstream `wbMGEFFAssocItemAfterSet`, line 1391 of `wbDefinitionsFNV.pas`.
pub fn wb_mgeff_assoc_item_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFFAssocItemAfterSet from wbDefinitionsFNV.pas line 1391")
}

/// Upstream `wbNPCAfterLoad`, line 2535 of `wbDefinitionsFNV.pas`.
pub fn wb_npc_after_load(_a_element: &ElementRef) {
    todo!("port wbNPCAfterLoad from wbDefinitionsFNV.pas line 2535")
}

/// Upstream `wbPACKAfterLoad`, line 2472 of `wbDefinitionsFNV.pas`.
pub fn wb_pack_after_load(_a_element: &ElementRef) {
    todo!("port wbPACKAfterLoad from wbDefinitionsFNV.pas line 2472")
}

/// Upstream `wbPerkDATAFunctionAfterSet`, line 2064 of `wbDefinitionsFNV.pas`.
pub fn wb_perk_data_function_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPerkDATAFunctionAfterSet from wbDefinitionsFNV.pas line 2064")
}

/// Upstream `wbPERKEntryPointAfterSet`, line 1714 of `wbDefinitionsFNV.pas`.
pub fn wb_perk_entry_point_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPERKEntryPointAfterSet from wbDefinitionsFNV.pas line 1714")
}

/// Upstream `wbPerkEPFTAfterSet`, line 2195 of `wbDefinitionsFNV.pas`.
pub fn wb_perk_epft_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPerkEPFTAfterSet from wbDefinitionsFNV.pas line 2195")
}

/// Upstream `wbREFRAfterLoad`, line 2552 of `wbDefinitionsFNV.pas`.
pub fn wb_refr_after_load(_a_element: &ElementRef) {
    todo!("port wbREFRAfterLoad from wbDefinitionsFNV.pas line 2552")
}

/// Upstream `wbWATRAfterLoad`, line 2705 of `wbDefinitionsFNV.pas`.
pub fn wb_watr_after_load(_a_element: &ElementRef) {
    todo!("port wbWATRAfterLoad from wbDefinitionsFNV.pas line 2705")
}

/// Upstream `wbWEAPAfterLoad`, line 2740 of `wbDefinitionsFNV.pas`.
pub fn wb_weap_after_load(_a_element: &ElementRef) {
    todo!("port wbWEAPAfterLoad from wbDefinitionsFNV.pas line 2740")
}
