// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsFNVSaves.pas

//! The callbacks of `wbDefinitionsFNVSaves.pas` that are ported by hand.
//! The ones that are not ported yet are stubs in `fnvsaves_stubs.rs`.

#[allow(unused_imports)]
pub use super::fnvsaves_stubs::*;

use xedit_core::interface::globals::{
    set_extract_info, set_file_chapters, set_file_header, set_file_magic, set_file_plugins,
};
use xedit_core::interface::*;

use crate::fnv::define_fnv;
use crate::fnvsaves::{WB_ACTOR_VALUE_LABELS, WB_CO_SAVE_CHAPTERS, WB_CO_SAVE_HEADER, define_fnv_saves_s};

/// Upstream `ExtractInfoSave`: the chapters of a save that are initialized
/// while it loads.
const EXTRACT_INFO_SAVE: [u8; 2] = [3, 4];

/// Port of `DefineFNVSavesA`: the labels of the actor value arrays.
pub fn define_fnv_saves_a() {
    let labels = actor_value_enum().map_or_else(Vec::new, |enum_def| {
        (0..enum_def.get_name_count())
            .map(|index| enum_def.get_name_of(i64::from(index)))
            .collect()
    });
    WB_ACTOR_VALUE_LABELS.set(labels);
}

/// Port of `DefineFNVSaves`.
pub fn define_fnv_saves() {
    set_file_magic("FO3SAVEGAME");
    set_extract_info(&EXTRACT_INFO_SAVE);
    set_file_plugins("Plugins");
    define_fnv();
    define_fnv_saves_a();
    define_fnv_saves_s();
}

/// Port of `SwitchToFNVCoSave`.
pub fn switch_to_fnv_co_save() {
    set_file_magic("NVSE");
    set_extract_info(&[]);
    set_file_plugins("Absolute:44");
    set_file_chapters(WB_CO_SAVE_CHAPTERS.get());
    set_file_header(WB_CO_SAVE_HEADER.get());
}

// ----- generated by gen_fnv.py -----

use std::sync::atomic::{AtomicUsize, Ordering};

use super::fo4saves::{self, CHANGED_FORM_OFFSET, consumed, native, root_value, save_child, save_value};
use super::save_interface::wb_find_save_element;
use crate::fnvsaves::{TEMP_CHANGED_FORM_FLAGS, WB_CHANGE_TYPES};

/// Upstream `MaxInt`: what `GetRelativeDeciderInteger` returns when it
/// finds nothing.
const MAX_INT: i64 = i32::MAX as i64;

/// The bytes at `offset` before the address `address` in the block of the
/// data of `element`.
fn bytes_before_address(address: usize, element: &ElementRef, offset: usize, len: usize) -> Option<Vec<u8>> {
    let block = element.as_data_container()?.get_block()?;
    let start = address.checked_sub(block.as_ptr() as usize)?;
    let begin = start.checked_sub(offset)?;
    block.get(begin..begin + len).map(<[u8]>::to_vec)
}

/// The address of the data, 0 without data.
fn address(data: DataPtr) -> usize {
    data.map_or(0, |data| data.as_ptr() as usize)
}

/// Port of `GetRelativeDeciderInteger`: the integer of `size` bytes at
/// `offset` before the data, or else the value of the element of the save
/// element `container_name`.
fn relative_decider_integer(
    offset: usize,
    size: usize,
    container_name: &str,
    integer_name: &str,
    base_address: usize,
    a_element: ElementArg,
) -> i64 {
    let Some(element) = a_element else { return MAX_INT };
    if base_address != 0 {
        let len = match size {
            2..=4 => size,
            _ => 1,
        };
        let Some(bytes) = bytes_before_address(base_address, element, offset, len) else {
            return MAX_INT;
        };
        return match size {
            4 => i64::from(i32::from_le_bytes(bytes[..4].try_into().unwrap())),
            // `wbReadInteger24` reads the three bytes from the most significant.
            3 => (i64::from(bytes[0]) << 16) | (i64::from(bytes[1]) << 8) | i64::from(bytes[2]),
            2 => i64::from(u16::from_le_bytes(bytes[..2].try_into().unwrap())),
            _ => i64::from(bytes[0]),
        };
    }
    let found = wb_find_save_element(container_name, element);
    let Some(container) = found.as_container() else {
        return MAX_INT;
    };
    let value = if integer_name.contains('\\') {
        container.get_element_by_path(integer_name)
    } else {
        container.get_element_by_name(integer_name)
    };
    value.map_or(MAX_INT, |value| native(Some(value)) as i32 as i64)
}

/// `relative_decider_integer` from the data pointer of the callback.
fn relative_integer(
    offset: usize,
    size: usize,
    container_name: &str,
    integer_name: &str,
    a_base_ptr: DataPtr,
    a_element: ElementArg,
) -> i64 {
    relative_decider_integer(
        offset,
        size,
        container_name,
        integer_name,
        address(a_base_ptr),
        a_element,
    )
}

/// Port of `ChangedFormGetType`: the type of the form without the size
/// bits, with the changed form.
fn changed_form_get_type(element: &ElementRef) -> (i32, ElementRef) {
    let (kind, changed_form) = fo4saves::changed_form_get_raw_type(element);
    (if kind > 0 { kind & 0x3F } else { kind }, changed_form)
}

/// Port of `ChangedFormGetLengthCode`: the size bits of the type.
fn changed_form_get_length_code(element: &ElementRef) -> (i32, ElementRef) {
    let (kind, changed_form) = fo4saves::changed_form_get_raw_type(element);
    (if kind >= 0 { kind >> 6 } else { kind }, changed_form)
}

/// Port of `ChangedFlagXXDecider`: the change flags of a leveled creature
/// are kept by `ChangedFormActorBaseDecider`.
fn changed_flag_xx_decider(mask: i64, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    if element.get_path().contains("\\ Leveled Creature \\") {
        return i32::from(i64::from(TEMP_CHANGED_FORM_FLAGS.get()) & mask != 0);
    }
    match save_value("Changed Form", element, "Change Flags") {
        Some(flags) if flags & mask != 0 => 1,
        _ => 0,
    }
}

/// Port of `IsCreatedDecider`.
fn is_created_decider(a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    match save_value("Changed Form", element, "RefID") {
        Some(id) if id >> 22 == 2 => 1,
        _ => 0,
    }
}

/// Upstream `ChangedFlag11OrCreatedDecider`.
pub fn changed_flag11_or_created_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    match changed_flag_xx_decider(0x800, a_element) {
        0 => is_created_decider(a_element),
        result => result,
    }
}

/// Upstream `ChangedFlag28ActorDecider`.
pub fn changed_flag28_actor_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let result = changed_flag_xx_decider(0x1000_0000, a_element);
    if result == 1 && !matches!(changed_form_get_type(element).0, 1 | 2) {
        return 0;
    }
    result
}

/// Upstream `ChangedFlag28NotActorDecider`.
pub fn changed_flag28_not_actor_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let result = changed_flag_xx_decider(0x1000_0000, a_element);
    if result == 1 && matches!(changed_form_get_type(element).0, 1 | 2) {
        return 0;
    }
    result
}

/// Upstream `ChangeFormBaseProcessCreatedPackageDecider`.
pub fn change_form_base_process_created_package_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let result = relative_integer(4, 3, "Package Struct", "Package", a_base_ptr, a_element);
    i32::from(result != MAX_INT && result >> 22 == 2)
}

/// Upstream `ChangeFormBaseProcessPackageDecider`.
pub fn change_form_base_process_package_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let result = relative_integer(4, 3, "Package Struct", "Package", a_base_ptr, a_element);
    i32::from(result != MAX_INT && result != 0)
}

/// Upstream `ChangeFormCombatControllerHasUnk0A0Decider`.
pub fn change_form_combat_controller_has_unk0_a0_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let result = relative_integer(2, 1, "Combat Controller", "Has Unk0A0", a_base_ptr, a_element);
    i32::from(result != MAX_INT && result != 0)
}

/// Upstream `ChangeFormCombatProcedureTypeDecider`.
pub fn change_form_combat_procedure_type_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let result = relative_integer(
        2,
        1,
        "Change Combat Procedure",
        "Combat Procedure Type",
        a_base_ptr,
        a_element,
    );
    if result == MAX_INT || result > 14 {
        0
    } else {
        1 + result as i32
    }
}

/// Upstream `ChangeFormCreatedPackageDecider`: the initialization of the
/// created package.
pub fn change_form_created_package_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let result = relative_integer(2, 1, "Created Package Struct", "Type", a_base_ptr, a_element);
    if result == MAX_INT {
        return 0;
    }
    match 1 + result {
        0 | 41 | 256 => 1,
        10 => 2,
        16 | 29 => 3,
        18 => 4,
        19 => 5,
        22 => 6,
        23 => 7,
        24 => 8,
        25 => 9,
        40 => 10,
        _ => 0,
    }
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit0DeciderBasePtr` and
/// the other data pointers that the first bit decider keeps for the next
/// ones.
static CREATED_PACKAGE_CONTENT_FLAGS: AtomicUsize = AtomicUsize::new(0);
static CREATED_PACKAGE_PRESENT_FLAGS: AtomicUsize = AtomicUsize::new(0);
static ACTOR_MOVER_CONTENT_FLAGS: AtomicUsize = AtomicUsize::new(0);
static PACKAGE_CREATED_CONTENT_FLAGS: AtomicUsize = AtomicUsize::new(0);

/// A decider of one bit of the flags at the data pointer the first bit
/// decider kept.
fn kept_flag_decider(
    kept: &AtomicUsize,
    first: Option<DataPtr>,
    container_name: &str,
    integer_name: &str,
    mask: i64,
    a_element: ElementArg,
) -> i32 {
    if let Some(a_base_ptr) = first {
        kept.store(address(a_base_ptr), Ordering::Relaxed);
    }
    let result = relative_decider_integer(
        2,
        1,
        container_name,
        integer_name,
        kept.load(Ordering::Relaxed),
        a_element,
    );
    i32::from(result != MAX_INT && result & mask != 0)
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit0Decider`.
pub fn change_form_created_package_has_content_flag_bit0_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_CONTENT_FLAGS,
        Some(a_base_ptr),
        "Unk09C",
        "Content Flags",
        1,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit1Decider`.
pub fn change_form_created_package_has_content_flag_bit1_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_CONTENT_FLAGS,
        None,
        "Unk09C",
        "Content Flags",
        2,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit2Decider`.
pub fn change_form_created_package_has_content_flag_bit2_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_CONTENT_FLAGS,
        None,
        "Unk09C",
        "Content Flags",
        4,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit3Decider`.
pub fn change_form_created_package_has_content_flag_bit3_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_CONTENT_FLAGS,
        None,
        "Unk09C",
        "Content Flags",
        8,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit4Decider`.
pub fn change_form_created_package_has_content_flag_bit4_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_CONTENT_FLAGS,
        None,
        "Unk09C",
        "Content Flags",
        16,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit5Decider`.
pub fn change_form_created_package_has_content_flag_bit5_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_CONTENT_FLAGS,
        None,
        "Unk09C",
        "Content Flags",
        32,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit0Decider`.
pub fn change_form_created_package_has_present_flag_bit0_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_PRESENT_FLAGS,
        Some(a_base_ptr),
        "Unk09C",
        "Present Flags",
        1,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit1Decider`.
pub fn change_form_created_package_has_present_flag_bit1_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_PRESENT_FLAGS,
        None,
        "Unk09C",
        "Present Flags",
        2,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit2Decider`.
pub fn change_form_created_package_has_present_flag_bit2_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_PRESENT_FLAGS,
        None,
        "Unk09C",
        "Present Flags",
        4,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit3Decider`.
pub fn change_form_created_package_has_present_flag_bit3_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_PRESENT_FLAGS,
        None,
        "Unk09C",
        "Present Flags",
        8,
        a_element,
    )
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit4Decider`.
pub fn change_form_created_package_has_present_flag_bit4_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &CREATED_PACKAGE_PRESENT_FLAGS,
        None,
        "Unk09C",
        "Present Flags",
        16,
        a_element,
    )
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit0Decider`.
pub fn changed_form_package_actor_mover_content_flags_bit0_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &ACTOR_MOVER_CONTENT_FLAGS,
        Some(a_base_ptr),
        "Actor Mover",
        "Content Flags",
        1,
        a_element,
    )
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit1Decider`.
pub fn changed_form_package_actor_mover_content_flags_bit1_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &ACTOR_MOVER_CONTENT_FLAGS,
        None,
        "Actor Mover",
        "Content Flags",
        2,
        a_element,
    )
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit2Decider`.
pub fn changed_form_package_actor_mover_content_flags_bit2_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &ACTOR_MOVER_CONTENT_FLAGS,
        None,
        "Actor Mover",
        "Content Flags",
        4,
        a_element,
    )
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit3Decider`.
pub fn changed_form_package_actor_mover_content_flags_bit3_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &ACTOR_MOVER_CONTENT_FLAGS,
        None,
        "Actor Mover",
        "Content Flags",
        8,
        a_element,
    )
}

/// Upstream `ChangedFormPackageCreatedContentFlagsBit0Decider`.
pub fn changed_form_package_created_content_flags_bit0_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &PACKAGE_CREATED_CONTENT_FLAGS,
        Some(a_base_ptr),
        "Data",
        "Content Flags",
        1,
        a_element,
    )
}

/// Upstream `ChangedFormPackageCreatedContentFlagsBit1Decider`.
pub fn changed_form_package_created_content_flags_bit1_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &PACKAGE_CREATED_CONTENT_FLAGS,
        None,
        "Data",
        "Content Flags",
        2,
        a_element,
    )
}

/// Upstream `ChangedFormPackageCreatedContentFlagsBit2Decider`.
pub fn changed_form_package_created_content_flags_bit2_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    kept_flag_decider(
        &PACKAGE_CREATED_CONTENT_FLAGS,
        None,
        "Data",
        "Content Flags",
        4,
        a_element,
    )
}

/// Upstream `ChangedFormPackageCreatedPackageDataTypeDecider`: from the
/// data pointer of the first content flag decider.
pub fn changed_form_package_created_package_data_type_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let result = relative_decider_integer(
        (13 - 4) + 2,
        1,
        "Data",
        "General\\Type",
        PACKAGE_CREATED_CONTENT_FLAGS.load(Ordering::Relaxed),
        a_element,
    );
    match result {
        1 | 2 => 1,
        3 | 8 | 9 => 2,
        13 => 3,
        15 | 28 => 4,
        16 => 5,
        _ => 0,
    }
}

/// Upstream `ChangeFormExtraPackageTypeDecider`.
pub fn change_form_extra_package_type_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    match relative_integer(2, 1, "Package Data", "Package Data Type", a_base_ptr, a_element) {
        2 => 1,
        12 => 2,
        13 => 3,
        14 => 4,
        16 => 5,
        _ => 0,
    }
}

/// Upstream `ExtraTypeToDecider` of `ChangedExtraUnionDecider`.
const EXTRA_TYPE_TO_DECIDER: [u8; 0x86] = [
    0x0, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x1, 0x3C, 2, 3, 4, 5, 6, 7, 8, 9, 0x3C, 0x0A, 0x0B, 0x0C,
    0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x3C, 0x12, 0x13, 0x14, 0x3C, 0x15, 0x16, 0x17, 0x3C, 0x18, 0x19, 0x3C, 0x1A, 0x3C,
    0x3C, 0x3C, 0x1B, 0x3C, 0x3C, 0x1C, 0x3C, 0x1D, 0x1E, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x1F, 0x20, 0x3C, 0x3C, 0x21,
    0x22, 0x3C, 0x3C, 0x23, 0x24, 0x3C, 0x25, 0x3C, 0x3C, 0x3C, 0x26, 0x27, 0x28, 0x3C, 0x3C, 0x3C, 0x3C, 0x29, 0x2A,
    0x2B, 0x2C, 0x2D, 0x2E, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x2F, 0x3C, 0x30, 0x3C,
    0x31, 0x3C, 0x3C, 0x32, 0x33, 0x34, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x35, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C,
    0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x3C, 0x36, 0x3C, 0x37, 0x3C, 0x38, 0x3C, 0x39, 0x3A, 0x3A, 0x3B,
];

/// Upstream `ChangedExtraUnionDecider`.
pub fn changed_extra_union_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let mut result = 0;
    if let Some(kind) = save_value("Extra", element, "Extra Type")
        && (0x0D..=0x0D + 0x85).contains(&kind)
    {
        result = 1 + i32::from(EXTRA_TYPE_TO_DECIDER[(kind - 0x0D) as usize]);
        if result == 0x3C + 1 {
            result = 0;
        }
    }
    result
}

/// Upstream `ChangedFlag00Decider`.
pub fn changed_flag00_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x1, a_element)
}

/// Upstream `ChangedFlag01Decider`.
pub fn changed_flag01_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x2, a_element)
}

/// Upstream `ChangedFlag02Decider`.
pub fn changed_flag02_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x4, a_element)
}

/// Upstream `ChangedFlag03Decider`.
pub fn changed_flag03_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x8, a_element)
}

/// Upstream `ChangedFlag04Decider`.
pub fn changed_flag04_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x10, a_element)
}

/// Upstream `ChangedFlag05Decider`.
pub fn changed_flag05_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x20, a_element)
}

/// Upstream `ChangedFlag05or27Decider`.
pub fn changed_flag05or27_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x8000020, a_element)
}

/// Upstream `ChangedFlag09Decider`.
pub fn changed_flag09_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x200, a_element)
}

/// Upstream `ChangedFlag10Decider`.
pub fn changed_flag10_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x400, a_element)
}

/// Upstream `ChangedFlag11Decider`.
pub fn changed_flag11_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x800, a_element)
}

/// Upstream `ChangedFlag19Decider`.
pub fn changed_flag19_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x80000, a_element)
}

/// Upstream `ChangedFlag20Decider`.
pub fn changed_flag20_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x100000, a_element)
}

/// Upstream `ChangedFlag21Decider`.
pub fn changed_flag21_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x200000, a_element)
}

/// Upstream `ChangedFlag22Decider`.
pub fn changed_flag22_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x400000, a_element)
}

/// Upstream `ChangedFlag23Decider`.
pub fn changed_flag23_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x800000, a_element)
}

/// Upstream `ChangedFlag24Decider`.
pub fn changed_flag24_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x1000000, a_element)
}

/// Upstream `ChangedFlag25Decider`.
pub fn changed_flag25_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x2000000, a_element)
}

/// Upstream `ChangedFlag28Decider`.
pub fn changed_flag28_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x10000000, a_element)
}

/// Upstream `ChangedFlag29Decider`.
pub fn changed_flag29_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x20000000, a_element)
}

/// Upstream `ChangedFlag30Decider`.
pub fn changed_flag30_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x40000000, a_element)
}

/// Upstream `ChangedFlag31Decider`.
pub fn changed_flag31_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_flag_xx_decider(0x80000000, a_element)
}

/// Upstream `ChangedFormActorBaseDecider`: keeps the change flags of the
/// leveled creature for the flag deciders.
pub fn changed_form_actor_base_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let mut result = match changed_form_get_type(element).0 {
        kind @ (1 | 2) => kind,
        _ => 0,
    };
    if result > 0 {
        let creature = wb_find_save_element("Leveled Creature", element);
        if let Some(container) = creature.as_container() {
            match container.get_element_by_name("Actor Base Changed Flags") {
                Some(flags) => TEMP_CHANGED_FORM_FLAGS.set(native(Some(flags)) as i32),
                None => result = 0,
            }
        }
    }
    result
}

/// Upstream `ChangedFormCellIsInteriorDecider`: an exterior cell has a
/// separator 0x20 bytes on.
pub fn changed_form_cell_is_interior_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    /// Upstream `wbTerminator`.
    const TERMINATOR: u8 = b'|';
    let byte = match a_base_ptr.and_then(|data| data.get(0x20)) {
        Some(byte) => Some(*byte),
        // Upstream reads past the end of the data.
        None => a_element.and_then(|element| {
            let block = element.as_data_container()?.get_block()?;
            let start = address(a_base_ptr).checked_sub(block.as_ptr() as usize)?;
            block.get(start + 0x20).copied()
        }),
    };
    i32::from(byte.is_some_and(|byte| byte != TERMINATOR))
}

/// Upstream `ChangedFormDataDecider`: the member for the form type.
pub fn changed_form_data_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let (kind, changed_form) = changed_form_get_type(element);
    if kind < 0 || changed_form.as_data_container().is_none() {
        return 0;
    }
    let result = 1 + kind;
    if result > 55 { 0 } else { result }
}

/// Upstream `ChangedFormDataLengthDecider`.
pub fn changed_form_data_length_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 3 };
    match changed_form_get_length_code(element).0 {
        size @ 0..=2 => size,
        _ => 3,
    }
}

/// Upstream `ChangedFormDataSizer`: the data of a changed form is never
/// compressed; the compressed size is its length.
pub fn changed_form_data_sizer(_a_base_ptr: DataPtr, a_element: ElementArg, compressed_size: &mut i32) -> u32 {
    const OFFSET_LENGTH: usize = 9;
    let Some(element) = a_element else {
        *compressed_size = 0;
        return 0;
    };
    let (size_length, changed_form) = changed_form_get_length_code(element);
    let Some(container) = changed_form.as_data_container().filter(|_| size_length >= 0) else {
        *compressed_size = 0;
        return 0;
    };
    match container.get_element_by_path("Datas\\CForm Data\\Length") {
        Some(length) => *compressed_size = native(Some(length)) as i32,
        None => {
            let data = container.get_data().unwrap_or_default();
            if let Some(value) = fo4saves::sized_value(data, OFFSET_LENGTH, size_length) {
                *compressed_size = value as i32;
            }
        }
    }
    0
}

/// The value of a child of a save element as a flag: 1 when the child is
/// above 0.
fn positive_decider(name: &str, child: &str, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let found = wb_find_save_element(name, element);
    let Some(container) = found.as_container() else {
        return 0;
    };
    match container.get_element_by_name(child) {
        Some(value) if native(Some(value.clone())) > 0 => 1,
        _ => 0,
    }
}

/// Upstream `ChangedFormEventListHasStruct010Decider`.
pub fn changed_form_event_list_has_struct010_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    positive_decider("Script Event List", "has Struct010", a_element)
}

/// Upstream `ChangedFormExtraDecider`.
pub fn changed_form_extra_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let kind = changed_form_get_type(element).0;
    let mut result = 0;
    if matches!(kind, 0 | 3..=6 | 44) && changed_flag_xx_decider(0xA402_1C40, a_element) != 0 {
        result = 1;
    }
    if matches!(kind, 1 | 2) && changed_flag_xx_decider(0xA406_1840, a_element) != 0 {
        result = 1;
    }
    result
}

/// Upstream `ChangedFormExtraScriptEventDecider`.
pub fn changed_form_extra_script_event_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let found = wb_find_save_element("Data", element);
    let Some(container) = found.as_container() else {
        return 0;
    };
    match container.get_element_by_name("FlagAndVarID") {
        Some(value) if native(Some(value.clone())) & 0x8000_0000 == 0 => 1,
        _ => 0,
    }
}

/// Upstream `ChangedFormFlagsDecider`.
pub fn changed_form_flags_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    changed_form_data_decider(a_base_ptr, a_element)
}

/// Upstream `ChangedFormGetChapterType`.
pub fn changed_form_get_chapter_type(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return -1 };
    let kind = changed_form_get_type(element).0;
    if kind >= 0 { CHANGED_FORM_OFFSET + kind } else { kind }
}

/// Upstream `ChangedFormGetChapterTypeName`: the whole name of the type.
pub fn changed_form_get_chapter_type_name(a_base_ptr: DataPtr, a_element: ElementArg) -> String {
    let kind = changed_form_get_chapter_type(a_base_ptr, a_element);
    let mut result = String::new();
    if let Some(change_types) = WB_CHANGE_TYPES.get()
        && kind >= CHANGED_FORM_OFFSET
        && kind < CHANGED_FORM_OFFSET + change_types.get_name_count()
    {
        result = change_types.get_name_of(i64::from(kind - CHANGED_FORM_OFFSET));
    }
    if result.is_empty() { kind.to_string() } else { result }
}

/// Upstream `ChangedFormHasUnk3DCDecider`.
pub fn changed_form_has_unk3_dc_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(relative_integer(25, 3, "Unk000", "Has Unk3DC", a_base_ptr, a_element) == 1)
}

/// Upstream `ChangedFormHighProcessSubBufferCounter`.
pub fn changed_form_high_process_sub_buffer_counter(_a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::save_value_counter("SubBuffer", "Length", a_element)
}

/// Upstream `ChangedFormList44CData00CDecider`.
pub fn changed_form_list44_c_data00_c_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(relative_integer(2, 3, "Data", "Unk020", a_base_ptr, a_element) == 1)
}

/// The process level of the mobile object, when it has one.
fn process_level(a_element: ElementArg) -> Option<i64> {
    let element = a_element?;
    let found = wb_find_save_element("Changed MobileObject", element);
    let level = found.as_container()?.get_element_by_name("Process Level")?;
    Some(native(Some(level)))
}

/// Upstream `ChangedFormMobileObjectBaseProcessDecider`.
pub fn changed_form_mobile_object_base_process_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(process_level(a_element).is_some_and(|level| level != -1))
}

/// Upstream `ChangedFormMobileObjectHighProcessDecider`.
pub fn changed_form_mobile_object_high_process_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(process_level(a_element).is_some_and(|level| level < 1))
}

/// Upstream `ChangedFormMobileObjectLowProcessDecider`.
pub fn changed_form_mobile_object_low_process_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(process_level(a_element).is_some_and(|level| level < 4))
}

/// Upstream `ChangedFormMobileObjectMiddleHighProcessDecider`.
pub fn changed_form_mobile_object_middle_high_process_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(process_level(a_element).is_some_and(|level| level < 2))
}

/// Upstream `ChangedFormMobileObjectMiddleLowProcessDecider`.
pub fn changed_form_mobile_object_middle_low_process_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(process_level(a_element).is_some_and(|level| level < 3))
}

/// A decider of a relative byte that is 0 when it is not found.
fn relative_or_zero(offset: usize, container: &str, name: &str, a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    match relative_integer(offset, 1, container, name, a_base_ptr, a_element) {
        MAX_INT => 0,
        result => result as i32,
    }
}

/// Upstream `ChangedFormPackageCreatedAUEHasLocationDecider`.
pub fn changed_form_package_created_aue_has_location_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    relative_or_zero(2, "Ambush/Use Item/Eat", "Has Location", a_base_ptr, a_element)
}

/// Upstream `ChangedFormPackageCreatedDHasLocationDecider`.
pub fn changed_form_package_created_d_has_location_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    relative_or_zero(2, "Dialogue", "Has Location", a_base_ptr, a_element)
}

/// Upstream `ChangedFormPackageCreatedFEHasLocationDecider`.
pub fn changed_form_package_created_fe_has_location_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    relative_or_zero(2, "Follow/Escort", "Has Location", a_base_ptr, a_element)
}

/// Upstream `ChangedFormPackageCreatedUWHasLocationDecider`.
pub fn changed_form_package_created_uw_has_location_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    relative_or_zero(2, "Use Weapon", "Has Location", a_base_ptr, a_element)
}

/// Upstream `ChangedFormPackageCreatedUWHasTargetDecider`.
pub fn changed_form_package_created_uw_has_target_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    relative_or_zero(2, "Use Weapon", "Has Target", a_base_ptr, a_element)
}

/// Upstream `ChangedFormPathingRequestTypeDecider`.
pub fn changed_form_pathing_request_type_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    relative_or_zero(2, "Pathing Request", "Type", a_base_ptr, a_element)
}

/// Upstream `ChangedFormPackageLocationTypeDecider`.
pub fn changed_form_package_location_type_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    match relative_integer(7, 1, "Location", "Type", a_base_ptr, a_element) {
        0..=4 => 1,
        5 => 2,
        _ => 0,
    }
}

/// Upstream `ChangedFormPackageTargetTypeDecider`.
pub fn changed_form_package_target_type_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    match relative_integer(12, 1, "Target", "Type", a_base_ptr, a_element) {
        0 | 1 => 1,
        2 => 2,
        _ => 0,
    }
}

/// Upstream `ChangedFormPathingRequestSubStructHasUnk00CDecider`.
pub fn changed_form_pathing_request_sub_struct_has_unk00_c_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    i32::from(relative_integer(25, 1, "PathingRequest subStruct", "Byt020", a_base_ptr, a_element) == 1)
}

/// A decider that is 1 when the child of the save element is not 0.
fn nonzero_decider(name: &str, child: &str, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    match save_child(name, element, child) {
        Some(value) if native(Some(value.clone())) != 0 => 1,
        _ => 0,
    }
}

/// Upstream `ChangedFormProjectileHasEntryDataDecider`.
pub fn changed_form_projectile_has_entry_data_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    nonzero_decider("Changed Projectile", "Has Entry Data", a_element)
}

/// Upstream `ChangedFormQuestStageHasLogDataDecider`.
pub fn changed_form_quest_stage_has_log_data_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    nonzero_decider("Data", "Has Log Data", a_element)
}

/// Upstream `Lst0044Has00D4DataDecider`.
pub fn lst0044_has00_d4_data_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    nonzero_decider("Lst044 Data", "Unk00D0", a_element)
}

/// Upstream `Lst0044HasArr0018DataDecider`.
pub fn lst0044_has_arr0018_data_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    nonzero_decider("Lst044 Data", "Unk00D0", a_element)
}

/// Upstream `ChangedFormRemainingDataCounter`: the length of the form data
/// after the first two elements of the changed form data.
pub fn changed_form_remaining_data_counter(_a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    let Some(element) = a_element else { return 0 };
    let cform = wb_find_save_element("CForm Data", element);
    let mut result = cform
        .as_data_container()
        .and_then(|container| container.get_element_by_name("Length"))
        .filter(|length| length.as_data_container().is_some())
        .map_or(0, |length| native(Some(length)) as u32);
    if result > 0 {
        let data = wb_find_save_element("Changed Form Data", element);
        if let Some(container) = data.as_data_container()
            && let Some(third) = container.get_element(2)
            && let Some(third) = third.as_data_container()
        {
            result = result.wrapping_sub(consumed(third.get_data(), container.get_data()));
        }
    }
    result
}

/// Upstream `GlobalData2TableSizeCounter`.
pub fn global_data2_table_size_counter(_a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::save_value_counter("Global Data 2", "Size", a_element)
}

/// Upstream `GlobalDataDecider`: only the types 0 to 11 are decoded.
pub fn global_data_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let mut element = element.clone();
    while !element.get_name().contains("Global Data ") {
        match element.get_container() {
            Some(container) => element = container,
            None => break,
        }
    }
    let Some(container) = element.as_data_container() else {
        return 0;
    };
    let mut result = 0;
    if let Some(kind) = container.get_element_by_name("Type") {
        result = match native(Some(kind)) {
            kind @ 0..=11 => kind as i32 + 1,
            1000 => 13,
            _ => 0,
        };
    }
    if result > 12 { 0 } else { result }
}

/// Upstream `HasDialogueItemsDecider`.
pub fn has_dialogue_items_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let result = relative_integer(2, 1, "Dialogue Struct", "Has Dialogue Items", a_base_ptr, a_element);
    i32::from(result != MAX_INT && result != 0)
}

/// Upstream `InitialDataTypeDecider`.
pub fn initial_data_type_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let (kind, changed_form) = changed_form_get_type(element);
    if kind < 0 {
        return 0;
    }
    let Some(container) = changed_form.as_data_container() else {
        return 0;
    };
    let flag = |mask: i64| changed_flag_xx_decider(mask, a_element) != 0;
    let mut result = 0;
    if kind == 7 {
        // CELL
        if flag(0x4000_0000) && flag(0x2000_0000) {
            result = 1;
        } else if flag(0x4000_0000) && flag(0x1000_0000) {
            result = 2;
        } else if flag(0x4000_0000) {
            result = 3;
        }
    }
    if matches!(kind, 0..=6 | 44) {
        // REFR or a descendant.
        let constructed = container
            .get_element_by_name("RefID")
            .is_some_and(|ref_id| native(Some(ref_id)) >> 22 == 2);
        if constructed {
            result = 5;
        } else if flag(0x8) {
            result = 6;
        } else if flag(0x6) {
            result = 4;
        }
    }
    result
}

/// Upstream `NVSEChaptersDecider`: the member for the chunk type.
pub fn nvse_chapters_decider(_a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    let Some(element) = a_element else { return 0 };
    let chunk = wb_find_save_element("Chunk", element);
    let Some(kind) = chunk
        .as_data_container()
        .and_then(|chunk| chunk.get_element_by_name("Type"))
    else {
        return 0;
    };
    match kind.get_value().as_str() {
        "MODS" => 1,
        "STVS" => 2,
        "STVR" => 3,
        "STVE" => 4,
        "ARVS" => 5,
        "ARVR" => 6,
        "ARVE" => 7,
        _ => 8,
    }
}

/// Upstream `ScreenShotDataCounter`: three bytes per pixel.
pub fn screen_shot_data_counter(_a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    let Some(element) = a_element else { return 0 };
    let Some(width) = root_value(element, "Save File Header\\Header\\Screenshot Width") else {
        return 0;
    };
    match root_value(element, "Save File Header\\Header\\Screenshot Height") {
        Some(height) => (3 * width * height) as u32,
        None => width as u32,
    }
}

/// Upstream `ChangedFormAnimationSubBufferCounter`, the same as for Fallout 4.
pub fn changed_form_animation_sub_buffer_counter(a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::changed_form_animation_sub_buffer_counter(a_base_ptr, a_element)
}

/// Upstream `ChangedFormGetChapterName`, the same as for Fallout 4.
pub fn changed_form_get_chapter_name(a_base_ptr: DataPtr, a_element: ElementArg) -> String {
    fo4saves::changed_form_get_chapter_name(a_base_ptr, a_element)
}

/// Upstream `ChangedFormHavokMovedSubBufferCounter`, the same as for Fallout 4.
pub fn changed_form_havok_moved_sub_buffer_counter(a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::changed_form_havok_moved_sub_buffer_counter(a_base_ptr, a_element)
}

/// Upstream `ChangedFormsCounter`, the same as for Fallout 4.
pub fn changed_forms_counter(a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::changed_forms_counter(a_base_ptr, a_element)
}

/// Upstream `DataCounter`, the same as for Fallout 4.
pub fn data_counter(a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::data_counter(a_base_ptr, a_element)
}

/// Upstream `GlobalData1Counter`, the same as for Fallout 4.
pub fn global_data1_counter(a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::global_data1_counter(a_base_ptr, a_element)
}

/// Upstream `GlobalData2Counter`, the same as for Fallout 4.
pub fn global_data2_counter(a_base_ptr: DataPtr, a_element: ElementArg) -> u32 {
    fo4saves::global_data2_counter(a_base_ptr, a_element)
}

/// Upstream `GlobalDataGetChapterType`, the same as for Fallout 4.
pub fn global_data_get_chapter_type(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    fo4saves::global_data_get_chapter_type(a_base_ptr, a_element)
}

/// Upstream `GlobalDataGetChapterTypeName`, the same as for Fallout 4.
pub fn global_data_get_chapter_type_name(a_base_ptr: DataPtr, a_element: ElementArg) -> String {
    fo4saves::global_data_get_chapter_type_name(a_base_ptr, a_element)
}

/// Upstream `IsActorPlayerDecider`, the same as for Fallout 4.
pub fn is_actor_player_decider(a_base_ptr: DataPtr, a_element: ElementArg) -> i32 {
    fo4saves::is_actor_player_decider(a_base_ptr, a_element)
}

/// Upstream `ChangedFormSizer`, the same as for Fallout 4.
pub fn changed_form_sizer(a_base_ptr: DataPtr, a_element: ElementArg, compressed_size: &mut i32) -> u32 {
    fo4saves::changed_form_sizer(a_base_ptr, a_element, compressed_size)
}

/// Upstream `GlobalDataSizer`, the same as for Fallout 4.
pub fn global_data_sizer(a_base_ptr: DataPtr, a_element: ElementArg, compressed_size: &mut i32) -> u32 {
    fo4saves::global_data_sizer(a_base_ptr, a_element, compressed_size)
}

/// Upstream `RefIDTableAfterLoad`, the same as for Fallout 4.
pub fn ref_id_table_after_load(a_element: &ElementRef) {
    fo4saves::ref_id_table_after_load(a_element)
}

/// Upstream `WorldspaceTableAfterLoad`, the same as for Fallout 4.
pub fn worldspace_table_after_load(a_element: &ElementRef) {
    fo4saves::worldspace_table_after_load(a_element)
}
