// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsFNVSaves.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use std::sync::Arc;

use xedit_core::interface::*;

/// Upstream `ChangeFormBaseProcessCreatedPackageDecider`, line 1414 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_base_process_created_package_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormBaseProcessCreatedPackageDecider from wbDefinitionsFNVSaves.pas line 1414")
}

/// Upstream `ChangeFormBaseProcessPackageDecider`, line 1427 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_base_process_package_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormBaseProcessPackageDecider from wbDefinitionsFNVSaves.pas line 1427")
}

/// Upstream `ChangeFormCombatControllerHasUnk0A0Decider`, line 1624 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_combat_controller_has_unk0_a0_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCombatControllerHasUnk0A0Decider from wbDefinitionsFNVSaves.pas line 1624")
}

/// Upstream `ChangeFormCombatProcedureTypeDecider`, line 1635 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_combat_procedure_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCombatProcedureTypeDecider from wbDefinitionsFNVSaves.pas line 1635")
}

/// Upstream `ChangeFormCreatedPackageDecider`, line 1438 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageDecider from wbDefinitionsFNVSaves.pas line 1438")
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit0Decider`, line 1479 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_content_flag_bit0_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasContentFlagBit0Decider from wbDefinitionsFNVSaves.pas line 1479")
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit1Decider`, line 1496 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_content_flag_bit1_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasContentFlagBit1Decider from wbDefinitionsFNVSaves.pas line 1496")
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit2Decider`, line 1508 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_content_flag_bit2_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasContentFlagBit2Decider from wbDefinitionsFNVSaves.pas line 1508")
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit3Decider`, line 1520 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_content_flag_bit3_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasContentFlagBit3Decider from wbDefinitionsFNVSaves.pas line 1520")
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit4Decider`, line 1532 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_content_flag_bit4_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasContentFlagBit4Decider from wbDefinitionsFNVSaves.pas line 1532")
}

/// Upstream `ChangeFormCreatedPackageHasContentFlagBit5Decider`, line 1544 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_content_flag_bit5_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasContentFlagBit5Decider from wbDefinitionsFNVSaves.pas line 1544")
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit0Decider`, line 1559 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_present_flag_bit0_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasPresentFlagBit0Decider from wbDefinitionsFNVSaves.pas line 1559")
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit1Decider`, line 1576 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_present_flag_bit1_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasPresentFlagBit1Decider from wbDefinitionsFNVSaves.pas line 1576")
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit2Decider`, line 1588 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_present_flag_bit2_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasPresentFlagBit2Decider from wbDefinitionsFNVSaves.pas line 1588")
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit3Decider`, line 1600 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_present_flag_bit3_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasPresentFlagBit3Decider from wbDefinitionsFNVSaves.pas line 1600")
}

/// Upstream `ChangeFormCreatedPackageHasPresentFlagBit4Decider`, line 1612 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_created_package_has_present_flag_bit4_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormCreatedPackageHasPresentFlagBit4Decider from wbDefinitionsFNVSaves.pas line 1612")
}

/// Upstream `ChangeFormExtraPackageTypeDecider`, line 1261 of `wbDefinitionsFNVSaves.pas`.
pub fn change_form_extra_package_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangeFormExtraPackageTypeDecider from wbDefinitionsFNVSaves.pas line 1261")
}

/// Upstream `ChangedExtraUnionDecider`, line 1278 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_extra_union_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedExtraUnionDecider from wbDefinitionsFNVSaves.pas line 1278")
}

/// Upstream `ChangedFlag00Decider`, line 606 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag00_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag00Decider from wbDefinitionsFNVSaves.pas line 606")
}

/// Upstream `ChangedFlag01Decider`, line 611 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag01_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag01Decider from wbDefinitionsFNVSaves.pas line 611")
}

/// Upstream `ChangedFlag02Decider`, line 616 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag02_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag02Decider from wbDefinitionsFNVSaves.pas line 616")
}

/// Upstream `ChangedFlag03Decider`, line 626 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag03_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag03Decider from wbDefinitionsFNVSaves.pas line 626")
}

/// Upstream `ChangedFlag04Decider`, line 631 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag04_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag04Decider from wbDefinitionsFNVSaves.pas line 631")
}

/// Upstream `ChangedFlag05Decider`, line 636 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag05_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag05Decider from wbDefinitionsFNVSaves.pas line 636")
}

/// Upstream `ChangedFlag05or27Decider`, line 763 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag05or27_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag05or27Decider from wbDefinitionsFNVSaves.pas line 763")
}

/// Upstream `ChangedFlag09Decider`, line 656 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag09_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag09Decider from wbDefinitionsFNVSaves.pas line 656")
}

/// Upstream `ChangedFlag10Decider`, line 661 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag10_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag10Decider from wbDefinitionsFNVSaves.pas line 661")
}

/// Upstream `ChangedFlag11Decider`, line 666 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag11_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag11Decider from wbDefinitionsFNVSaves.pas line 666")
}

/// Upstream `ChangedFlag11OrCreatedDecider`, line 671 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag11_or_created_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag11OrCreatedDecider from wbDefinitionsFNVSaves.pas line 671")
}

/// Upstream `ChangedFlag19Decider`, line 713 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag19_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag19Decider from wbDefinitionsFNVSaves.pas line 713")
}

/// Upstream `ChangedFlag20Decider`, line 718 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag20_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag20Decider from wbDefinitionsFNVSaves.pas line 718")
}

/// Upstream `ChangedFlag21Decider`, line 723 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag21_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag21Decider from wbDefinitionsFNVSaves.pas line 723")
}

/// Upstream `ChangedFlag22Decider`, line 728 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag22_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag22Decider from wbDefinitionsFNVSaves.pas line 728")
}

/// Upstream `ChangedFlag23Decider`, line 733 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag23_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag23Decider from wbDefinitionsFNVSaves.pas line 733")
}

/// Upstream `ChangedFlag24Decider`, line 738 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag24_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag24Decider from wbDefinitionsFNVSaves.pas line 738")
}

/// Upstream `ChangedFlag25Decider`, line 743 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag25_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag25Decider from wbDefinitionsFNVSaves.pas line 743")
}

/// Upstream `ChangedFlag28ActorDecider`, line 782 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag28_actor_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag28ActorDecider from wbDefinitionsFNVSaves.pas line 782")
}

/// Upstream `ChangedFlag28Decider`, line 768 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag28_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag28Decider from wbDefinitionsFNVSaves.pas line 768")
}

/// Upstream `ChangedFlag28NotActorDecider`, line 773 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag28_not_actor_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag28NotActorDecider from wbDefinitionsFNVSaves.pas line 773")
}

/// Upstream `ChangedFlag29Decider`, line 791 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag29_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag29Decider from wbDefinitionsFNVSaves.pas line 791")
}

/// Upstream `ChangedFlag30Decider`, line 796 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag30_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag30Decider from wbDefinitionsFNVSaves.pas line 796")
}

/// Upstream `ChangedFlag31Decider`, line 806 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_flag31_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFlag31Decider from wbDefinitionsFNVSaves.pas line 806")
}

/// Upstream `ChangedFormActorBaseDecider`, line 1234 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_actor_base_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormActorBaseDecider from wbDefinitionsFNVSaves.pas line 1234")
}

/// Upstream `ChangedFormAnimationSubBufferCounter`, line 412 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_animation_sub_buffer_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port ChangedFormAnimationSubBufferCounter from wbDefinitionsFNVSaves.pas line 412")
}

/// Upstream `ChangedFormCellIsInteriorDecider`, line 873 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_cell_is_interior_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormCellIsInteriorDecider from wbDefinitionsFNVSaves.pas line 873")
}

/// Upstream `ChangedFormDataDecider`, line 536 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormDataDecider from wbDefinitionsFNVSaves.pas line 536")
}

/// Upstream `ChangedFormDataLengthDecider`, line 518 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_data_length_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormDataLengthDecider from wbDefinitionsFNVSaves.pas line 518")
}

/// Upstream `ChangedFormDataSizer`, line 428 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_data_sizer(_a_base_ptr: DataPtr, _a_element: ElementArg, compressed_size: &mut i32) -> u32 {
    todo!("port ChangedFormDataSizer from wbDefinitionsFNVSaves.pas line 428")
}

/// Upstream `ChangedFormEventListHasStruct010Decider`, line 1216 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_event_list_has_struct010_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormEventListHasStruct010Decider from wbDefinitionsFNVSaves.pas line 1216")
}

/// Upstream `ChangedFormExtraDecider`, line 1179 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_extra_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormExtraDecider from wbDefinitionsFNVSaves.pas line 1179")
}

/// Upstream `ChangedFormExtraScriptEventDecider`, line 1198 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_extra_script_event_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormExtraScriptEventDecider from wbDefinitionsFNVSaves.pas line 1198")
}

/// Upstream `ChangedFormFlagsDecider`, line 555 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_flags_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormFlagsDecider from wbDefinitionsFNVSaves.pas line 555")
}

/// Upstream `ChangedFormGetChapterName`, line 505 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_get_chapter_name(_a_base_ptr: DataPtr, _a_element: ElementArg) -> String {
    todo!("port ChangedFormGetChapterName from wbDefinitionsFNVSaves.pas line 505")
}

/// Upstream `ChangedFormGetChapterType`, line 478 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_get_chapter_type(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormGetChapterType from wbDefinitionsFNVSaves.pas line 478")
}

/// Upstream `ChangedFormGetChapterTypeName`, line 488 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_get_chapter_type_name(_a_base_ptr: DataPtr, _a_element: ElementArg) -> String {
    todo!("port ChangedFormGetChapterTypeName from wbDefinitionsFNVSaves.pas line 488")
}

/// Upstream `ChangedFormHasUnk3DCDecider`, line 1403 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_has_unk3_dc_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormHasUnk3DCDecider from wbDefinitionsFNVSaves.pas line 1403")
}

/// Upstream `ChangedFormHavokMovedSubBufferCounter`, line 326 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_havok_moved_sub_buffer_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port ChangedFormHavokMovedSubBufferCounter from wbDefinitionsFNVSaves.pas line 326")
}

/// Upstream `ChangedFormHighProcessSubBufferCounter`, line 342 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_high_process_sub_buffer_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port ChangedFormHighProcessSubBufferCounter from wbDefinitionsFNVSaves.pas line 342")
}

/// Upstream `ChangedFormList44CData00CDecider`, line 1392 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_list44_c_data00_c_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormList44CData00CDecider from wbDefinitionsFNVSaves.pas line 1392")
}

/// Upstream `ChangedFormMobileObjectBaseProcessDecider`, line 1317 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_mobile_object_base_process_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormMobileObjectBaseProcessDecider from wbDefinitionsFNVSaves.pas line 1317")
}

/// Upstream `ChangedFormMobileObjectHighProcessDecider`, line 1377 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_mobile_object_high_process_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormMobileObjectHighProcessDecider from wbDefinitionsFNVSaves.pas line 1377")
}

/// Upstream `ChangedFormMobileObjectLowProcessDecider`, line 1332 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_mobile_object_low_process_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormMobileObjectLowProcessDecider from wbDefinitionsFNVSaves.pas line 1332")
}

/// Upstream `ChangedFormMobileObjectMiddleHighProcessDecider`, line 1362 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_mobile_object_middle_high_process_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormMobileObjectMiddleHighProcessDecider from wbDefinitionsFNVSaves.pas line 1362")
}

/// Upstream `ChangedFormMobileObjectMiddleLowProcessDecider`, line 1347 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_mobile_object_middle_low_process_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormMobileObjectMiddleLowProcessDecider from wbDefinitionsFNVSaves.pas line 1347")
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit0Decider`, line 1078 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_actor_mover_content_flags_bit0_decider(
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
) -> i32 {
    todo!("port ChangedFormPackageActorMoverContentFlagsBit0Decider from wbDefinitionsFNVSaves.pas line 1078")
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit1Decider`, line 1094 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_actor_mover_content_flags_bit1_decider(
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
) -> i32 {
    todo!("port ChangedFormPackageActorMoverContentFlagsBit1Decider from wbDefinitionsFNVSaves.pas line 1094")
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit2Decider`, line 1105 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_actor_mover_content_flags_bit2_decider(
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
) -> i32 {
    todo!("port ChangedFormPackageActorMoverContentFlagsBit2Decider from wbDefinitionsFNVSaves.pas line 1105")
}

/// Upstream `ChangedFormPackageActorMoverContentFlagsBit3Decider`, line 1116 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_actor_mover_content_flags_bit3_decider(
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
) -> i32 {
    todo!("port ChangedFormPackageActorMoverContentFlagsBit3Decider from wbDefinitionsFNVSaves.pas line 1116")
}

/// Upstream `ChangedFormPackageCreatedAUEHasLocationDecider`, line 972 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_aue_has_location_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedAUEHasLocationDecider from wbDefinitionsFNVSaves.pas line 972")
}

/// Upstream `ChangedFormPackageCreatedContentFlagsBit0Decider`, line 1037 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_content_flags_bit0_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedContentFlagsBit0Decider from wbDefinitionsFNVSaves.pas line 1037")
}

/// Upstream `ChangedFormPackageCreatedContentFlagsBit1Decider`, line 1053 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_content_flags_bit1_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedContentFlagsBit1Decider from wbDefinitionsFNVSaves.pas line 1053")
}

/// Upstream `ChangedFormPackageCreatedContentFlagsBit2Decider`, line 1064 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_content_flags_bit2_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedContentFlagsBit2Decider from wbDefinitionsFNVSaves.pas line 1064")
}

/// Upstream `ChangedFormPackageCreatedDHasLocationDecider`, line 981 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_d_has_location_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedDHasLocationDecider from wbDefinitionsFNVSaves.pas line 981")
}

/// Upstream `ChangedFormPackageCreatedFEHasLocationDecider`, line 963 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_fe_has_location_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedFEHasLocationDecider from wbDefinitionsFNVSaves.pas line 963")
}

/// Upstream `ChangedFormPackageCreatedPackageDataTypeDecider`, line 1162 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_package_data_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedPackageDataTypeDecider from wbDefinitionsFNVSaves.pas line 1162")
}

/// Upstream `ChangedFormPackageCreatedUWHasLocationDecider`, line 990 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_uw_has_location_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedUWHasLocationDecider from wbDefinitionsFNVSaves.pas line 990")
}

/// Upstream `ChangedFormPackageCreatedUWHasTargetDecider`, line 999 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_created_uw_has_target_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageCreatedUWHasTargetDecider from wbDefinitionsFNVSaves.pas line 999")
}

/// Upstream `ChangedFormPackageLocationTypeDecider`, line 1008 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_location_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageLocationTypeDecider from wbDefinitionsFNVSaves.pas line 1008")
}

/// Upstream `ChangedFormPackageTargetTypeDecider`, line 1021 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_package_target_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPackageTargetTypeDecider from wbDefinitionsFNVSaves.pas line 1021")
}

/// Upstream `ChangedFormPathingRequestSubStructHasUnk00CDecider`, line 1136 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_pathing_request_sub_struct_has_unk00_c_decider(
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
) -> i32 {
    todo!("port ChangedFormPathingRequestSubStructHasUnk00CDecider from wbDefinitionsFNVSaves.pas line 1136")
}

/// Upstream `ChangedFormPathingRequestTypeDecider`, line 1127 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_pathing_request_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormPathingRequestTypeDecider from wbDefinitionsFNVSaves.pas line 1127")
}

/// Upstream `ChangedFormProjectileHasEntryDataDecider`, line 883 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_projectile_has_entry_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormProjectileHasEntryDataDecider from wbDefinitionsFNVSaves.pas line 883")
}

/// Upstream `ChangedFormQuestStageHasLogDataDecider`, line 899 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_quest_stage_has_log_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port ChangedFormQuestStageHasLogDataDecider from wbDefinitionsFNVSaves.pas line 899")
}

/// Upstream `ChangedFormRemainingDataCounter`, line 1646 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_remaining_data_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port ChangedFormRemainingDataCounter from wbDefinitionsFNVSaves.pas line 1646")
}

/// Upstream `ChangedFormSizer`, line 460 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_form_sizer(_a_base_ptr: DataPtr, _a_element: ElementArg, compressed_size: &mut i32) -> u32 {
    todo!("port ChangedFormSizer from wbDefinitionsFNVSaves.pas line 460")
}

/// Upstream `ChangedFormsCounter`, line 166 of `wbDefinitionsFNVSaves.pas`.
pub fn changed_forms_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port ChangedFormsCounter from wbDefinitionsFNVSaves.pas line 166")
}

/// Upstream `DataCounter`, line 1749 of `wbDefinitionsFNVSaves.pas`.
pub fn data_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port DataCounter from wbDefinitionsFNVSaves.pas line 1749")
}

/// Upstream `GlobalData1Counter`, line 151 of `wbDefinitionsFNVSaves.pas`.
pub fn global_data1_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port GlobalData1Counter from wbDefinitionsFNVSaves.pas line 151")
}

/// Upstream `GlobalData2Counter`, line 156 of `wbDefinitionsFNVSaves.pas`.
pub fn global_data2_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port GlobalData2Counter from wbDefinitionsFNVSaves.pas line 156")
}

/// Upstream `GlobalData2TableSizeCounter`, line 171 of `wbDefinitionsFNVSaves.pas`.
pub fn global_data2_table_size_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port GlobalData2TableSizeCounter from wbDefinitionsFNVSaves.pas line 171")
}

/// Upstream `GlobalDataDecider`, line 187 of `wbDefinitionsFNVSaves.pas`.
pub fn global_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port GlobalDataDecider from wbDefinitionsFNVSaves.pas line 187")
}

/// Upstream `GlobalDataGetChapterType`, line 259 of `wbDefinitionsFNVSaves.pas`.
pub fn global_data_get_chapter_type(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port GlobalDataGetChapterType from wbDefinitionsFNVSaves.pas line 259")
}

/// Upstream `GlobalDataGetChapterTypeName`, line 271 of `wbDefinitionsFNVSaves.pas`.
pub fn global_data_get_chapter_type_name(_a_base_ptr: DataPtr, _a_element: ElementArg) -> String {
    todo!("port GlobalDataGetChapterTypeName from wbDefinitionsFNVSaves.pas line 271")
}

/// Upstream `GlobalDataSizer`, line 290 of `wbDefinitionsFNVSaves.pas`.
pub fn global_data_sizer(_a_base_ptr: DataPtr, _a_element: ElementArg, compressed_size: &mut i32) -> u32 {
    todo!("port GlobalDataSizer from wbDefinitionsFNVSaves.pas line 290")
}

/// Upstream `HasDialogueItemsDecider`, line 1465 of `wbDefinitionsFNVSaves.pas`.
pub fn has_dialogue_items_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port HasDialogueItemsDecider from wbDefinitionsFNVSaves.pas line 1465")
}

/// Upstream `InitialDataTypeDecider`, line 841 of `wbDefinitionsFNVSaves.pas`.
pub fn initial_data_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port InitialDataTypeDecider from wbDefinitionsFNVSaves.pas line 841")
}

/// Upstream `IsActorPlayerDecider`, line 814 of `wbDefinitionsFNVSaves.pas`.
pub fn is_actor_player_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port IsActorPlayerDecider from wbDefinitionsFNVSaves.pas line 814")
}

/// Upstream `Lst0044Has00D4DataDecider`, line 931 of `wbDefinitionsFNVSaves.pas`.
pub fn lst0044_has00_d4_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port Lst0044Has00D4DataDecider from wbDefinitionsFNVSaves.pas line 931")
}

/// Upstream `Lst0044HasArr0018DataDecider`, line 915 of `wbDefinitionsFNVSaves.pas`.
pub fn lst0044_has_arr0018_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port Lst0044HasArr0018DataDecider from wbDefinitionsFNVSaves.pas line 915")
}

/// Upstream `NVSEChaptersDecider`, line 1799 of `wbDefinitionsFNVSaves.pas`.
pub fn nvse_chapters_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port NVSEChaptersDecider from wbDefinitionsFNVSaves.pas line 1799")
}

/// Upstream `RefIDTableAfterLoad`, line 228 of `wbDefinitionsFNVSaves.pas`.
pub fn ref_id_table_after_load(_a_element: &ElementRef) {
    todo!("port RefIDTableAfterLoad from wbDefinitionsFNVSaves.pas line 228")
}

/// Upstream `ScreenShotDataCounter`, line 104 of `wbDefinitionsFNVSaves.pas`.
pub fn screen_shot_data_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port ScreenShotDataCounter from wbDefinitionsFNVSaves.pas line 104")
}

/// Upstream `WorldspaceTableAfterLoad`, line 217 of `wbDefinitionsFNVSaves.pas`.
pub fn worldspace_table_after_load(_a_element: &ElementRef) {
    todo!("port WorldspaceTableAfterLoad from wbDefinitionsFNVSaves.pas line 217")
}
