// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsFO3.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `wbCELLAfterLoad`, line 2275 of `wbDefinitionsFO3.pas`.
pub fn wb_cell_after_load(_a_element: &ElementRef) {
    todo!("port wbCELLAfterLoad from wbDefinitionsFO3.pas line 2275")
}

/// Upstream `wbConditionsfterLoad`, line 746 of `wbDefinitionsFO3.pas`.
pub fn wb_conditionsfter_load(_a_element: &ElementRef) {
    todo!("port wbConditionsfterLoad from wbDefinitionsFO3.pas line 746")
}

/// Upstream `wbEFITAfterLoad`, line 2496 of `wbDefinitionsFO3.pas`.
pub fn wb_efit_after_load(_a_element: &ElementRef) {
    todo!("port wbEFITAfterLoad from wbDefinitionsFO3.pas line 2496")
}

/// Upstream `wbEFSHAfterLoad`, line 2437 of `wbDefinitionsFO3.pas`.
pub fn wb_efsh_after_load(_a_element: &ElementRef) {
    todo!("port wbEFSHAfterLoad from wbDefinitionsFO3.pas line 2437")
}

/// Upstream `wbEmbeddedScriptAfterLoad`, line 2306 of `wbDefinitionsFO3.pas`.
pub fn wb_embedded_script_after_load(_a_element: &ElementRef) {
    todo!("port wbEmbeddedScriptAfterLoad from wbDefinitionsFO3.pas line 2306")
}

/// Upstream `wbFACTAfterLoad`, line 2469 of `wbDefinitionsFO3.pas`.
pub fn wb_fact_after_load(_a_element: &ElementRef) {
    todo!("port wbFACTAfterLoad from wbDefinitionsFO3.pas line 2469")
}

/// Upstream `wbFLSTEDIDAfterSet`, line 949 of `wbDefinitionsFO3.pas`.
pub fn wb_flstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbFLSTEDIDAfterSet from wbDefinitionsFO3.pas line 949")
}

/// Upstream `wbGMSTEDIDAfterSet`, line 929 of `wbDefinitionsFO3.pas`.
pub fn wb_gmstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGMSTEDIDAfterSet from wbDefinitionsFO3.pas line 929")
}

/// Upstream `wbHeadPartsAfterSet`, line 916 of `wbDefinitionsFO3.pas`.
pub fn wb_head_parts_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbHeadPartsAfterSet from wbDefinitionsFO3.pas line 916")
}

/// Upstream `wbINFOAfterLoad`, line 2254 of `wbDefinitionsFO3.pas`.
pub fn wb_info_after_load(_a_element: &ElementRef) {
    todo!("port wbINFOAfterLoad from wbDefinitionsFO3.pas line 2254")
}

/// Upstream `wbMGEFAfterLoad`, line 2113 of `wbDefinitionsFO3.pas`.
pub fn wb_mgef_after_load(_a_element: &ElementRef) {
    todo!("port wbMGEFAfterLoad from wbDefinitionsFO3.pas line 2113")
}

/// Upstream `wbMGEFArchtypeAfterSet`, line 1096 of `wbDefinitionsFO3.pas`.
pub fn wb_mgef_archtype_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFArchtypeAfterSet from wbDefinitionsFO3.pas line 1096")
}

/// Upstream `wbMGEFAssocItemAfterSet`, line 1080 of `wbDefinitionsFO3.pas`.
pub fn wb_mgef_assoc_item_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFAssocItemAfterSet from wbDefinitionsFO3.pas line 1080")
}

/// Upstream `wbNPCAfterLoad`, line 2215 of `wbDefinitionsFO3.pas`.
pub fn wb_npc_after_load(_a_element: &ElementRef) {
    todo!("port wbNPCAfterLoad from wbDefinitionsFO3.pas line 2215")
}

/// Upstream `wbPACKAfterLoad`, line 2154 of `wbDefinitionsFO3.pas`.
pub fn wb_pack_after_load(_a_element: &ElementRef) {
    todo!("port wbPACKAfterLoad from wbDefinitionsFO3.pas line 2154")
}

/// Upstream `wbPerkDATAFunctionAfterSet`, line 1703 of `wbDefinitionsFO3.pas`.
pub fn wb_perk_data_function_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPerkDATAFunctionAfterSet from wbDefinitionsFO3.pas line 1703")
}

/// Upstream `wbPERKEntryPointAfterSet`, line 1329 of `wbDefinitionsFO3.pas`.
pub fn wb_perk_entry_point_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPERKEntryPointAfterSet from wbDefinitionsFO3.pas line 1329")
}

/// Upstream `wbPerkEPFTAfterSet`, line 1842 of `wbDefinitionsFO3.pas`.
pub fn wb_perk_epft_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPerkEPFTAfterSet from wbDefinitionsFO3.pas line 1842")
}

/// Upstream `wbREFRAfterLoad`, line 2232 of `wbDefinitionsFO3.pas`.
pub fn wb_refr_after_load(_a_element: &ElementRef) {
    todo!("port wbREFRAfterLoad from wbDefinitionsFO3.pas line 2232")
}

/// Upstream `wbWATRAfterLoad`, line 2386 of `wbDefinitionsFO3.pas`.
pub fn wb_watr_after_load(_a_element: &ElementRef) {
    todo!("port wbWATRAfterLoad from wbDefinitionsFO3.pas line 2386")
}

/// Upstream `wbWEAPAfterLoad`, line 2416 of `wbDefinitionsFO3.pas`.
pub fn wb_weap_after_load(_a_element: &ElementRef) {
    todo!("port wbWEAPAfterLoad from wbDefinitionsFO3.pas line 2416")
}
