// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsFO76.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `wbAECHTypeAfterSet`, line 2456 of `wbDefinitionsFO76.pas`.
pub fn wb_aech_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbAECHTypeAfterSet from wbDefinitionsFO76.pas line 2456")
}

/// Upstream `wbARMAAfterLoad`, line 2789 of `wbDefinitionsFO76.pas`.
pub fn wb_arma_after_load(_a_element: &ElementRef) {
    todo!("port wbARMAAfterLoad from wbDefinitionsFO76.pas line 2789")
}

/// Upstream `wbARMOAfterLoad`, line 2784 of `wbDefinitionsFO76.pas`.
pub fn wb_armo_after_load(_a_element: &ElementRef) {
    todo!("port wbARMOAfterLoad from wbDefinitionsFO76.pas line 2784")
}

/// Upstream `wbCELLCombinedRefsAfterSet`, line 3309 of `wbDefinitionsFO76.pas`.
pub fn wb_cell_combined_refs_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbCELLCombinedRefsAfterSet from wbDefinitionsFO76.pas line 3309")
}

/// Upstream `wbCELLDATAAfterSet`, line 2974 of `wbDefinitionsFO76.pas`.
pub fn wb_celldata_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbCELLDATAAfterSet from wbDefinitionsFO76.pas line 2974")
}

/// Upstream `wbCELLXCLWGetConflictPriority`, line 2940 of `wbDefinitionsFO76.pas`.
pub fn wb_cellxclw_get_conflict_priority(_a_element: ElementArg, _a_conflict_priority: &mut ConflictPriority) {
    todo!("port wbCELLXCLWGetConflictPriority from wbDefinitionsFO76.pas line 2940")
}

/// Upstream `wbConditionEventToInt`, line 1160 of `wbDefinitionsFO76.pas`.
pub fn wb_condition_event_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionEventToInt from wbDefinitionsFO76.pas line 1160")
}

/// Upstream `wbEFITAfterLoad`, line 3032 of `wbDefinitionsFO76.pas`.
pub fn wb_efit_after_load(_a_element: &ElementRef) {
    todo!("port wbEFITAfterLoad from wbDefinitionsFO76.pas line 3032")
}

/// Upstream `wbFLSTEDIDAfterSet`, line 1920 of `wbDefinitionsFO76.pas`.
pub fn wb_flstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbFLSTEDIDAfterSet from wbDefinitionsFO76.pas line 1920")
}

/// Upstream `wbFLSTLNAMIsSorted`, line 2155 of `wbDefinitionsFO76.pas`.
pub fn wb_flstlnam_is_sorted(_a_container: ElementArg) -> bool {
    todo!("port wbFLSTLNAMIsSorted from wbDefinitionsFO76.pas line 2155")
}

/// Upstream `wbGMSTEDIDAfterSet`, line 1900 of `wbDefinitionsFO76.pas`.
pub fn wb_gmstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGMSTEDIDAfterSet from wbDefinitionsFO76.pas line 1900")
}

/// Upstream `wbLLEAfterLoad`, line 3065 of `wbDefinitionsFO76.pas`.
pub fn wb_lle_after_load(_a_element: &ElementRef) {
    todo!("port wbLLEAfterLoad from wbDefinitionsFO76.pas line 3065")
}

/// Upstream `wbMGEFArchtypeAfterSet`, line 2126 of `wbDefinitionsFO76.pas`.
pub fn wb_mgef_archtype_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFArchtypeAfterSet from wbDefinitionsFO76.pas line 2126")
}

/// Upstream `wbMGEFAssocItemAfterSet`, line 2093 of `wbDefinitionsFO76.pas`.
pub fn wb_mgef_assoc_item_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFAssocItemAfterSet from wbDefinitionsFO76.pas line 2093")
}

/// Upstream `wbMGEFAV2WeightAfterSet`, line 2110 of `wbDefinitionsFO76.pas`.
pub fn wb_mgefav2_weight_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFAV2WeightAfterSet from wbDefinitionsFO76.pas line 2110")
}

/// Upstream `wbNPCAfterLoad`, line 2881 of `wbDefinitionsFO76.pas`.
pub fn wb_npc_after_load(_a_element: &ElementRef) {
    todo!("port wbNPCAfterLoad from wbDefinitionsFO76.pas line 2881")
}

/// Upstream `wbPackageDataInputValueTypeAfterSet`, line 3140 of `wbDefinitionsFO76.pas`.
pub fn wb_package_data_input_value_type_after_set(
    _a_element: &ElementRef,
    _a_old_value: &Variant,
    _a_new_value: &Variant,
) {
    todo!("port wbPackageDataInputValueTypeAfterSet from wbDefinitionsFO76.pas line 3140")
}

/// Upstream `wbREFRAfterLoad`, line 2886 of `wbDefinitionsFO76.pas`.
pub fn wb_refr_after_load(_a_element: &ElementRef) {
    todo!("port wbREFRAfterLoad from wbDefinitionsFO76.pas line 2886")
}
