// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsReflection.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `wbREFLStringToInt`, line 11 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_string_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbREFLStringToInt from wbDefinitionsReflection.pas line 11")
}

/// Upstream `wbREFLStringToStr`, line 10 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_string_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbREFLStringToStr from wbDefinitionsReflection.pas line 10")
}

/// Upstream `anonymous routine in wb_reflection`, line 258 of `wbDefinitionsReflection.pas`.
pub fn wb_reflection_anonymous_258(_a_base_ptr: DataPtr, _a_array: ElementArg) -> bool {
    todo!("port anonymous routine in wb_reflection from wbDefinitionsReflection.pas line 258")
}
