// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsSF1.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `anonymous routine in wb_links_to_node_id`, line 2283 of `wbDefinitionsSF1.pas`.
pub fn wb_links_to_node_id_anonymous_2283(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port anonymous routine in wb_links_to_node_id from wbDefinitionsSF1.pas line 2283")
}

/// Upstream `wbWwiseGuidToStr`, line 2321 of `wbDefinitionsSF1.pas`.
pub fn wb_wwise_guid_to_str(_a_value: &mut String, _a_base_ptr: DataPtr, _a_element: ElementArg, _a_type: CallbackType) {
    todo!("port wbWwiseGuidToStr from wbDefinitionsSF1.pas line 2321")
}
