// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsSF1.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use std::sync::Arc;

use xedit_core::interface::*;

/// Upstream `anonymous routine in define_sf1`, line 5247 of `wbDefinitionsSF1.pas`.
pub fn define_sf1_anonymous_5247(_a_element: &ElementRef) {
    todo!("port anonymous routine in define_sf1 from wbDefinitionsSF1.pas line 5247")
}

/// Upstream `anonymous routine in define_sf1`, line 5256 of `wbDefinitionsSF1.pas`.
pub fn define_sf1_anonymous_5256(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port anonymous routine in define_sf1 from wbDefinitionsSF1.pas line 5256")
}

/// Upstream `anonymous routine in define_sf1`, line 5271 of `wbDefinitionsSF1.pas`.
pub fn define_sf1_anonymous_5271(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port anonymous routine in define_sf1 from wbDefinitionsSF1.pas line 5271")
}

/// Upstream `anonymous routine in define_sf1`, line 5287 of `wbDefinitionsSF1.pas`.
pub fn define_sf1_anonymous_5287(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port anonymous routine in define_sf1 from wbDefinitionsSF1.pas line 5287")
}

/// Upstream `wbCELLDATAAfterSet`, line 1990 of `wbDefinitionsSF1.pas`.
pub fn wb_celldata_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbCELLDATAAfterSet from wbDefinitionsSF1.pas line 1990")
}

/// Upstream `wbConditionEventToInt`, line 923 of `wbDefinitionsSF1.pas`.
pub fn wb_condition_event_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionEventToInt from wbDefinitionsSF1.pas line 923")
}

/// Upstream `wbFLSTEDIDAfterSet`, line 1426 of `wbDefinitionsSF1.pas`.
pub fn wb_flstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbFLSTEDIDAfterSet from wbDefinitionsSF1.pas line 1426")
}

/// Upstream `wbFLSTLNAMIsSorted`, line 1761 of `wbDefinitionsSF1.pas`.
pub fn wb_flstlnam_is_sorted(_a_container: ElementArg) -> bool {
    todo!("port wbFLSTLNAMIsSorted from wbDefinitionsSF1.pas line 1761")
}

/// Upstream `wbGMSTEDIDAfterSet`, line 1406 of `wbDefinitionsSF1.pas`.
pub fn wb_gmstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGMSTEDIDAfterSet from wbDefinitionsSF1.pas line 1406")
}

/// Upstream `wbGPOFTypeAfterSetCallback`, line 1340 of `wbDefinitionsSF1.pas`.
pub fn wb_gpof_type_after_set_callback(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGPOFTypeAfterSetCallback from wbDefinitionsSF1.pas line 1340")
}

/// Upstream `wbGPOGTypeAfterSetCallback`, line 1362 of `wbDefinitionsSF1.pas`.
pub fn wb_gpog_type_after_set_callback(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGPOGTypeAfterSetCallback from wbDefinitionsSF1.pas line 1362")
}

/// Upstream `wbMGEFArchtypeAfterSet`, line 1722 of `wbDefinitionsSF1.pas`.
pub fn wb_mgef_archtype_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFArchtypeAfterSet from wbDefinitionsSF1.pas line 1722")
}

/// Upstream `wbPackageDataInputValueTypeAfterSet`, line 2049 of `wbDefinitionsSF1.pas`.
pub fn wb_package_data_input_value_type_after_set(
    _a_element: &ElementRef,
    _a_old_value: &Variant,
    _a_new_value: &Variant,
) {
    todo!("port wbPackageDataInputValueTypeAfterSet from wbDefinitionsSF1.pas line 2049")
}

/// Upstream `wbSCENTimelineTypeAfterSet`, line 1384 of `wbDefinitionsSF1.pas`.
pub fn wb_scen_timeline_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbSCENTimelineTypeAfterSet from wbDefinitionsSF1.pas line 1384")
}

/// Upstream `wbTMLMTypeAfterSet`, line 1314 of `wbDefinitionsSF1.pas`.
pub fn wb_tmlm_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbTMLMTypeAfterSet from wbDefinitionsSF1.pas line 1314")
}
