// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsTES3.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `wbEffectAreaDontShow`, line 136 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_area_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbEffectAreaDontShow from wbDefinitionsTES3.pas line 136")
}

/// Upstream `wbEffectAttributeDontShow`, line 146 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_attribute_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbEffectAttributeDontShow from wbDefinitionsTES3.pas line 146")
}

/// Upstream `wbEffectDurationDontShow`, line 154 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_duration_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbEffectDurationDontShow from wbDefinitionsTES3.pas line 154")
}

/// Upstream `wbEffectMagnitudeDontShow`, line 237 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_magnitude_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbEffectMagnitudeDontShow from wbDefinitionsTES3.pas line 237")
}

/// Upstream `wbEffectRangeAfterLoad`, line 170 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_range_after_load(_a_element: &ElementRef) {
    todo!("port wbEffectRangeAfterLoad from wbDefinitionsTES3.pas line 170")
}

/// Upstream `wbEffectRangeAfterSet`, line 186 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_range_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbEffectRangeAfterSet from wbDefinitionsTES3.pas line 186")
}

/// Upstream `wbEffectRangeDecider`, line 212 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_range_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbEffectRangeDecider from wbDefinitionsTES3.pas line 212")
}

/// Upstream `wbEffectRangeDontShow`, line 225 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_range_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbEffectRangeDontShow from wbDefinitionsTES3.pas line 225")
}

/// Upstream `wbEffectSkillDontShow`, line 162 of `wbDefinitionsTES3.pas`.
pub fn wb_effect_skill_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbEffectSkillDontShow from wbDefinitionsTES3.pas line 162")
}

/// Upstream `wbForwardForReal`, line 261 of `wbDefinitionsTES3.pas`.
pub fn wb_forward_for_real(_a_element: &ElementRef) {
    todo!("port wbForwardForReal from wbDefinitionsTES3.pas line 261")
}
