// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsTES4.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `wbCalcPGRRSize`, line 620 of `wbDefinitionsTES4.pas`.
pub fn wb_calc_pgrr_size(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port wbCalcPGRRSize from wbDefinitionsTES4.pas line 620")
}

/// Upstream `wbCELLAfterLoad`, line 644 of `wbDefinitionsTES4.pas`.
pub fn wb_cell_after_load(_a_element: &ElementRef) {
    todo!("port wbCELLAfterLoad from wbDefinitionsTES4.pas line 644")
}

/// Upstream `wbConditionFunctionToInt`, line 376 of `wbDefinitionsTES4.pas`.
pub fn wb_condition_function_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionFunctionToInt from wbDefinitionsTES4.pas line 376")
}

/// Upstream `wbConditionFunctionToStr`, line 341 of `wbDefinitionsTES4.pas`.
pub fn wb_condition_function_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionFunctionToStr from wbDefinitionsTES4.pas line 341")
}

/// Upstream `wbConditionParam1Decider`, line 386 of `wbDefinitionsTES4.pas`.
pub fn wb_condition_param1_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionParam1Decider from wbDefinitionsTES4.pas line 386")
}

/// Upstream `wbConditionParam2Decider`, line 399 of `wbDefinitionsTES4.pas`.
pub fn wb_condition_param2_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionParam2Decider from wbDefinitionsTES4.pas line 399")
}

/// Upstream `wbConditionQuestStageToStr`, line 412 of `wbDefinitionsTES4.pas`.
pub fn wb_condition_quest_stage_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionQuestStageToStr from wbDefinitionsTES4.pas line 412")
}

/// Upstream `wbConditionVariableNameToInt`, line 571 of `wbDefinitionsTES4.pas`.
pub fn wb_condition_variable_name_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionVariableNameToInt from wbDefinitionsTES4.pas line 571")
}

/// Upstream `wbConditionVariableNameToStr`, line 486 of `wbDefinitionsTES4.pas`.
pub fn wb_condition_variable_name_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionVariableNameToStr from wbDefinitionsTES4.pas line 486")
}

/// Upstream `wbEFITAfterLoad`, line 687 of `wbDefinitionsTES4.pas`.
pub fn wb_efit_after_load(_a_element: &ElementRef) {
    todo!("port wbEFITAfterLoad from wbDefinitionsTES4.pas line 687")
}

/// Upstream `wbIdleAnam`, line 749 of `wbDefinitionsTES4.pas`.
pub fn wb_idle_anam(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbIdleAnam from wbDefinitionsTES4.pas line 749")
}

/// Upstream `wbLVLAfterLoad`, line 782 of `wbDefinitionsTES4.pas`.
pub fn wb_lvl_after_load(_a_element: &ElementRef) {
    todo!("port wbLVLAfterLoad from wbDefinitionsTES4.pas line 782")
}

/// Upstream `wbMGEFAfterLoad`, line 805 of `wbDefinitionsTES4.pas`.
pub fn wb_mgef_after_load(_a_element: &ElementRef) {
    todo!("port wbMGEFAfterLoad from wbDefinitionsTES4.pas line 805")
}

/// Upstream `wbMGEFFAssocItemDecider`, line 845 of `wbDefinitionsTES4.pas`.
pub fn wb_mgeff_assoc_item_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbMGEFFAssocItemDecider from wbDefinitionsTES4.pas line 845")
}

/// Upstream `wbMISCActorValueDecider`, line 865 of `wbDefinitionsTES4.pas`.
pub fn wb_misc_actor_value_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbMISCActorValueDecider from wbDefinitionsTES4.pas line 865")
}

/// Upstream `wbPACKPKDTDecider`, line 894 of `wbDefinitionsTES4.pas`.
pub fn wb_packpkdt_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbPACKPKDTDecider from wbDefinitionsTES4.pas line 894")
}

/// Upstream `wbPGRDAfterLoad`, line 908 of `wbDefinitionsTES4.pas`.
pub fn wb_pgrd_after_load(_a_element: &ElementRef) {
    todo!("port wbPGRDAfterLoad from wbDefinitionsTES4.pas line 908")
}

/// Upstream `wbPGRIPointerAfterLoad`, line 969 of `wbDefinitionsTES4.pas`.
pub fn wb_pgri_pointer_after_load(_a_element: &ElementRef) {
    todo!("port wbPGRIPointerAfterLoad from wbDefinitionsTES4.pas line 969")
}

/// Upstream `wbREFRAfterLoad`, line 999 of `wbDefinitionsTES4.pas`.
pub fn wb_refr_after_load(_a_element: &ElementRef) {
    todo!("port wbREFRAfterLoad from wbDefinitionsTES4.pas line 999")
}

/// Upstream `wbXLOCFillerDecider`, line 1029 of `wbDefinitionsTES4.pas`.
pub fn wb_xloc_filler_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbXLOCFillerDecider from wbDefinitionsTES4.pas line 1029")
}
