// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsTES5.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `anonymous routine in define_tes5`, line 4890 of `wbDefinitionsTES5.pas`.
pub fn define_tes5_anonymous_4890(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port anonymous routine in define_tes5 from wbDefinitionsTES5.pas line 4890")
}

/// Upstream `anonymous routine in define_tes5`, line 6171 of `wbDefinitionsTES5.pas`.
pub fn define_tes5_anonymous_6171(_a_main_record: &MainRecordRef, _a_index_keys: &mut IndexKeys) {
    todo!("port anonymous routine in define_tes5 from wbDefinitionsTES5.pas line 6171")
}

/// Upstream `anonymous routine in define_tes5`, line 6207 of `wbDefinitionsTES5.pas`.
pub fn define_tes5_anonymous_6207(_a_element: ElementArg) -> bool {
    todo!("port anonymous routine in define_tes5 from wbDefinitionsTES5.pas line 6207")
}

/// Upstream `anonymous routine in define_tes5`, line 7697 of `wbDefinitionsTES5.pas`.
pub fn define_tes5_anonymous_7697(_a_main_record: &MainRecordRef, _a_index_keys: &mut IndexKeys) {
    todo!("port anonymous routine in define_tes5 from wbDefinitionsTES5.pas line 7697")
}

/// Upstream `anonymous routine in define_tes5`, line 9854 of `wbDefinitionsTES5.pas`.
pub fn define_tes5_anonymous_9854(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port anonymous routine in define_tes5 from wbDefinitionsTES5.pas line 9854")
}

/// Upstream `wbACBSLevelDecider`, line 266 of `wbDefinitionsTES5.pas`.
pub fn wb_acbs_level_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbACBSLevelDecider from wbDefinitionsTES5.pas line 266")
}

/// Upstream `wbACBSLevelMultAfterLoad`, line 39 of `wbDefinitionsTES5.pas`.
pub fn wb_acbs_level_mult_after_load(_a_element: &ElementRef) {
    todo!("port wbACBSLevelMultAfterLoad from wbDefinitionsTES5.pas line 39")
}

/// Upstream `wbACBSLevelMultAfterSet`, line 54 of `wbDefinitionsTES5.pas`.
pub fn wb_acbs_level_mult_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbACBSLevelMultAfterSet from wbDefinitionsTES5.pas line 54")
}

/// Upstream `wbAliasToInt`, line 177 of `wbDefinitionsTES5.pas`.
pub fn wb_alias_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbAliasToInt from wbDefinitionsTES5.pas line 177")
}

/// Upstream `wbARMAAfterLoad`, line 1643 of `wbDefinitionsTES5.pas`.
pub fn wb_arma_after_load(_a_element: &ElementRef) {
    todo!("port wbARMAAfterLoad from wbDefinitionsTES5.pas line 1643")
}

/// Upstream `wbARMOAfterLoad`, line 1638 of `wbDefinitionsTES5.pas`.
pub fn wb_armo_after_load(_a_element: &ElementRef) {
    todo!("port wbARMOAfterLoad from wbDefinitionsTES5.pas line 1638")
}

/// Upstream `wbAVIFSkillAfterLoad`, line 40 of `wbDefinitionsTES5.pas`.
pub fn wb_avif_skill_after_load(_a_element: &ElementRef) {
    todo!("port wbAVIFSkillAfterLoad from wbDefinitionsTES5.pas line 40")
}

/// Upstream `wbBOOKDataFlagsAfterSet`, line 55 of `wbDefinitionsTES5.pas`.
pub fn wb_book_data_flags_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbBOOKDataFlagsAfterSet from wbDefinitionsTES5.pas line 55")
}

/// Upstream `wbBOOKTeachesDecider`, line 1321 of `wbDefinitionsTES5.pas`.
pub fn wb_book_teaches_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbBOOKTeachesDecider from wbDefinitionsTES5.pas line 1321")
}

/// Upstream `wbBookTeachesDontSHow`, line 94 of `wbDefinitionsTES5.pas`.
pub fn wb_book_teaches_dont_s_how(_a_element: ElementArg) -> bool {
    todo!("port wbBookTeachesDontSHow from wbDefinitionsTES5.pas line 94")
}

/// Upstream `wbCELLAfterLoad`, line 1773 of `wbDefinitionsTES5.pas`.
pub fn wb_cell_after_load(_a_element: &ElementRef) {
    todo!("port wbCELLAfterLoad from wbDefinitionsTES5.pas line 1773")
}

/// Upstream `wbCellExteriorDontShow`, line 96 of `wbDefinitionsTES5.pas`.
pub fn wb_cell_exterior_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbCellExteriorDontShow from wbDefinitionsTES5.pas line 96")
}

/// Upstream `wbCellLightingIsRemovable`, line 136 of `wbDefinitionsTES5.pas`.
pub fn wb_cell_lighting_is_removable(_a_element: ElementArg) -> bool {
    todo!("port wbCellLightingIsRemovable from wbDefinitionsTES5.pas line 136")
}

/// Upstream `wbCELLDATAAfterSet`, line 1757 of `wbDefinitionsTES5.pas`.
pub fn wb_celldata_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbCELLDATAAfterSet from wbDefinitionsTES5.pas line 1757")
}

/// Upstream `wbCELLXCLWGetConflictPriority`, line 1722 of `wbDefinitionsTES5.pas`.
pub fn wb_cellxclw_get_conflict_priority(_a_element: ElementArg, _a_conflict_priority: &mut ConflictPriority) {
    todo!("port wbCELLXCLWGetConflictPriority from wbDefinitionsTES5.pas line 1722")
}

/// Upstream `wbClmtMoonsPhaseLength`, line 200 of `wbDefinitionsTES5.pas`.
pub fn wb_clmt_moons_phase_length(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbClmtMoonsPhaseLength from wbDefinitionsTES5.pas line 200")
}

/// Upstream `wbClmtTime`, line 201 of `wbDefinitionsTES5.pas`.
pub fn wb_clmt_time(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbClmtTime from wbDefinitionsTES5.pas line 201")
}

/// Upstream `wbCOEDOwnerDecider`, line 267 of `wbDefinitionsTES5.pas`.
pub fn wb_coed_owner_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbCOEDOwnerDecider from wbDefinitionsTES5.pas line 267")
}

/// Upstream `wbConditionAliasToStr`, line 202 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_alias_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionAliasToStr from wbDefinitionsTES5.pas line 202")
}

/// Upstream `wbConditionCompValueDecider`, line 268 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_comp_value_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionCompValueDecider from wbDefinitionsTES5.pas line 268")
}

/// Upstream `wbConditionEventToInt`, line 772 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_event_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionEventToInt from wbDefinitionsTES5.pas line 772")
}

/// Upstream `wbConditionEventToStr`, line 732 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_event_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionEventToStr from wbDefinitionsTES5.pas line 732")
}

/// Upstream `wbConditionFunctionToInt`, line 683 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_function_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionFunctionToInt from wbDefinitionsTES5.pas line 683")
}

/// Upstream `wbConditionFunctionToStr`, line 649 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_function_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionFunctionToStr from wbDefinitionsTES5.pas line 649")
}

/// Upstream `wbConditionOwnerToStr`, line 237 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_owner_to_str(
    _a_value: &mut String,
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
    _a_type: CallbackType,
) {
    todo!("port wbConditionOwnerToStr from wbDefinitionsTES5.pas line 237")
}

/// Upstream `wbConditionParam1Decider`, line 692 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_param1_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionParam1Decider from wbDefinitionsTES5.pas line 692")
}

/// Upstream `wbConditionParam2Decider`, line 712 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_param2_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionParam2Decider from wbDefinitionsTES5.pas line 712")
}

/// Upstream `wbConditionParam3Decider`, line 269 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_param3_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionParam3Decider from wbDefinitionsTES5.pas line 269")
}

/// Upstream `wbConditionQuestStageToStr`, line 789 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_quest_stage_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionQuestStageToStr from wbDefinitionsTES5.pas line 789")
}

/// Upstream `wbConditionReferenceDecider`, line 270 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_reference_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionReferenceDecider from wbDefinitionsTES5.pas line 270")
}

/// Upstream `wbConditionRunOnAfterSet`, line 57 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_run_on_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbConditionRunOnAfterSet from wbDefinitionsTES5.pas line 57")
}

/// Upstream `wbConditionStringToInt`, line 178 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_string_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionStringToInt from wbDefinitionsTES5.pas line 178")
}

/// Upstream `wbConditionStringToStr`, line 203 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_string_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionStringToStr from wbDefinitionsTES5.pas line 203")
}

/// Upstream `wbConditionToStr`, line 236 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_to_str(_a_value: &mut String, _a_base_ptr: DataPtr, _a_element: ElementArg, _a_type: CallbackType) {
    todo!("port wbConditionToStr from wbDefinitionsTES5.pas line 236")
}

/// Upstream `wbConditionTypeAfterSet`, line 56 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbConditionTypeAfterSet from wbDefinitionsTES5.pas line 56")
}

/// Upstream `wbConditionTypeToInt`, line 179 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_type_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionTypeToInt from wbDefinitionsTES5.pas line 179")
}

/// Upstream `wbConditionTypeToStr`, line 204 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_type_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbConditionTypeToStr from wbDefinitionsTES5.pas line 204")
}

/// Upstream `wbConditionVATSValueParamDecider`, line 864 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_vats_value_param_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbConditionVATSValueParamDecider from wbDefinitionsTES5.pas line 864")
}

/// Upstream `wbDialogueTextAfterLoad`, line 41 of `wbDefinitionsTES5.pas`.
pub fn wb_dialogue_text_after_load(_a_element: &ElementRef) {
    todo!("port wbDialogueTextAfterLoad from wbDefinitionsTES5.pas line 41")
}

/// Upstream `wbDialogueTextAfterSet`, line 58 of `wbDefinitionsTES5.pas`.
pub fn wb_dialogue_text_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbDialogueTextAfterSet from wbDefinitionsTES5.pas line 58")
}

/// Upstream `wbDOBJObjectsAfterLoad`, line 42 of `wbDefinitionsTES5.pas`.
pub fn wb_dobj_objects_after_load(_a_element: &ElementRef) {
    todo!("port wbDOBJObjectsAfterLoad from wbDefinitionsTES5.pas line 42")
}

/// Upstream `wbEdgeLinksTo0`, line 151 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_links_to0(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbEdgeLinksTo0 from wbDefinitionsTES5.pas line 151")
}

/// Upstream `wbEdgeLinksTo1`, line 152 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_links_to1(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbEdgeLinksTo1 from wbDefinitionsTES5.pas line 152")
}

/// Upstream `wbEdgeLinksTo2`, line 153 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_links_to2(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbEdgeLinksTo2 from wbDefinitionsTES5.pas line 153")
}

/// Upstream `wbEdgeToInt0`, line 181 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_to_int0(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbEdgeToInt0 from wbDefinitionsTES5.pas line 181")
}

/// Upstream `wbEdgeToInt1`, line 182 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_to_int1(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbEdgeToInt1 from wbDefinitionsTES5.pas line 182")
}

/// Upstream `wbEdgeToInt2`, line 183 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_to_int2(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbEdgeToInt2 from wbDefinitionsTES5.pas line 183")
}

/// Upstream `wbEdgeToStr0`, line 205 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_to_str0(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbEdgeToStr0 from wbDefinitionsTES5.pas line 205")
}

/// Upstream `wbEdgeToStr1`, line 206 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_to_str1(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbEdgeToStr1 from wbDefinitionsTES5.pas line 206")
}

/// Upstream `wbEdgeToStr2`, line 207 of `wbDefinitionsTES5.pas`.
pub fn wb_edge_to_str2(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbEdgeToStr2 from wbDefinitionsTES5.pas line 207")
}

/// Upstream `wbEFITAfterLoad`, line 1860 of `wbDefinitionsTES5.pas`.
pub fn wb_efit_after_load(_a_element: &ElementRef) {
    todo!("port wbEFITAfterLoad from wbDefinitionsTES5.pas line 1860")
}

/// Upstream `wbEPFDActorValueToInt`, line 907 of `wbDefinitionsTES5.pas`.
pub fn wb_epfd_actor_value_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbEPFDActorValueToInt from wbDefinitionsTES5.pas line 907")
}

/// Upstream `wbEPFDActorValueToStr`, line 889 of `wbDefinitionsTES5.pas`.
pub fn wb_epfd_actor_value_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbEPFDActorValueToStr from wbDefinitionsTES5.pas line 889")
}

/// Upstream `wbEPFDDecider`, line 1278 of `wbDefinitionsTES5.pas`.
pub fn wb_epfd_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbEPFDDecider from wbDefinitionsTES5.pas line 1278")
}

/// Upstream `wbFlagNavmeshBoundingBoxDontSHow`, line 85 of `wbDefinitionsTES5.pas`.
pub fn wb_flag_navmesh_bounding_box_dont_s_how(_a_element: ElementArg) -> bool {
    todo!("port wbFlagNavmeshBoundingBoxDontSHow from wbDefinitionsTES5.pas line 85")
}

/// Upstream `wbFlagNavmeshFilterDontSHow`, line 84 of `wbDefinitionsTES5.pas`.
pub fn wb_flag_navmesh_filter_dont_s_how(_a_element: ElementArg) -> bool {
    todo!("port wbFlagNavmeshFilterDontSHow from wbDefinitionsTES5.pas line 84")
}

/// Upstream `wbFlagNavmeshGroundDontSHow`, line 88 of `wbDefinitionsTES5.pas`.
pub fn wb_flag_navmesh_ground_dont_s_how(_a_element: ElementArg) -> bool {
    todo!("port wbFlagNavmeshGroundDontSHow from wbDefinitionsTES5.pas line 88")
}

/// Upstream `wbFlagPartialFormDontShow`, line 89 of `wbDefinitionsTES5.pas`.
pub fn wb_flag_partial_form_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbFlagPartialFormDontShow from wbDefinitionsTES5.pas line 89")
}

/// Upstream `wbFlagREFRInteriorDontShow`, line 83 of `wbDefinitionsTES5.pas`.
pub fn wb_flag_refr_interior_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbFlagREFRInteriorDontShow from wbDefinitionsTES5.pas line 83")
}

/// Upstream `wbFlagREFRSkyMarkerDontShow`, line 90 of `wbDefinitionsTES5.pas`.
pub fn wb_flag_refr_sky_marker_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbFlagREFRSkyMarkerDontShow from wbDefinitionsTES5.pas line 90")
}

/// Upstream `wbFLSTEDIDAfterSet`, line 1041 of `wbDefinitionsTES5.pas`.
pub fn wb_flstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbFLSTEDIDAfterSet from wbDefinitionsTES5.pas line 1041")
}

/// Upstream `wbFLSTLNAMIsSorted`, line 1239 of `wbDefinitionsTES5.pas`.
pub fn wb_flstlnam_is_sorted(_a_container: ElementArg) -> bool {
    todo!("port wbFLSTLNAMIsSorted from wbDefinitionsTES5.pas line 1239")
}

/// Upstream `wbGMSTEDIDAfterSet`, line 1021 of `wbDefinitionsTES5.pas`.
pub fn wb_gmstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGMSTEDIDAfterSet from wbDefinitionsTES5.pas line 1021")
}

/// Upstream `wbHideFFFF`, line 210 of `wbDefinitionsTES5.pas`.
pub fn wb_hide_ffff(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbHideFFFF from wbDefinitionsTES5.pas line 210")
}

/// Upstream `wbINFOPNAMAfterSet`, line 997 of `wbDefinitionsTES5.pas`.
pub fn wb_infopnam_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbINFOPNAMAfterSet from wbDefinitionsTES5.pas line 997")
}

/// Upstream `wbLCTNCellDontShow`, line 105 of `wbDefinitionsTES5.pas`.
pub fn wb_lctn_cell_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbLCTNCellDontShow from wbDefinitionsTES5.pas line 105")
}

/// Upstream `wbLIGHCarryDontShow`, line 99 of `wbDefinitionsTES5.pas`.
pub fn wb_ligh_carry_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbLIGHCarryDontShow from wbDefinitionsTES5.pas line 99")
}

/// Upstream `wbLIGHDataFlagsAfterSet`, line 2176 of `wbDefinitionsTES5.pas`.
pub fn wb_ligh_data_flags_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbLIGHDataFlagsAfterSet from wbDefinitionsTES5.pas line 2176")
}

/// Upstream `wbLIGHFalloffDontShow`, line 100 of `wbDefinitionsTES5.pas`.
pub fn wb_ligh_falloff_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbLIGHFalloffDontShow from wbDefinitionsTES5.pas line 100")
}

/// Upstream `wbLIGHFlickerDontShow`, line 101 of `wbDefinitionsTES5.pas`.
pub fn wb_ligh_flicker_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbLIGHFlickerDontShow from wbDefinitionsTES5.pas line 101")
}

/// Upstream `wbLIGHShadowSpotDontShow`, line 102 of `wbDefinitionsTES5.pas`.
pub fn wb_ligh_shadow_spot_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbLIGHShadowSpotDontShow from wbDefinitionsTES5.pas line 102")
}

/// Upstream `wbMESGAfterLoad`, line 43 of `wbDefinitionsTES5.pas`.
pub fn wb_mesg_after_load(_a_element: &ElementRef) {
    todo!("port wbMESGAfterLoad from wbDefinitionsTES5.pas line 43")
}

/// Upstream `wbMESGDNAMAfterSet`, line 61 of `wbDefinitionsTES5.pas`.
pub fn wb_mesgdnam_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMESGDNAMAfterSet from wbDefinitionsTES5.pas line 61")
}

/// Upstream `wbMESGTNAMDontShow`, line 103 of `wbDefinitionsTES5.pas`.
pub fn wb_mesgtnam_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbMESGTNAMDontShow from wbDefinitionsTES5.pas line 103")
}

/// Upstream `wbMessageTNAMIsRemovable`, line 137 of `wbDefinitionsTES5.pas`.
pub fn wb_message_tnam_is_removable(_a_element: ElementArg) -> bool {
    todo!("port wbMessageTNAMIsRemovable from wbDefinitionsTES5.pas line 137")
}

/// Upstream `wbMGEFArchtypeAfterSet`, line 1210 of `wbDefinitionsTES5.pas`.
pub fn wb_mgef_archtype_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFArchtypeAfterSet from wbDefinitionsTES5.pas line 1210")
}

/// Upstream `wbMGEFAssocItemAfterSet`, line 1177 of `wbDefinitionsTES5.pas`.
pub fn wb_mgef_assoc_item_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFAssocItemAfterSet from wbDefinitionsTES5.pas line 1177")
}

/// Upstream `wbMGEFAssocItemDecider`, line 1135 of `wbDefinitionsTES5.pas`.
pub fn wb_mgef_assoc_item_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbMGEFAssocItemDecider from wbDefinitionsTES5.pas line 1135")
}

/// Upstream `wbMGEFAV2WeightAfterSet`, line 1194 of `wbDefinitionsTES5.pas`.
pub fn wb_mgefav2_weight_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFAV2WeightAfterSet from wbDefinitionsTES5.pas line 1194")
}

/// Upstream `wbNAVIIslandDataDecider`, line 275 of `wbDefinitionsTES5.pas`.
pub fn wb_navi_island_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbNAVIIslandDataDecider from wbDefinitionsTES5.pas line 275")
}

/// Upstream `wbNAVIParentDecider`, line 276 of `wbDefinitionsTES5.pas`.
pub fn wb_navi_parent_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbNAVIParentDecider from wbDefinitionsTES5.pas line 276")
}

/// Upstream `wbNavmeshGridCounter`, line 74 of `wbDefinitionsTES5.pas`.
pub fn wb_navmesh_grid_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port wbNavmeshGridCounter from wbDefinitionsTES5.pas line 74")
}

/// Upstream `wbNPCPackageToStr`, line 242 of `wbDefinitionsTES5.pas`.
pub fn wb_npc_package_to_str(
    _a_value: &mut String,
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
    _a_type: CallbackType,
) {
    todo!("port wbNPCPackageToStr from wbDefinitionsTES5.pas line 242")
}

/// Upstream `wbNVNMParentDecider`, line 277 of `wbDefinitionsTES5.pas`.
pub fn wb_nvnm_parent_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbNVNMParentDecider from wbDefinitionsTES5.pas line 277")
}

/// Upstream `wbPACKDateAfterLoad`, line 44 of `wbDefinitionsTES5.pas`.
pub fn wb_pack_date_after_load(_a_element: &ElementRef) {
    todo!("port wbPACKDateAfterLoad from wbDefinitionsTES5.pas line 44")
}

/// Upstream `wbPACKDateAfterSet`, line 62 of `wbDefinitionsTES5.pas`.
pub fn wb_pack_date_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPACKDateAfterSet from wbDefinitionsTES5.pas line 62")
}

/// Upstream `wbPACKTemplateDontShow`, line 106 of `wbDefinitionsTES5.pas`.
pub fn wb_pack_template_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbPACKTemplateDontShow from wbDefinitionsTES5.pas line 106")
}

/// Upstream `wbPackageDataInputValueTypeAfterSet`, line 1931 of `wbDefinitionsTES5.pas`.
pub fn wb_package_data_input_value_type_after_set(
    _a_element: &ElementRef,
    _a_old_value: &Variant,
    _a_new_value: &Variant,
) {
    todo!("port wbPackageDataInputValueTypeAfterSet from wbDefinitionsTES5.pas line 1931")
}

/// Upstream `wbPackageLocationAliasToStr`, line 216 of `wbDefinitionsTES5.pas`.
pub fn wb_package_location_alias_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbPackageLocationAliasToStr from wbDefinitionsTES5.pas line 216")
}

/// Upstream `wbPackagePSDTMonthValueToInt`, line 193 of `wbDefinitionsTES5.pas`.
pub fn wb_package_psdt_month_value_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbPackagePSDTMonthValueToInt from wbDefinitionsTES5.pas line 193")
}

/// Upstream `wbPackagePSDTMonthValueToStr`, line 228 of `wbDefinitionsTES5.pas`.
pub fn wb_package_psdt_month_value_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbPackagePSDTMonthValueToStr from wbDefinitionsTES5.pas line 228")
}

/// Upstream `wbPerkDATADecider`, line 1259 of `wbDefinitionsTES5.pas`.
pub fn wb_perk_data_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbPerkDATADecider from wbDefinitionsTES5.pas line 1259")
}

/// Upstream `wbPerkDATAQuestStageToStr`, line 917 of `wbDefinitionsTES5.pas`.
pub fn wb_perk_data_quest_stage_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbPerkDATAQuestStageToStr from wbDefinitionsTES5.pas line 917")
}

/// Upstream `wbPERKPRKETypeAfterSet`, line 63 of `wbDefinitionsTES5.pas`.
pub fn wb_perkprke_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbPERKPRKETypeAfterSet from wbDefinitionsTES5.pas line 63")
}

/// Upstream `wbPubPackCNAMDecider`, line 1893 of `wbDefinitionsTES5.pas`.
pub fn wb_pub_pack_cnam_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbPubPackCNAMDecider from wbDefinitionsTES5.pas line 1893")
}

/// Upstream `wbQuestAliasToStr`, line 217 of `wbDefinitionsTES5.pas`.
pub fn wb_quest_alias_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbQuestAliasToStr from wbDefinitionsTES5.pas line 217")
}

/// Upstream `wbQuestExternalAliasToStr`, line 218 of `wbDefinitionsTES5.pas`.
pub fn wb_quest_external_alias_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbQuestExternalAliasToStr from wbDefinitionsTES5.pas line 218")
}

/// Upstream `wbQuestStageToInt`, line 180 of `wbDefinitionsTES5.pas`.
pub fn wb_quest_stage_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbQuestStageToInt from wbDefinitionsTES5.pas line 180")
}

/// Upstream `wbQUSTAliasToStr`, line 244 of `wbDefinitionsTES5.pas`.
pub fn wb_qust_alias_to_str(
    _a_value: &mut String,
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
    _a_type: CallbackType,
) {
    todo!("port wbQUSTAliasToStr from wbDefinitionsTES5.pas line 244")
}

/// Upstream `wbQUSTEventToStr`, line 245 of `wbDefinitionsTES5.pas`.
pub fn wb_qust_event_to_str(
    _a_value: &mut String,
    _a_base_ptr: DataPtr,
    _a_element: ElementArg,
    _a_type: CallbackType,
) {
    todo!("port wbQUSTEventToStr from wbDefinitionsTES5.pas line 245")
}

/// Upstream `wbRACEAfterLoad`, line 1681 of `wbDefinitionsTES5.pas`.
pub fn wb_race_after_load(_a_element: &ElementRef) {
    todo!("port wbRACEAfterLoad from wbDefinitionsTES5.pas line 1681")
}

/// Upstream `wbREFRAfterLoad`, line 1660 of `wbDefinitionsTES5.pas`.
pub fn wb_refr_after_load(_a_element: &ElementRef) {
    todo!("port wbREFRAfterLoad from wbDefinitionsTES5.pas line 1660")
}

/// Upstream `wbREFRNavmeshTriangleToStr`, line 219 of `wbDefinitionsTES5.pas`.
pub fn wb_refr_navmesh_triangle_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbREFRNavmeshTriangleToStr from wbDefinitionsTES5.pas line 219")
}

/// Upstream `wbREFRRecordFlagsDecider`, line 1950 of `wbDefinitionsTES5.pas`.
pub fn wb_refr_record_flags_decider(_a_element: ElementArg) -> i32 {
    todo!("port wbREFRRecordFlagsDecider from wbDefinitionsTES5.pas line 1950")
}

/// Upstream `wbREGNGrassDontShow`, line 107 of `wbDefinitionsTES5.pas`.
pub fn wb_regn_grass_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbREGNGrassDontShow from wbDefinitionsTES5.pas line 107")
}

/// Upstream `wbREGNLandDontShow`, line 109 of `wbDefinitionsTES5.pas`.
pub fn wb_regn_land_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbREGNLandDontShow from wbDefinitionsTES5.pas line 109")
}

/// Upstream `wbREGNMapDontShow`, line 110 of `wbDefinitionsTES5.pas`.
pub fn wb_regn_map_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbREGNMapDontShow from wbDefinitionsTES5.pas line 110")
}

/// Upstream `wbREGNObjectsDontShow`, line 111 of `wbDefinitionsTES5.pas`.
pub fn wb_regn_objects_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbREGNObjectsDontShow from wbDefinitionsTES5.pas line 111")
}

/// Upstream `wbREGNWeatherDontShow`, line 113 of `wbDefinitionsTES5.pas`.
pub fn wb_regn_weather_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbREGNWeatherDontShow from wbDefinitionsTES5.pas line 113")
}

/// Upstream `wbSCENAliasLinksTo`, line 156 of `wbDefinitionsTES5.pas`.
pub fn wb_scen_alias_links_to(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbSCENAliasLinksTo from wbDefinitionsTES5.pas line 156")
}

/// Upstream `wbSceneActionTypeAfterSet`, line 65 of `wbDefinitionsTES5.pas`.
pub fn wb_scene_action_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbSceneActionTypeAfterSet from wbDefinitionsTES5.pas line 65")
}

/// Upstream `wbSceneAliasToStr`, line 221 of `wbDefinitionsTES5.pas`.
pub fn wb_scene_alias_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbSceneAliasToStr from wbDefinitionsTES5.pas line 221")
}

/// Upstream `wbScriptFragmentsInfoCounter`, line 75 of `wbDefinitionsTES5.pas`.
pub fn wb_script_fragments_info_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port wbScriptFragmentsInfoCounter from wbDefinitionsTES5.pas line 75")
}

/// Upstream `wbScriptFragmentsPackCounter`, line 76 of `wbDefinitionsTES5.pas`.
pub fn wb_script_fragments_pack_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port wbScriptFragmentsPackCounter from wbDefinitionsTES5.pas line 76")
}

/// Upstream `wbScriptFragmentsSceneCounter`, line 77 of `wbDefinitionsTES5.pas`.
pub fn wb_script_fragments_scene_counter(_a_base_ptr: DataPtr, _a_element: ElementArg) -> u32 {
    todo!("port wbScriptFragmentsSceneCounter from wbDefinitionsTES5.pas line 77")
}

/// Upstream `wbScriptObjFormatDecider`, line 280 of `wbDefinitionsTES5.pas`.
pub fn wb_script_obj_format_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbScriptObjFormatDecider from wbDefinitionsTES5.pas line 280")
}

/// Upstream `wbScriptObjectAliasLinksTo`, line 157 of `wbDefinitionsTES5.pas`.
pub fn wb_script_object_alias_links_to(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbScriptObjectAliasLinksTo from wbDefinitionsTES5.pas line 157")
}

/// Upstream `wbScriptObjectAliasToStr`, line 222 of `wbDefinitionsTES5.pas`.
pub fn wb_script_object_alias_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbScriptObjectAliasToStr from wbDefinitionsTES5.pas line 222")
}

/// Upstream `wbScriptPropertyDecider`, line 1299 of `wbDefinitionsTES5.pas`.
pub fn wb_script_property_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbScriptPropertyDecider from wbDefinitionsTES5.pas line 1299")
}

/// Upstream `wbScriptPropertyTypeAfterSet`, line 67 of `wbDefinitionsTES5.pas`.
pub fn wb_script_property_type_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbScriptPropertyTypeAfterSet from wbDefinitionsTES5.pas line 67")
}

/// Upstream `wbScrollCastAfterLoad`, line 48 of `wbDefinitionsTES5.pas`.
pub fn wb_scroll_cast_after_load(_a_element: &ElementRef) {
    todo!("port wbScrollCastAfterLoad from wbDefinitionsTES5.pas line 48")
}

/// Upstream `wbScrollTypeAfterLoad`, line 49 of `wbDefinitionsTES5.pas`.
pub fn wb_scroll_type_after_load(_a_element: &ElementRef) {
    todo!("port wbScrollTypeAfterLoad from wbDefinitionsTES5.pas line 49")
}

/// Upstream `wbStrToInt`, line 187 of `wbDefinitionsTES5.pas`.
pub fn wb_str_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbStrToInt from wbDefinitionsTES5.pas line 187")
}

/// Upstream `wbStringToInt`, line 992 of `wbDefinitionsTES5.pas`.
pub fn wb_string_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbStringToInt from wbDefinitionsTES5.pas line 992")
}

/// Upstream `wbTintLayerToStr`, line 2023 of `wbDefinitionsTES5.pas`.
pub fn wb_tint_layer_to_str(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbTintLayerToStr from wbDefinitionsTES5.pas line 2023")
}

/// Upstream `wbTriangleLinksTo`, line 158 of `wbDefinitionsTES5.pas`.
pub fn wb_triangle_links_to(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbTriangleLinksTo from wbDefinitionsTES5.pas line 158")
}

/// Upstream `wbTypeDecider`, line 1913 of `wbDefinitionsTES5.pas`.
pub fn wb_type_decider(_a_base_ptr: DataPtr, _a_element: ElementArg) -> i32 {
    todo!("port wbTypeDecider from wbDefinitionsTES5.pas line 1913")
}

/// Upstream `wbUpdateSameParentUnions`, line 68 of `wbDefinitionsTES5.pas`.
pub fn wb_update_same_parent_unions(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbUpdateSameParentUnions from wbDefinitionsTES5.pas line 68")
}

/// Upstream `wbVertexLinksTo`, line 159 of `wbDefinitionsTES5.pas`.
pub fn wb_vertex_links_to(_a_element: ElementArg) -> Option<ElementRef> {
    todo!("port wbVertexLinksTo from wbDefinitionsTES5.pas line 159")
}

/// Upstream `wbVertexToInt0`, line 189 of `wbDefinitionsTES5.pas`.
pub fn wb_vertex_to_int0(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbVertexToInt0 from wbDefinitionsTES5.pas line 189")
}

/// Upstream `wbVertexToInt1`, line 190 of `wbDefinitionsTES5.pas`.
pub fn wb_vertex_to_int1(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbVertexToInt1 from wbDefinitionsTES5.pas line 190")
}

/// Upstream `wbVertexToInt2`, line 191 of `wbDefinitionsTES5.pas`.
pub fn wb_vertex_to_int2(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbVertexToInt2 from wbDefinitionsTES5.pas line 191")
}

/// Upstream `wbVertexToStr0`, line 223 of `wbDefinitionsTES5.pas`.
pub fn wb_vertex_to_str0(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbVertexToStr0 from wbDefinitionsTES5.pas line 223")
}

/// Upstream `wbVertexToStr1`, line 224 of `wbDefinitionsTES5.pas`.
pub fn wb_vertex_to_str1(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbVertexToStr1 from wbDefinitionsTES5.pas line 224")
}

/// Upstream `wbVertexToStr2`, line 225 of `wbDefinitionsTES5.pas`.
pub fn wb_vertex_to_str2(_a_int: i64, _a_element: ElementArg, _a_type: CallbackType) -> String {
    todo!("port wbVertexToStr2 from wbDefinitionsTES5.pas line 225")
}

/// Upstream `wbWEAPAfterLoad`, line 1686 of `wbDefinitionsTES5.pas`.
pub fn wb_weap_after_load(_a_element: &ElementRef) {
    todo!("port wbWEAPAfterLoad from wbDefinitionsTES5.pas line 1686")
}

/// Upstream `wbWorldAfterLoad`, line 51 of `wbDefinitionsTES5.pas`.
pub fn wb_world_after_load(_a_element: &ElementRef) {
    todo!("port wbWorldAfterLoad from wbDefinitionsTES5.pas line 51")
}

/// Upstream `wbWorldAfterSet`, line 69 of `wbDefinitionsTES5.pas`.
pub fn wb_world_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbWorldAfterSet from wbDefinitionsTES5.pas line 69")
}

/// Upstream `wbWorldClimateIsRemovable`, line 142 of `wbDefinitionsTES5.pas`.
pub fn wb_world_climate_is_removable(_a_element: ElementArg) -> bool {
    todo!("port wbWorldClimateIsRemovable from wbDefinitionsTES5.pas line 142")
}

/// Upstream `wbWorldWaterIsRemovable`, line 141 of `wbDefinitionsTES5.pas`.
pub fn wb_world_water_is_removable(_a_element: ElementArg) -> bool {
    todo!("port wbWorldWaterIsRemovable from wbDefinitionsTES5.pas line 141")
}

/// Upstream `wbWorldXWEMDontShow`, line 116 of `wbDefinitionsTES5.pas`.
pub fn wb_world_xwem_dont_show(_a_element: ElementArg) -> bool {
    todo!("port wbWorldXWEMDontShow from wbDefinitionsTES5.pas line 116")
}
