// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsTES5.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

//! Stubs of the callbacks that are not ported yet. Each panics when called.

#![allow(clippy::all, unused_variables, unused_imports)]

use xedit_core::interface::*;

/// Upstream `anonymous routine in define_tes5`, line 4890 of `wbDefinitionsTES5.pas`.
pub fn define_tes5_anonymous_4890(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port anonymous routine in define_tes5 from wbDefinitionsTES5.pas line 4890")
}

/// Upstream `anonymous routine in define_tes5`, line 6207 of `wbDefinitionsTES5.pas`.
pub fn define_tes5_anonymous_6207(_a_element: ElementArg) -> bool {
    todo!("port anonymous routine in define_tes5 from wbDefinitionsTES5.pas line 6207")
}

/// Upstream `wbARMAAfterLoad`, line 1643 of `wbDefinitionsTES5.pas`.
pub fn wb_arma_after_load(_a_element: &ElementRef) {
    todo!("port wbARMAAfterLoad from wbDefinitionsTES5.pas line 1643")
}

/// Upstream `wbARMOAfterLoad`, line 1638 of `wbDefinitionsTES5.pas`.
pub fn wb_armo_after_load(_a_element: &ElementRef) {
    todo!("port wbARMOAfterLoad from wbDefinitionsTES5.pas line 1638")
}

/// Upstream `wbCELLAfterLoad`, line 1773 of `wbDefinitionsTES5.pas`.
pub fn wb_cell_after_load(_a_element: &ElementRef) {
    todo!("port wbCELLAfterLoad from wbDefinitionsTES5.pas line 1773")
}

/// Upstream `wbCELLDATAAfterSet`, line 1757 of `wbDefinitionsTES5.pas`.
pub fn wb_celldata_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbCELLDATAAfterSet from wbDefinitionsTES5.pas line 1757")
}

/// Upstream `wbCELLXCLWGetConflictPriority`, line 1722 of `wbDefinitionsTES5.pas`.
pub fn wb_cellxclw_get_conflict_priority(_a_element: ElementArg, _a_conflict_priority: &mut ConflictPriority) {
    todo!("port wbCELLXCLWGetConflictPriority from wbDefinitionsTES5.pas line 1722")
}

/// Upstream `wbConditionEventToInt`, line 772 of `wbDefinitionsTES5.pas`.
pub fn wb_condition_event_to_int(_a_string: &str, _a_element: ElementArg) -> i64 {
    todo!("port wbConditionEventToInt from wbDefinitionsTES5.pas line 772")
}

/// Upstream `wbEFITAfterLoad`, line 1860 of `wbDefinitionsTES5.pas`.
pub fn wb_efit_after_load(_a_element: &ElementRef) {
    todo!("port wbEFITAfterLoad from wbDefinitionsTES5.pas line 1860")
}

/// Upstream `wbFLSTEDIDAfterSet`, line 1041 of `wbDefinitionsTES5.pas`.
pub fn wb_flstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbFLSTEDIDAfterSet from wbDefinitionsTES5.pas line 1041")
}

/// Upstream `wbFLSTLNAMIsSorted`, line 1239 of `wbDefinitionsTES5.pas`.
pub fn wb_flstlnam_is_sorted(_a_container: ElementArg) -> bool {
    todo!("port wbFLSTLNAMIsSorted from wbDefinitionsTES5.pas line 1239")
}

/// Upstream `wbGMSTEDIDAfterSet`, line 1021 of `wbDefinitionsTES5.pas`.
pub fn wb_gmstedid_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbGMSTEDIDAfterSet from wbDefinitionsTES5.pas line 1021")
}

/// Upstream `wbINFOPNAMAfterSet`, line 997 of `wbDefinitionsTES5.pas`.
pub fn wb_infopnam_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbINFOPNAMAfterSet from wbDefinitionsTES5.pas line 997")
}

/// Upstream `wbLIGHDataFlagsAfterSet`, line 2176 of `wbDefinitionsTES5.pas`.
pub fn wb_ligh_data_flags_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbLIGHDataFlagsAfterSet from wbDefinitionsTES5.pas line 2176")
}

/// Upstream `wbMGEFArchtypeAfterSet`, line 1210 of `wbDefinitionsTES5.pas`.
pub fn wb_mgef_archtype_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFArchtypeAfterSet from wbDefinitionsTES5.pas line 1210")
}

/// Upstream `wbMGEFAssocItemAfterSet`, line 1177 of `wbDefinitionsTES5.pas`.
pub fn wb_mgef_assoc_item_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFAssocItemAfterSet from wbDefinitionsTES5.pas line 1177")
}

/// Upstream `wbMGEFAV2WeightAfterSet`, line 1194 of `wbDefinitionsTES5.pas`.
pub fn wb_mgefav2_weight_after_set(_a_element: &ElementRef, _a_old_value: &Variant, _a_new_value: &Variant) {
    todo!("port wbMGEFAV2WeightAfterSet from wbDefinitionsTES5.pas line 1194")
}

/// Upstream `wbPackageDataInputValueTypeAfterSet`, line 1931 of `wbDefinitionsTES5.pas`.
pub fn wb_package_data_input_value_type_after_set(
    _a_element: &ElementRef,
    _a_old_value: &Variant,
    _a_new_value: &Variant,
) {
    todo!("port wbPackageDataInputValueTypeAfterSet from wbDefinitionsTES5.pas line 1931")
}

/// Upstream `wbRACEAfterLoad`, line 1681 of `wbDefinitionsTES5.pas`.
pub fn wb_race_after_load(_a_element: &ElementRef) {
    todo!("port wbRACEAfterLoad from wbDefinitionsTES5.pas line 1681")
}

/// Upstream `wbREFRAfterLoad`, line 1660 of `wbDefinitionsTES5.pas`.
pub fn wb_refr_after_load(_a_element: &ElementRef) {
    todo!("port wbREFRAfterLoad from wbDefinitionsTES5.pas line 1660")
}

/// Upstream `wbWEAPAfterLoad`, line 1686 of `wbDefinitionsTES5.pas`.
pub fn wb_weap_after_load(_a_element: &ElementRef) {
    todo!("port wbWEAPAfterLoad from wbDefinitionsTES5.pas line 1686")
}
