// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The record definitions of the games: the `wbDefinitions*` units of xEdit.
//!
//! `signatures.rs` and the unit modules are generated by `cargo xtask
//! port-defs`. The callbacks the definitions name are ported by hand in
//! `callbacks`, with generated stubs for the ones that are not ported yet.

pub mod callbacks;
pub mod common;
pub mod fnv;
pub mod fo3;
pub mod fo4;
pub mod fo76;
pub mod hardcoded;
pub mod reflection;
pub mod sf1;
pub mod signatures;
pub mod tes3;
pub mod tes4;
pub mod tes5;
