// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsReflection.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

#![allow(
    clippy::all,
    unused_variables,
    unused_mut,
    unused_assignments,
    unused_parens,
    unused_imports,
    unreachable_code
)]

use std::sync::Arc;

use xedit_core::delphi::*;
use xedit_core::interface::globals::*;
use xedit_core::interface::*;

use crate::callbacks::common::*;
use crate::callbacks::reflection::*;
use crate::common::*;
use crate::signatures::*;

/// Upstream `wbREFLColor`, line 147 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_color(a_name: &str) -> Option<Arc<dyn ValueDef>> {
    wb_struct(
        a_name,
        &[
            wb_len_string("Operation", 2, ConflictPriority::cpNormal, false, None, None)
                .map(|def| def.set_formater(wb_refl_operation_enum()))
                .map(|def| def.set_default_edit_value("Replace"))
                .map(|def| def as Arc<dyn ValueDef>),
            wb_float_rgba("Value", 0.0, 0.0, 0.0, 0.0),
            wb_float_scale(
                "Blend Amount",
                ConflictPriority::cpNormal,
                false,
                1.0,
                -(1),
                None,
                None,
                0.0,
                None,
            )
            .map(|def| def.set_default_native_value(Variant::from(1)))
            .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    )
    .map(|def| def.set_summary_key(&[1]))
    .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
    .map(|def| def as Arc<dyn ValueDef>)
}

/// Upstream `wbREFLEffect`, line 160 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_effect(a_name: &str) -> Option<Arc<dyn ValueDef>> {
    wb_struct_sk(
        &[0],
        a_name,
        &[
            wb_refl_form_id("Spell", &[SPEL, NULL]),
            wb_float_scale(
                "Threshold",
                ConflictPriority::cpNormal,
                false,
                1.0,
                -(1),
                None,
                None,
                0.0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    )
    .map(|def| def.set_summary_key(&[0]))
    .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
    .map(|def| def as Arc<dyn ValueDef>)
}

/// Upstream `wbREFLFloat`, line 170 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_float(a_name: &str, a_default_value: i32) -> Option<Arc<dyn ValueDef>> {
    wb_struct(
        a_name,
        &[
            wb_len_string("Operation", 2, ConflictPriority::cpNormal, false, None, None)
                .map(|def| def.set_formater(wb_refl_operation_enum()))
                .map(|def| def.set_default_edit_value("Replace"))
                .map(|def| def as Arc<dyn ValueDef>),
            wb_float_scale(
                "Value",
                ConflictPriority::cpNormal,
                false,
                1.0,
                -(1),
                None,
                None,
                0.0,
                None,
            )
            .map(|def| def.set_default_native_value(Variant::from(a_default_value)))
            .map(|def| def as Arc<dyn ValueDef>),
            wb_float_scale(
                "Blend Amount",
                ConflictPriority::cpNormal,
                false,
                1.0,
                -(1),
                None,
                None,
                0.0,
                None,
            )
            .map(|def| def.set_default_native_value(Variant::from(1)))
            .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    )
    .map(|def| def.set_summary_key(&[1]))
    .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
    .map(|def| def as Arc<dyn ValueDef>)
}

/// Upstream `wbREFLFormID`, line 183 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_form_id(a_name: &str, a_sigs: &[Signature]) -> Option<Arc<dyn ValueDef>> {
    wb_struct_sk(
        &[1],
        a_name,
        &[
            wb_integer_to_str(
                "Data Type",
                IntType::itS32,
                Some(Arc::new(wb_refl_string_to_str)),
                Some(Arc::new(wb_refl_string_to_int)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def.set_default_edit_value("UInt32"))
            .map(|def| def as Arc<dyn ValueDef>),
            wb_form_id_ck(a_name, a_sigs, false, ConflictPriority::cpNormal, false, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    )
    .map(|def| def.set_summary_key(&[1]))
    .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
    .map(|def| def as Arc<dyn ValueDef>)
}

/// Upstream `wbREFLWwiseGUID`, line 195 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_wwise_guid(a_name: &str) -> Option<Arc<dyn ValueDef>> {
    wb_struct(
        a_name,
        &[
            wb_integer_to_str(
                "Data Type",
                IntType::itS32,
                Some(Arc::new(wb_refl_string_to_str)),
                Some(Arc::new(wb_refl_string_to_int)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def.set_default_edit_value("UInt32"))
            .map(|def| def as Arc<dyn ValueDef>),
            wb_unknown_size(8, ConflictPriority::cpNormal, false, None, None).map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    )
    .map(|def| def as Arc<dyn ValueDef>)
}

/// Upstream `wbREFLColorEnum`, line 204 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_color_enum() -> Option<Arc<EnumDef>> {
    wb_enum(&["Red", "Green", "Blue", "Alpha"])
}

/// Upstream `wbREFLFloatEnum`, line 215 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_float_enum() -> Option<Arc<EnumDef>> {
    wb_enum(&["Operation", "Value", "Blend Amount"])
}

/// Upstream `wbREFLOperationEnum`, line 225 of `wbDefinitionsReflection.pas`.
pub fn wb_refl_operation_enum() -> Option<Arc<dyn StringDefFormater>> {
    wb_string_enum(&["Add", "Greater", "Multiply", "Replace"])
}

/// Upstream `wbReflection`, line 236 of `wbDefinitionsReflection.pas`.
pub fn wb_reflection(a_sig: Signature, a_data: Option<Arc<dyn ValueDef>>) -> Option<Arc<dyn RecordMemberDef>> {
    let mut result: Option<Arc<dyn RecordMemberDef>> = Default::default();
    let mut l_boolean: bool = false;
    if !(a_data.is_some()) {
        l_boolean = true;
    }
    result = wb_struct_signature(
        a_sig,
        "Reflection",
        &[
            wb_struct(
                "Reflection Header",
                &[
                    wb_string("Signature", 4, ConflictPriority::cpNormal, false, None, None, None)
                        .map(|def| def.set_default_edit_value("BETH"))
                        .map(|def| def as Arc<dyn ValueDef>),
                    wb_integer(
                        "Data Size",
                        IntType::itU32,
                        None,
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                        0,
                        None,
                    )
                    .map(|def| def.set_default_native_value(Variant::from(8)))
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_integer(
                        "Version",
                        IntType::itU32,
                        None,
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                        0,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_integer(
                        "Chunk Count",
                        IntType::itU32,
                        None,
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                        0,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                ],
                ConflictPriority::cpNormal,
                false,
                None,
                -(1),
                None,
                None,
                None,
            )
            .map(|def| def.include_flag_when(DefFlag::dfFastAssign, true))
            .map(|def| def.include_flag_when(DefFlag::dfInternalEditOnly, true))
            .map(|def| def as Arc<dyn ValueDef>),
            wb_struct(
                "String Table",
                &[
                    wb_string("Signature", 4, ConflictPriority::cpNormal, false, None, None, None)
                        .map(|def| def.set_default_edit_value("STRT"))
                        .map(|def| def as Arc<dyn ValueDef>),
                    wb_integer(
                        "Data Size",
                        IntType::itU32,
                        None,
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                        0,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_array_count(
                        "Strings",
                        wb_string("String", 0, ConflictPriority::cpNormal, false, None, None, None)
                            .map(|def| def as Arc<dyn ValueDef>),
                        0,
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                    )
                    .map(|def| def.set_should_include(Some(Arc::new(wb_reflection_anonymous_258))))
                    .map(|def| def as Arc<dyn ValueDef>),
                ],
                ConflictPriority::cpNormal,
                false,
                None,
                -(1),
                None,
                None,
                None,
            )
            .map(|def| def.set_summary_key(&[2]))
            .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
            .map(|def| def.include_flag_when(DefFlag::dfInternalEditOnly, true))
            .map(|def| def as Arc<dyn ValueDef>),
            wb_struct(
                "Type",
                &[
                    wb_string("Signature", 4, ConflictPriority::cpNormal, false, None, None, None)
                        .map(|def| def.set_default_edit_value("TYPE"))
                        .map(|def| def as Arc<dyn ValueDef>),
                    wb_integer(
                        "Data Size",
                        IntType::itU32,
                        None,
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                        0,
                        None,
                    )
                    .map(|def| def.set_default_native_value(Variant::from(4)))
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_integer(
                        "Class Count",
                        IntType::itU32,
                        None,
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                        0,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                ],
                ConflictPriority::cpNormal,
                false,
                None,
                -(1),
                None,
                None,
                None,
            )
            .map(|def| def.set_summary_key(&[2]))
            .map(|def| def.set_summary_member_prefix_suffix(2, "Class Count: ", ""))
            .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
            .map(|def| def.include_flag_when(DefFlag::dfInternalEditOnly, true))
            .map(|def| def as Arc<dyn ValueDef>),
            wb_array_count(
                "Classes",
                wb_struct(
                    "Class",
                    &[
                        wb_string("Signature", 4, ConflictPriority::cpNormal, false, None, None, None)
                            .map(|def| def.set_default_edit_value("CLAS"))
                            .map(|def| def as Arc<dyn ValueDef>),
                        wb_integer(
                            "Data Size",
                            IntType::itU32,
                            None,
                            ConflictPriority::cpNormal,
                            false,
                            None,
                            None,
                            0,
                            None,
                        )
                        .map(|def| def as Arc<dyn ValueDef>),
                        wb_integer_to_str(
                            "Class Name",
                            IntType::itS32,
                            Some(Arc::new(wb_refl_string_to_str)),
                            Some(Arc::new(wb_refl_string_to_int)),
                            ConflictPriority::cpNormal,
                            false,
                            None,
                            None,
                            0,
                            None,
                        )
                        .map(|def| def as Arc<dyn ValueDef>),
                        wb_integer_to_str(
                            "Form",
                            IntType::itS32,
                            Some(Arc::new(wb_refl_string_to_str)),
                            Some(Arc::new(wb_refl_string_to_int)),
                            ConflictPriority::cpNormal,
                            false,
                            None,
                            None,
                            0,
                            None,
                        )
                        .map(|def| def as Arc<dyn ValueDef>),
                        wb_integer(
                            "Flags",
                            IntType::itU16,
                            wb_flags_unknown_is_unused(
                                &wb_sparse_flags(
                                    &[
                                        VarRec::Int((2) as i64),
                                        VarRec::Str("User".to_owned()),
                                        VarRec::Int((3) as i64),
                                        VarRec::Str("Struct".to_owned()),
                                    ],
                                    false,
                                    4,
                                )
                                .iter()
                                .map(String::as_str)
                                .collect::<Vec<_>>(),
                                false,
                            )
                            .map(|def| def as Arc<dyn IntegerDefFormater>),
                            ConflictPriority::cpNormal,
                            false,
                            None,
                            None,
                            0,
                            None,
                        )
                        .map(|def| def.include_flag_when(DefFlag::dfCollapsed, collapse_flags()))
                        .map(|def| def as Arc<dyn ValueDef>),
                        wb_array_count(
                            "Fields",
                            wb_struct(
                                "Field",
                                &[
                                    wb_integer_to_str(
                                        "Field Name",
                                        IntType::itS32,
                                        Some(Arc::new(wb_refl_string_to_str)),
                                        Some(Arc::new(wb_refl_string_to_int)),
                                        ConflictPriority::cpNormal,
                                        false,
                                        None,
                                        None,
                                        0,
                                        None,
                                    )
                                    .map(|def| def as Arc<dyn ValueDef>),
                                    wb_integer_to_str(
                                        "Field Type",
                                        IntType::itS32,
                                        Some(Arc::new(wb_refl_string_to_str)),
                                        Some(Arc::new(wb_refl_string_to_int)),
                                        ConflictPriority::cpNormal,
                                        false,
                                        None,
                                        None,
                                        0,
                                        None,
                                    )
                                    .map(|def| def as Arc<dyn ValueDef>),
                                    wb_integer(
                                        "Offset",
                                        IntType::itU16,
                                        None,
                                        ConflictPriority::cpNormal,
                                        false,
                                        None,
                                        None,
                                        0,
                                        None,
                                    )
                                    .map(|def| def as Arc<dyn ValueDef>),
                                    wb_integer(
                                        "Size",
                                        IntType::itU16,
                                        None,
                                        ConflictPriority::cpNormal,
                                        false,
                                        None,
                                        None,
                                        0,
                                        None,
                                    )
                                    .map(|def| def as Arc<dyn ValueDef>),
                                ],
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                -(1),
                                None,
                                None,
                                None,
                            )
                            .map(|def| def.set_summary_key(&[0]))
                            .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
                            .map(|def| def as Arc<dyn ValueDef>),
                            -(2),
                            ConflictPriority::cpNormal,
                            false,
                            None,
                            None,
                        )
                        .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
                        .map(|def| def as Arc<dyn ValueDef>),
                    ],
                    ConflictPriority::cpNormal,
                    false,
                    None,
                    -(1),
                    None,
                    None,
                    None,
                )
                .map(|def| def.set_summary_key(&[2]))
                .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
                .map(|def| def as Arc<dyn ValueDef>),
                0,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def.set_count_path("Type\\Class Count", true))
            .map(|def| def.include_flag_when(DefFlag::dfCollapsed, true))
            .map(|def| def.include_flag_when(DefFlag::dfInternalEditOnly, true))
            .map(|def| def as Arc<dyn ValueDef>),
            if_then_value_def(
                l_boolean,
                wb_unknown_size(0, ConflictPriority::cpNormal, false, None, None).map(|def| def as Arc<dyn ValueDef>),
                None,
            ),
            a_data.clone(),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    )
    .map(|def| def.include_flag_when(DefFlag::dfCanContainReflection, true))
    .map(|def| def.include_flag_when(DefFlag::dfFastAssign, true))
    .map(|def| def.include_flag_when(DefFlag::dfIsReflection, true))
    .map(|def| def as Arc<dyn RecordMemberDef>);
    result
}
