// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Ported from xEdit: Core/wbDefinitionsTES4Saves.pas

// Generated by `cargo xtask port-defs emit-unit`. Do not edit.

#![allow(
    clippy::all,
    unused_variables,
    unused_mut,
    unused_assignments,
    unused_parens,
    unused_imports,
    unreachable_code
)]

use std::sync::Arc;

use xedit_core::delphi::*;
use xedit_core::interface::globals::*;
use xedit_core::interface::*;

use crate::callbacks::common::*;
use crate::callbacks::save_interface::*;
use crate::callbacks::tes4saves::*;
use crate::common::*;
use crate::signatures::*;
use crate::tes4::*;

/// Upstream `wbActorValueLabels`.
pub static WB_ACTOR_VALUE_LABELS: Global<Vec<String>> = Global::new();

/// Upstream `wbSaveChapters`.
pub static WB_SAVE_CHAPTERS: Global<Option<Arc<StructDef>>> = Global::new();

/// Upstream `wbCoSaveChapters`.
pub static WB_CO_SAVE_CHAPTERS: Global<Option<Arc<StructDef>>> = Global::new();

/// Upstream `wbSaveHeader`.
pub static WB_SAVE_HEADER: Global<Option<Arc<StructDef>>> = Global::new();

/// Upstream `wbCoSaveHeader`.
pub static WB_CO_SAVE_HEADER: Global<Option<Arc<StructDef>>> = Global::new();

/// Upstream `DefineTES4SavesS`, line 1819 of `wbDefinitionsTES4Saves.pas`.
pub fn define_tes4_saves_s() {
    let mut wb_header: Option<Arc<StructDef>> = Default::default();
    let mut wb_file_location_table: Option<Arc<StructDef>> = Default::default();
    let mut wb_global_data: Option<Arc<StructDef>> = Default::default();
    let mut wb_changed_form: Option<Arc<StructDef>> = Default::default();
    let mut wb_null: Option<Arc<dyn ValueDef>> = Default::default();
    let mut wb_co_save_chunk: Option<Arc<StructDef>> = Default::default();
    let mut wb_co_save_chunks: Option<Arc<ArrayDef>> = Default::default();
    let mut wb_co_save_plugin: Option<Arc<StructDef>> = Default::default();
    let mut wb_co_save_plugins: Option<Arc<ArrayDef>> = Default::default();
    wb_null = wb_byte_array_size("Unused", -(255), ConflictPriority::cpNormal, false, None, None)
        .map(|def| def as Arc<dyn ValueDef>);
    wb_header = wb_struct(
        "Header",
        &[
            wb_integer_t(
                "Version",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_string_t("Language", 64, ConflictPriority::cpNormal, false, None, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
            wb_integer_t(
                "Screenshot Width",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer_t(
                "Screenshot Height",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer_t(
                "Save Number",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_len_string_t("Player Name", -(3), ConflictPriority::cpNormal, false, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
            wb_len_string_t("Player Status", -(3), ConflictPriority::cpNormal, false, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
            wb_integer_t(
                "Player Level",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_len_string_t("Player Cell", -(3), ConflictPriority::cpNormal, false, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
            wb_len_string_t("Save Duration", -(3), ConflictPriority::cpNormal, false, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    );
    wb_file_location_table = wb_struct(
        "File Location Table",
        &[
            wb_integer(
                "RefID Array Count Offset",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Unknown Table Offset",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Global Data Table 1 Offset",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Changed Forms Offset",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Global Data Table 2 Offset",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Global Data Table 1 Count",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Global Data Table 2 Count",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Changed Forms Count",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Unknown Count",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_byte_array_size(
                "Unused",
                (0x6e - (9 * 4)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    );
    WB_SAVE_HEADER.set(wb_struct(
        "Save File Header",
        &[
            wb_string("Magic", 11, ConflictPriority::cpNormal, false, None, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Header Size",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_header.clone().map(|def| def as Arc<dyn ValueDef>),
            wb_byte_array_count_callback(
                "Hidden: Screenshot Data",
                Some(Arc::new(screen_shot_data_counter)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Form Version",
                IntType::itU8,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "PluginInfo Size",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_array_pt_count(
                &file_plugins(),
                wb_len_string_t("PluginName", -(3), ConflictPriority::cpNormal, false, None, None)
                    .map(|def| def as Arc<dyn ValueDef>),
                -(4),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_file_location_table.clone().map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    ));
    WB_SAVE_CHAPTERS.set(wb_struct(
        "Save File Chapters",
        &[
            wb_array_labels_count_callback(
                "Global Data 1",
                wb_global_data.clone().map(|def| def as Arc<dyn ValueDef>),
                &[],
                Some(Arc::new(global_data1_counter)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_array_labels_count_callback(
                "Changed Forms",
                wb_changed_form.clone().map(|def| def as Arc<dyn ValueDef>),
                &[],
                Some(Arc::new(changed_forms_counter)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_array_labels_count_callback(
                "Global Data 2",
                wb_global_data.clone().map(|def| def as Arc<dyn ValueDef>),
                &[],
                Some(Arc::new(global_data2_counter)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_array_after_load(
                "FormIDs",
                wb_form_id_name("FormID", ConflictPriority::cpFormID, false, None, None)
                    .map(|def| def as Arc<dyn ValueDef>),
                -(1),
                Some(Arc::new(ref_id_table_after_load)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_array_after_load(
                "Visited Worldspace",
                wb_form_id_name("FormID", ConflictPriority::cpFormID, false, None, None)
                    .map(|def| def as Arc<dyn ValueDef>),
                -(1),
                Some(Arc::new(worldspace_table_after_load)),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_array_count(
                "Unknown Table",
                wb_integer(
                    "Unknown",
                    IntType::itU8,
                    None,
                    ConflictPriority::cpNormal,
                    false,
                    None,
                    None,
                    0,
                    None,
                )
                .map(|def| def as Arc<dyn ValueDef>),
                -(1),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    ));
    WB_CO_SAVE_HEADER.set(wb_struct(
        "CoSave File Header",
        &[
            wb_string("Magic", 4, ConflictPriority::cpNormal, false, None, None, None)
                .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Version",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "OBSE Version",
                IntType::itU16,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "OBSE Minor Version",
                IntType::itU16,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Fallout Version",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Plugins count",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    ));
    wb_co_save_chunk = wb_struct_c(
        "Chunk",
        None,
        Some(Arc::new(wb_co_save_chunk_type)),
        Some(Arc::new(wb_co_save_chunk_type_name)),
        None,
        &[
            wb_integer(
                "Type",
                IntType::itU32,
                wb_str4().map(|def| def as Arc<dyn IntegerDefFormater>),
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Version",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Length",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_union_after_set(
                "Data",
                Some(Arc::new(obse_chapters_decider)),
                &[
                    wb_null.clone(),
                    wb_array_count(
                        "Modules",
                        wb_len_string("PluginName", 2, ConflictPriority::cpNormal, false, None, None)
                            .map(|def| def as Arc<dyn ValueDef>),
                        -(4),
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_null.clone(),
                    wb_struct(
                        "String_var",
                        &[
                            wb_integer(
                                "Owning Module Index",
                                IntType::itU8,
                                None,
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                                0,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                            wb_integer(
                                "ID",
                                IntType::itU32,
                                None,
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                                0,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                            wb_len_string("Value", 2, ConflictPriority::cpNormal, false, None, None)
                                .map(|def| def as Arc<dyn ValueDef>),
                        ],
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        -(1),
                        None,
                        None,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_null.clone(),
                    wb_null.clone(),
                    wb_struct(
                        "Array_var",
                        &[
                            wb_integer(
                                "Owning Module Index",
                                IntType::itU8,
                                None,
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                                0,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                            wb_integer(
                                "ID",
                                IntType::itU32,
                                None,
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                                0,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                            wb_integer(
                                "Key Type",
                                IntType::itU8,
                                WB_CO_SAVE_ARRAY_TYPE_ENUM
                                    .get()
                                    .map(|def| def as Arc<dyn IntegerDefFormater>),
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                                0,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                            wb_integer(
                                "Packed",
                                IntType::itU8,
                                None,
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                                0,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                            wb_array_count(
                                "Refs",
                                wb_integer(
                                    "Ref",
                                    IntType::itU8,
                                    None,
                                    ConflictPriority::cpNormal,
                                    false,
                                    None,
                                    None,
                                    0,
                                    None,
                                )
                                .map(|def| def as Arc<dyn ValueDef>),
                                -(1),
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                            wb_array_count(
                                "Elements",
                                wb_struct(
                                    "Element",
                                    &[
                                        wb_union_after_set(
                                            "Key",
                                            Some(Arc::new(wb_co_save_array_key_element_decider)),
                                            &[
                                                wb_null.clone(),
                                                wb_double_scale(
                                                    "Numeric Key",
                                                    ConflictPriority::cpNormal,
                                                    false,
                                                    1.0,
                                                    -(1),
                                                    None,
                                                    None,
                                                    0.0,
                                                    None,
                                                )
                                                .map(|def| def as Arc<dyn ValueDef>),
                                                wb_len_string(
                                                    "String Key",
                                                    2,
                                                    ConflictPriority::cpNormal,
                                                    false,
                                                    None,
                                                    None,
                                                )
                                                .map(|def| def as Arc<dyn ValueDef>),
                                            ],
                                            ConflictPriority::cpNormal,
                                            false,
                                            None,
                                            None,
                                            None,
                                        )
                                        .map(|def| def as Arc<dyn ValueDef>),
                                        wb_integer(
                                            "Data Type",
                                            IntType::itU8,
                                            WB_CO_SAVE_ARRAY_TYPE_ENUM
                                                .get()
                                                .map(|def| def as Arc<dyn IntegerDefFormater>),
                                            ConflictPriority::cpNormal,
                                            false,
                                            None,
                                            None,
                                            0,
                                            None,
                                        )
                                        .map(|def| def as Arc<dyn ValueDef>),
                                        wb_union_after_set(
                                            "Data",
                                            Some(Arc::new(wb_co_save_array_data_element_decider)),
                                            &[
                                                wb_null.clone(),
                                                wb_double_scale(
                                                    "Numeric Data",
                                                    ConflictPriority::cpNormal,
                                                    false,
                                                    1.0,
                                                    -(1),
                                                    None,
                                                    None,
                                                    0.0,
                                                    None,
                                                )
                                                .map(|def| def as Arc<dyn ValueDef>),
                                                wb_form_id_name(
                                                    "Form Data",
                                                    ConflictPriority::cpNormal,
                                                    false,
                                                    None,
                                                    None,
                                                )
                                                .map(|def| def as Arc<dyn ValueDef>),
                                                wb_len_string(
                                                    "String Data",
                                                    2,
                                                    ConflictPriority::cpNormal,
                                                    false,
                                                    None,
                                                    None,
                                                )
                                                .map(|def| def as Arc<dyn ValueDef>),
                                                wb_integer(
                                                    "Array Data",
                                                    IntType::itU32,
                                                    None,
                                                    ConflictPriority::cpNormal,
                                                    false,
                                                    None,
                                                    None,
                                                    0,
                                                    None,
                                                )
                                                .map(|def| def as Arc<dyn ValueDef>),
                                            ],
                                            ConflictPriority::cpNormal,
                                            false,
                                            None,
                                            None,
                                            None,
                                        )
                                        .map(|def| def as Arc<dyn ValueDef>),
                                    ],
                                    ConflictPriority::cpNormal,
                                    false,
                                    None,
                                    -(1),
                                    None,
                                    None,
                                    None,
                                )
                                .map(|def| def as Arc<dyn ValueDef>),
                                -(1),
                                ConflictPriority::cpNormal,
                                false,
                                None,
                                None,
                            )
                            .map(|def| def as Arc<dyn ValueDef>),
                        ],
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        -(1),
                        None,
                        None,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_null.clone(),
                    wb_array_count_callback(
                        "Globals",
                        wb_struct(
                            "Global",
                            &[
                                wb_integer(
                                    "ID",
                                    IntType::itU8,
                                    None,
                                    ConflictPriority::cpNormal,
                                    false,
                                    None,
                                    None,
                                    0,
                                    None,
                                )
                                .map(|def| def as Arc<dyn ValueDef>),
                                wb_double_scale(
                                    "Value",
                                    ConflictPriority::cpNormal,
                                    false,
                                    1.0,
                                    -(1),
                                    None,
                                    None,
                                    0.0,
                                    None,
                                )
                                .map(|def| def as Arc<dyn ValueDef>),
                            ],
                            ConflictPriority::cpNormal,
                            false,
                            None,
                            -(1),
                            None,
                            None,
                            None,
                        )
                        .map(|def| def as Arc<dyn ValueDef>),
                        Some(Arc::new(obse_chapter_global_counter)),
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                    wb_byte_array_count_callback(
                        "Others",
                        Some(Arc::new(wb_co_save_chapter_other_counter)),
                        ConflictPriority::cpNormal,
                        false,
                        None,
                        None,
                    )
                    .map(|def| def as Arc<dyn ValueDef>),
                ],
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    );
    wb_co_save_chunks = wb_array_count_callback(
        "Chunks",
        wb_co_save_chunk.clone().map(|def| def as Arc<dyn ValueDef>),
        Some(Arc::new(wb_co_save_chunk_counter)),
        ConflictPriority::cpNormal,
        false,
        Some(Arc::new(wb_dont_show_branch)),
        None,
    );
    wb_co_save_plugin = wb_struct_c(
        "Plugin",
        None,
        Some(Arc::new(wb_co_save_array_type)),
        Some(Arc::new(wb_co_save_array_type_name)),
        None,
        &[
            wb_integer(
                "Opcode Base",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Chunks count",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_integer(
                "Length",
                IntType::itU32,
                None,
                ConflictPriority::cpNormal,
                false,
                None,
                None,
                0,
                None,
            )
            .map(|def| def as Arc<dyn ValueDef>),
            wb_co_save_chunks.clone().map(|def| def as Arc<dyn ValueDef>),
        ],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    );
    if let Some(def) = &wb_co_save_chunks.clone() {
        def.set_tree_branch(true);
    }
    wb_co_save_plugins = wb_array_count_callback(
        "Plugins",
        wb_co_save_plugin.clone().map(|def| def as Arc<dyn ValueDef>),
        Some(Arc::new(wb_co_save_plugin_counter)),
        ConflictPriority::cpNormal,
        false,
        None,
        None,
    );
    WB_CO_SAVE_CHAPTERS.set(wb_struct(
        "CoSave File Chapters",
        &[wb_co_save_plugins.clone().map(|def| def as Arc<dyn ValueDef>)],
        ConflictPriority::cpNormal,
        false,
        None,
        -(1),
        None,
        None,
        None,
    ));
    set_file_chapters(WB_SAVE_CHAPTERS.get());
    set_file_header(WB_SAVE_HEADER.get());
    if let Some(def) = &WB_SAVE_HEADER.get() {
        def.set_tree_head(true);
    }
    if let Some(def) = &WB_CO_SAVE_HEADER.get() {
        def.set_tree_head(true);
    }
}
